"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import numpy as np
from data.financial import get_financial_data
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer

def compute_rps(kline_dict, codes):
    """
    计算全市场股票的250日RPS（相对价格强度）排名。
    
    kline_dict: {code: kline_df}，kline_df 含 'close' / '收盘' 列
    codes: 需要计算RPS的股票代码列表
    
    返回: {code: rps_value}，rps_value 范围 0-100
    如果某股票K线不足250日，RPS=0
    """
    rps_map = {}
    code_returns = {}
    
    for code in codes:
        df = kline_dict.get(code)
        if df is None or len(df) < 250:
            rps_map[code] = 0
            continue
        close_col = '收盘' if '收盘' in df.columns else 'close'
        if close_col not in df.columns:
            rps_map[code] = 0
            continue
        closes = df[close_col].values.astype(float)
        if len(closes) < 250:
            rps_map[code] = 0
            continue
        ret_250 = (closes[-1] / closes[-250] - 1) * 100
        code_returns[code] = ret_250
    
    if not code_returns:
        return rps_map
    
    # 按收益排名，计算百分位
    sorted_codes = sorted(code_returns, key=code_returns.get)
    n = len(sorted_codes)
    for i, code in enumerate(sorted_codes):
        rps_map[code] = round((i + 1) / n * 100, 1)
    
    return rps_map

def calculate_canslim_score(code, kline_df, stock_pool_context=None):
    """
    CAN SLIM 七因子简化版评分（基于K线+行情数据，财务因子占位）。
    
    维度（满分100）：
    - C_业绩增速（15分）：扣非净利润同比≥25%→15, ≥15%→10, ≥5%→5, 否则0
    - A_持续增长（15分）：ROE≥17%+CAGR≥20%→15, 仅ROE→8, 仅CAGR≥15%→5
    - N_新催化（15分）：距52周高点≤15%→15，≤25%→8，否则0
    - S_中小盘（10分）：总市值<500亿→10，<1000亿→5，否则0
    - L_RPS（20分）：RPS≥80→20，≥60→10，否则0
    - I_流动性（10分）：换手率2%-15%→10，1%-20%→5，否则0
    - M_大势（15分）：多头排列+>MA200→15，任一满足→7，否则0
    
    kline_df: 含 'close'/'收盘', 'open'/'开盘', 'high'/'最高', 'low'/'最低', 'volume'/'成交量' 等列
    stock_pool_context: dict，含 'rps', 'market_cap', 'turnover_rate' 等
    """
    close_col = '收盘' if '收盘' in kline_df.columns else 'close'
    high_col = '最高' if '最高' in kline_df.columns else 'high'
    volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'
    
    closes = kline_df[close_col].values.astype(float)
    highs = kline_df[high_col].values.astype(float)
    volumes = kline_df[volume_col].values.astype(float)
    n = len(closes)
    
    if n < 60:
        return {"pass": False, "综合评分": 0,
                "C_业绩增速": 0, "A_持续增长": 0, "N_新催化": 0,
                "S_中小盘": 0, "L_RPS": 0, "I_流动性": 0, "M_大势": 0}
    
    # --- C_业绩增速（15分）：扣非净利润同比 ---
    c_score = -1  # -1 = N/A: 财务数据不可用
    fin_cs = stock_pool_context.get('fin') if stock_pool_context else None
    if fin_cs and fin_cs.get('success'):
        g = fin_cs.get('eps_growth_yoy', 0)
        if g >= 0.25:
            c_score = 15
        elif g >= 0.15:
            c_score = 10
        elif g >= 0.05:
            c_score = 5
        else:
            c_score = 0
    
    # --- A_持续增长（15分）：ROE + 3年净利润CAGR ---
    a_score = -1  # -1 = N/A: 财务数据不可用
    if fin_cs and fin_cs.get('success'):
        roe = fin_cs.get('roe', 0)
        cagr = fin_cs.get('eps_cagr_3y')
        ok_roe = roe >= 0.17
        ok_cagr = cagr is not None and cagr >= 0.15
        if ok_roe and (cagr is not None and cagr >= 0.20):
            a_score = 15
        elif ok_roe:
            a_score = 8
        elif ok_cagr:
            a_score = 5
        else:
            a_score = 0
    
    # --- N_新催化：股价距52周高点 ---
    n_score = 0
    lookback = min(250, n)
    high_52w = np.max(highs[-lookback:])
    current_close = closes[-1]
    if high_52w > 0:
        dist_from_high = (high_52w - current_close) / high_52w * 100
        if dist_from_high <= 15:
            n_score = 15
        elif dist_from_high <= 25:
            n_score = 8
    
    # --- S_中小盘（优先财务数据，fallback 上下文） ---
    s_score = -1  # -1 = N/A: 无市值数据
    cap_yi = None
    if fin_cs and fin_cs.get('success') and fin_cs.get('market_cap', 0) > 0:
        cap_yi = fin_cs['market_cap']
    elif stock_pool_context:
        market_cap = stock_pool_context.get('market_cap', 0)
        if market_cap > 0:
            cap_yi = market_cap / 1e8  # 元转亿
    if cap_yi is not None and cap_yi > 0:
        if cap_yi < 500:
            s_score = 10
        elif cap_yi < 1000:
            s_score = 5
        else:
            s_score = 0
    
    # --- L_RPS ---
    l_score = 0
    if stock_pool_context:
        rps = stock_pool_context.get('rps', 0)
        if rps >= 80:
            l_score = 20
        elif rps >= 60:
            l_score = 10
    
    # --- I_流动性（优先财务数据，fallback 上下文） ---
    i_score = -1  # -1 = N/A: 无换手率数据（与 C/A 维度一致）
    turnover = 0
    if fin_cs and fin_cs.get('success') and fin_cs.get('turnover_rate', 0) > 0:
        turnover = fin_cs['turnover_rate']
    elif stock_pool_context:
        raw_t = stock_pool_context.get('turnover_rate', 0)
        if raw_t > 0:
            turnover = raw_t
    if turnover > 0:
        if 2 <= turnover <= 15:
            i_score = 10
        elif 1 <= turnover <= 20:
            i_score = 5
        else:
            i_score = 0
    
    # --- M_大势：均线多头排列 + 价格>MA200 ---
    m_score = 0
    cond1 = False  # 均线多头排列 MA5>MA20>MA60
    cond2 = False  # 收盘价 > MA200
    
    if n >= 60:
        ma5 = np.mean(closes[-5:])
        ma20 = np.mean(closes[-20:])
        ma60 = np.mean(closes[-60:])
        if ma5 > ma20 > ma60:
            cond1 = True
    
    if n >= 200:
        ma200 = np.mean(closes[-200:])
        if current_close > ma200:
            cond2 = True
    
    if cond1 and cond2:
        m_score = 15
    elif cond1 or cond2:
        m_score = 7
    
    # 综合评分：N/A（-1）维度按0计入总分
    def _safe(v):
        return 0 if v < 0 else v
    total = _safe(c_score) + _safe(a_score) + _safe(n_score) + _safe(s_score) + _safe(l_score) + _safe(i_score) + _safe(m_score)
    
    return {
        "pass": True,
        "综合评分": total,
        "C_业绩增速": c_score,
        "A_持续增长": a_score,
        "N_新催化": n_score,
        "S_中小盘": s_score,
        "L_RPS": l_score,
        "I_流动性": i_score,
        "M_大势": m_score,
    }


# ═══════════════════════════════════════════════════
#  CanslimScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

CANSLIM_DIM_NAMES = ["C_业绩增速", "A_持续增长", "N_新催化", "S_中小盘", "L_RPS", "I_流动性", "M_大势"]
CANSLIM_RAW_KEYS = ["c", "a", "n", "s", "l", "i", "m"]


@register_scorer
class CanslimScorer(BaseScorer):
    """CAN SLIM 七因子简化版评分（C_业绩增速/A_持续增长/N_新催化/S_中小盘/L_RPS/I_流动性/M_大势）"""

    model_name = "canslim"

    def compute(self, si: ScoreInput) -> ScoreResult:
        code = si.code
        kline_df = si.kline_df
        ctx = si.stock_pool_context

        if kline_df is None or len(kline_df) < 60:
            return ScoreResult(
                score=0, passed=False, filter_msg="K线不足60日",
                dimensions={k: 0 for k in CANSLIM_DIM_NAMES},
                raw={k: 0 for k in CANSLIM_RAW_KEYS},
            )

        close_col = '收盘' if '收盘' in kline_df.columns else 'close'
        high_col = '最高' if '最高' in kline_df.columns else 'high'
        volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'
        closes = kline_df[close_col].values.astype(float)
        highs = kline_df[high_col].values.astype(float)
        volumes = kline_df[volume_col].values.astype(float)
        n = len(closes)

        fin_cs = ctx.get('fin') if ctx else None

        # C_业绩增速
        c_score = -1
        if fin_cs and fin_cs.get('success'):
            g = fin_cs.get('eps_growth_yoy', 0)
            if g >= 0.25: c_score = 15
            elif g >= 0.15: c_score = 10
            elif g >= 0.05: c_score = 5
            else: c_score = 0

        # A_持续增长
        a_score = -1
        if fin_cs and fin_cs.get('success'):
            roe = fin_cs.get('roe', 0)
            cagr = fin_cs.get('eps_cagr_3y')
            ok_roe = roe >= 0.17
            ok_cagr = cagr is not None and cagr >= 0.15
            if ok_roe and (cagr is not None and cagr >= 0.20): a_score = 15
            elif ok_roe: a_score = 8
            elif ok_cagr: a_score = 5
            else: a_score = 0

        # N_新催化
        n_score = 0
        lookback = min(250, n)
        high_52w = np.max(highs[-lookback:])
        current_close = closes[-1]
        if high_52w > 0:
            dist = (high_52w - current_close) / high_52w * 100
            if dist <= 15: n_score = 15
            elif dist <= 25: n_score = 8

        # S_中小盘
        s_score = -1
        cap_yi = None
        if fin_cs and fin_cs.get('success') and fin_cs.get('market_cap', 0) > 0:
            cap_yi = fin_cs['market_cap']
        elif ctx:
            market_cap = ctx.get('market_cap', 0)
            if market_cap > 0: cap_yi = market_cap / 1e8
        if cap_yi is not None and cap_yi > 0:
            if cap_yi < 500: s_score = 10
            elif cap_yi < 1000: s_score = 5
            else: s_score = 0

        # L_RPS
        l_score = 0
        if ctx:
            rps = ctx.get('rps', 0)
            if rps >= 80: l_score = 20
            elif rps >= 60: l_score = 10

        # I_流动性
        i_score = -1
        turnover = 0
        if fin_cs and fin_cs.get('success') and fin_cs.get('turnover_rate', 0) > 0:
            turnover = fin_cs['turnover_rate']
        elif ctx:
            raw_t = ctx.get('turnover_rate', 0)
            if raw_t > 0: turnover = raw_t
        if turnover > 0:
            if 2 <= turnover <= 15: i_score = 10
            elif 1 <= turnover <= 20: i_score = 5
            else: i_score = 0

        # M_大势
        m_score = 0
        cond1 = cond2 = False
        if n >= 60:
            ma5 = np.mean(closes[-5:])
            ma20 = np.mean(closes[-20:])
            ma60 = np.mean(closes[-60:])
            if ma5 > ma20 > ma60: cond1 = True
        if n >= 200:
            ma200 = np.mean(closes[-200:])
            if current_close > ma200: cond2 = True
        if cond1 and cond2: m_score = 15
        elif cond1 or cond2: m_score = 7

        def _safe(v):
            return 0 if v < 0 else v
        total = _safe(c_score) + _safe(a_score) + n_score + _safe(s_score) + l_score + _safe(i_score) + m_score

        return ScoreResult(
            score=total, passed=True,
            dimensions={
                "C_业绩增速": _safe(c_score), "A_持续增长": _safe(a_score),
                "N_新催化": n_score, "S_中小盘": _safe(s_score),
                "L_RPS": l_score, "I_流动性": _safe(i_score), "M_大势": m_score,
            },
            raw={"c": c_score, "a": a_score, "n": n_score, "s": s_score,
                 "l": l_score, "i": i_score, "m": m_score},
        )
