"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from core.config import CYCLE_SECTOR, DEFAULT_WEIGHTS, GROWTH_SECTOR, _industry_pe_cache
from data.sector import _get_cached_dragon_tiger, _get_cached_sector_data, _get_sector_fund_flow, fetch_dragon_tiger_v3, fetch_sector_board_v3, _classify_stock_sector
from data.dde import _load_dde_data, get_resonance_cache, save_resonance_cache, _get_resonance_cross_ref
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer


def _estimate_pe_percentile(pe_val):
    """PE历史分位估算（0~100）"""
    if pd.isna(pe_val) or pe_val <= 0:
        return 50
    if pe_val < 15: return 15
    elif pe_val < 25: return 35
    elif pe_val < 40: return 55
    elif pe_val < 60: return 70
    elif pe_val < 80: return 82
    else: return 92

def score_trend_struct_v3(sd):
    """趋势结构 — 左侧见底/右侧突破/量价配合"""
    try:
        zx_score = sd.get('zx_score', 0) or 0
        macd_trend = sd.get('macd_trend', 0) or 0
        vol_score = sd.get('vol_score', 0) or 0
        zb_score = sd.get('zb_score', 0) or 0
        score = (zx_score * 8 + max(macd_trend, 0) * 5 + vol_score * 5 + zb_score * 7) / 25 * 25
        return max(0, min(25, score))
    except Exception:
        return 0

def score_momentum_v3(sd):
    """动量强度 — 均线多头排列 + 近期涨幅健康"""
    try:
        ma_score = sd.get('ma_score', 0) or 0
        vol_score = sd.get('vol_score', 0) or 0
        ret_5d = sd.get('ret_5d', 0) or 0
        ret_10d = sd.get('ret_10d', 0) or 0
        mom = ma_score * 8 + vol_score * 5
        if ret_5d > 0: mom += 3
        if ret_10d > 0: mom += 3
        if ret_5d > 10: mom -= 2
        if ret_5d > 20: mom -= 3
        return max(0, min(22, mom))
    except Exception:
        return 0

def score_sector_resonance_v3(sd):
    """板块共振 — 所属板块热度"""
    return max(0, min(10, (sd.get('sector_score', 0) or 0) * 2))

def score_north_capital_v3(sd):
    """北向资金 — 近3/5/10日净买"""
    try:
        nb3 = sd.get('north_buy_3d', 0) or 0; nb5 = sd.get('north_buy_5d', 0) or 0
        nb10 = sd.get('north_buy_10d', 0) or 0
        if nb3 is None or nb5 is None or nb10 is None: return -1
        score = (nb3 * 4 + nb5 * 3 + nb10 * 3) / 20000000 * 10
        return max(0, min(10, score))
    except: return 0

def score_inst_capital_v3(sd):
    """机构净买 — 3日机构净买入"""
    try:
        ib3 = sd.get('inst_buy_3d', 0) or 0; ib5 = sd.get('inst_buy_5d', 0) or 0
        if ib3 is None or ib5 is None: return -1
        score = (ib3 * 5 + ib5 * 5) / 20000000 * 10
        return max(0, min(10, score))
    except: return 0

def score_sector_fund_heat_v3(sd):
    """板块资金热度 — 板块整体资金流向热度"""
    try:
        fh = sd.get('sector_fund_heat', 0) or 0
        return max(0, min(10, fh * 2))
    except Exception: return 0

def score_volume_price_v3(sd):
    """量价配合 — 趋势确认+量能"""
    try:
        vp_score = sd.get('vp_score', 0) or 0
        return max(0, min(12, vp_score * 3))
    except Exception: return 0

def score_valuation_v3(sd):
    """估值安全 — PE分位+市净率"""
    try:
        pe_pct = sd.get('pe_percentile', 50) or 50
        pb = sd.get('pb', 2) or 2
        if pe_pct < 0: return -1
        score = (100 - abs(pe_pct - 50)) * 0.1 + max(0, 5 - min(pb, 5))
        return max(0, min(10, score))
    except Exception: return 0

def score_chip_v3(sd):
    """筹码稳定 — 股东人数变化+换手率"""
    try:
        chip_s = sd.get('chip_stability', 0) or 0
        if chip_s < 0: return -1
        return max(0, min(7, chip_s))
    except Exception: return 0

def score_sentiment_v3(sd):
    """情绪热度 — 换手率相对位置"""
    try:
        turn_pct = sd.get('turnover_percentile', 50) or 50
        if turn_pct < 0: return -1
        if turn_pct > 80: return 1
        if turn_pct > 60: return 2
        if turn_pct > 40: return 3
        return 4
    except Exception: return 0

def _calc_macd_divergence(kline_df):
    """检测MACD顶背离（简化版）"""
    if kline_df is None or len(kline_df) < 35:
        return False
    close = kline_df['收盘']
    ema12 = close.ewm(span=12).mean()
    ema26 = close.ewm(span=26).mean()
    dif = ema12 - ema26
    dea = dif.ewm(span=9).mean()
    macd_bar = (dif - dea) * 2
    if len(close) >= 10:
        recent = close.tail(10)
        recent_macd = macd_bar.tail(10)
        price_high_idx = recent.idxmax()
        if price_high_idx == recent.index[-1]:
            if len(recent_macd) >= 2 and recent_macd.iloc[-1] < recent_macd.iloc[-3] if len(recent_macd) >= 3 else False:
                return True
    return False


def _build_stock_data(row, kline_df, lhb_data, sector_data, stock_sector_map=None):
    """将stock_screener数据转换为v3评分函数所需的stock_data字典"""
    code = str(row.get('代码', ''))
    name = str(row.get('名称', ''))

    # 从K线计算MA
    ma5 = ma10 = ma20 = ma60 = 0
    ma5_prev = ma10_prev = ma20_prev = ma60_prev = 0
    new_high_2d = False
    new_high_today = False
    vol_today = 1
    ma5_vol = 1
    close = float(row.get('最新价', 10))
    amp = float(row.get('振幅', 5))

    if kline_df is not None and len(kline_df) >= 60:
        c = kline_df['收盘']
        ma5 = c.rolling(5).mean().iloc[-1]
        ma10 = c.rolling(10).mean().iloc[-1]
        ma20 = c.rolling(20).mean().iloc[-1]
        ma60 = c.rolling(60).mean().iloc[-1]
        if len(c) >= 6:
            ma5_prev = c.rolling(5).mean().iloc[-2]
            ma10_prev = c.rolling(10).mean().iloc[-2]
            ma20_prev = c.rolling(20).mean().iloc[-2]
            ma60_prev = c.rolling(60).mean().iloc[-2]
        close = float(c.iloc[-1])
        # 新高判断
        if len(c) >= 3:
            new_high_today = c.iloc[-1] >= c.tail(20).max()
            new_high_2d = c.iloc[-1] >= c.tail(20).max() and c.iloc[-2] >= c.tail(21).iloc[:-1].max()
        # 成交量
        v = kline_df['成交量']
        vol_today = float(v.iloc[-1]) if len(v) > 0 else 1
        ma5_vol = float(v.rolling(5).mean().iloc[-1]) if len(v) >= 5 else vol_today
        # 振幅
        if '振幅' in kline_df.columns and len(kline_df) > 0:
            amp = float(kline_df['振幅'].iloc[-1]) if pd.notna(kline_df['振幅'].iloc[-1]) else amp
        elif '最高' in kline_df.columns and '最低' in kline_df.columns:
            high = float(kline_df['最高'].iloc[-1])
            low = float(kline_df['最低'].iloc[-1])
            if low > 0:
                amp = (high - low) / low * 100
    else:
        # K线不足，用最新价估算MA；量价数据不可用标记N/A
        ma5 = ma10 = ma20 = ma60 = close
        ma5_prev = ma10_prev = ma20_prev = ma60_prev = close
        vol_today = -1; ma5_vol = -1; amp = -1

    # 涨幅
    g3 = float(row.get('涨跌幅_3d', 0) or 0)
    g5 = float(row.get('涨跌幅_5d', 0) or 0)
    g10 = float(row.get('涨跌幅_10d', 0) or 0)

    # 6日涨幅（从K线计算）
    g6 = 0
    if kline_df is not None and len(kline_df) >= 7:
        c6 = kline_df['收盘']
        g6 = (float(c6.iloc[-1]) / float(c6.iloc[-7]) - 1) * 100

    # 赛道
    sector = _classify_stock_sector(code, name, sector_data, stock_sector_map)
    sec_info = sector_data.get(sector, {}) if sector else {}

    # 龙虎榜
    lhb = lhb_data.get(code, {})

    # PE分位
    pe_val = float(row.get('市盈率-动态', 30) or 30)
    pe_pct = _estimate_pe_percentile(pe_val)

    # 换手率
    turnover = float(row.get('换手率', 3) or 3)

    # 热度估算（用RSI+涨幅综合）— N/A标记：RSI不可用时hot=-1
    rsi_raw = row.get('RSI', None)
    if rsi_raw is None or (isinstance(rsi_raw, float) and pd.isna(rsi_raw)):
        hot = -1
    else:
        rsi = float(rsi_raw or 50)
        hot = min(10, max(0, (rsi - 30) / 7 + max(0, g5) / 5))

    # MACD背离
    macd_div = _calc_macd_divergence(kline_df)

    stock_data = {
        "sector": sector,
        "3d_gain": g3, "5d_gain": g5, "10d_gain": g10, "6d_gain": g6,
        "close": close, "ma60": ma60, "ma60_prev": ma60_prev,
        "ma5": ma5, "ma5_prev": ma5_prev,
        "ma10": ma10, "ma10_prev": ma10_prev,
        "ma20": ma20, "ma20_prev": ma20_prev,
        "vol_today": vol_today, "ma5_vol": ma5_vol,
        "amplitude": amp,
        "new_high_2d": new_high_2d, "new_high_today": new_high_today,
        "inst_net_sell_2d": lhb.get('inst_sell_2d', False),
        "macd_top_divergence": macd_div,
        "sector_daily_gain": sec_info.get('daily_gain', 0),
        "sector_limit_up_count_count": sec_info.get('limit_up_count', 0),
        "sector_net_inflow": sec_info.get('net_inflow', 0),
        "inst_net_buy_3d": -1 if not lhb else lhb.get('inst_net_buy_3d', 0),
        "north_net_buy": -1 if not lhb else lhb.get('north_net_buy', 0),
        "pure_hot_money_only": lhb.get('pure_hot_money_only', True),
        "pe_hist_percent": pe_pct,
        "pe_raw": pe_val,
        "turnover_rate": turnover,
        "stock_hot_score": hot,
        "sector_fund_outflow": False,
    }

    # 填充板块资金流向判定（追高模型：板块净流出则淘汰）
    if stock_data["sector"]:
        fund_flows = _get_sector_fund_flow()
        sector_flow = fund_flows.get(stock_data["sector"], None)
        if sector_flow is not None:
            stock_data["sector_fund_outflow"] = (sector_flow <= 0)
    return stock_data


# ===================== 前置硬过滤 =====================


def hard_filter_v3(stock_data):
    """满足任意一条直接淘汰（7条硬过滤规则）。return: (True=保留, msg)
    1. 3日涨幅 > 15% → 淘汰（短期过热）
    2. 距MA60涨幅 > 80% → 淘汰（中长期乖离过大）
    3. 缩量新高顶背离 → 淘汰
    4. 机构连续2日净卖出 → 淘汰
    5. MACD高位顶背离 → 淘汰
    6. 连续6交易日累计涨幅 > 25% → 淘汰（中期过热）
    7. 所属板块资金净流出 → 淘汰（板块无主力资金支持）
    """
    if stock_data["3d_gain"] > 15:
        return False, f"3日涨幅{stock_data['3d_gain']:.1f}%>15%"
    if stock_data["ma60"] > 0 and (stock_data["close"] / stock_data["ma60"] - 1) > 0.8:
        return False, f"距MA60涨幅>{80}%"
    if stock_data["vol_today"] < stock_data["ma5_vol"] * 0.8 and stock_data["new_high_2d"]:
        return False, "缩量新高顶背离"
    if stock_data["inst_net_sell_2d"]:
        return False, "机构连续2日净卖出"
    if stock_data["macd_top_divergence"]:
        return False, "MACD高位顶背离"
    if stock_data.get("6d_gain", 0) > 25:
        return False, f"6日累计涨幅{stock_data['6d_gain']:.1f}%>25%"
    if stock_data.get("sector_fund_outflow", False):
        return False, f"板块{stock_data.get('sector', '')}资金净流出"
    return True, "过滤通过"

# ===================== 维度1：趋势结构 满分25 =====================


# ═══════════════════════════════════════════════════
#  旧接口：保持向后兼容
# ═══════════════════════════════════════════════════

def calculate_v3_total_score(stock_data, weights=None):
    """v4十维打分主函数（P0资金信号分层 + P1百分位归一化）。

    旧版 dict-based 接口。新代码请使用 ChaseHighScorer。
    """
    scorer = ChaseHighScorer()
    si = ScoreInput(stock_data=stock_data, weights=weights or DEFAULT_WEIGHTS)
    result = scorer.score(score_input=si)

    if weights is None:
        weights = DEFAULT_WEIGHTS

    ret = {
        "pass": result.passed, "filter_msg": result.filter_msg,
        "综合评分": int(result.score),
        "趋势结构": int(result.dimensions.get("趋势结构", 0)),
        "动量强度": int(result.dimensions.get("动量强度", 0)),
        "板块共振": int(result.dimensions.get("板块共振", 0)),
        "北向资金": int(result.dimensions.get("北向资金", 0)),
        "机构净买": int(result.dimensions.get("机构净买", 0)),
        "板块资金热度": int(result.dimensions.get("板块资金热度", 0)),
        "量价配合": int(result.dimensions.get("量价配合", 0)),
        "估值安全": int(result.dimensions.get("估值安全", 0)),
        "筹码稳定": int(result.dimensions.get("筹码稳定", 0)),
        "情绪热度": int(result.dimensions.get("情绪热度", 0)),
        "position_msg": result.position_msg,
        "_raw": result.raw,
    }
    return ret


def calculate_five_dimensions_score(row, rsi_dict=None, weight_config=None):
    """兼容旧接口"""
    return calculate_v3_total_score(row) if isinstance(row, dict) and "close" in row else {
        "趋势结构": 50, "动量强度": 50, "板块共振": 50,
        "北向资金": 50, "机构净买": 50, "板块资金热度": 50,
        "量价配合": 50, "估值安全": 50, "筹码稳定": 50, "情绪热度": 50,
        "综合评分": 50, "pass": True, "filter_msg": "", "position_msg": ""}


# ═══════════════════════════════════════════════════
#  ChaseHighScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

@register_scorer
class ChaseHighScorer(BaseScorer):
    """追高模型：十维评分（趋势/动量/板块共振/北向/机构/资金热度/量价/估值/筹码/情绪）"""

    model_name = "chase_high"

    def compute(self, si: ScoreInput) -> ScoreResult:
        sd = si.stock_data
        weights = si.weights or DEFAULT_WEIGHTS

        # 前置硬过滤
        pass_filter, filter_msg = hard_filter_v3(sd)
        if not pass_filter:
            return ScoreResult(
                score=0, passed=False, filter_msg=filter_msg,
                position_msg="前置淘汰",
                dimensions={k: 0 for k in DIM_NAMES},
                raw={k: 0 for k in RAW_KEYS},
            )

        # 十维打分
        s1 = score_trend_struct_v3(sd)
        s2 = score_momentum_v3(sd)
        s3 = score_sector_resonance_v3(sd)
        s4 = score_north_capital_v3(sd)
        s5 = score_inst_capital_v3(sd)
        s6 = score_sector_fund_heat_v3(sd)
        s7 = score_volume_price_v3(sd)
        s8 = score_valuation_v3(sd)
        s9 = score_chip_v3(sd)
        s10 = score_sentiment_v3(sd)

        def _safe(v):
            return 0 if v < 0 else v

        n1 = _safe(s1) / 25 * 100; n2 = _safe(s2) / 22 * 100
        n3 = _safe(s3) / 10 * 100; n4 = _safe(s4) / 10 * 100
        n5 = _safe(s5) / 10 * 100; n6 = _safe(s6) / 10 * 100
        n7 = _safe(s7) / 12 * 100; n8 = _safe(s8) / 10 * 100
        n9 = _safe(s9) / 7 * 100; n10 = _safe(s10) / 4 * 100

        total = int(
            n1 * weights.get("趋势结构", 15) / 100 +
            n2 * weights.get("动量强度", 18) / 100 +
            n3 * weights.get("板块共振", 8) / 100 +
            n4 * weights.get("北向资金", 15) / 100 +
            n5 * weights.get("机构净买", 10) / 100 +
            n6 * weights.get("板块资金热度", 5) / 100 +
            n7 * weights.get("量价配合", 14) / 100 +
            n8 * weights.get("估值安全", 3) / 100 +
            n9 * weights.get("筹码稳定", 6) / 100 +
            n10 * weights.get("情绪热度", 6) / 100
        )

        if total >= 85:
            pos_msg = "主线龙头，重仓60%~80%"
        elif total >= 70:
            pos_msg = "支线趋势，轻仓20%~40%"
        else:
            pos_msg = "分数不足70，放弃不参与"

        return ScoreResult(
            score=total, passed=True, filter_msg=filter_msg,
            position_msg=pos_msg,
            dimensions={
                "趋势结构": int(n1), "动量强度": int(n2), "板块共振": int(n3),
                "北向资金": int(n4), "机构净买": int(n5), "板块资金热度": int(n6),
                "量价配合": int(n7), "估值安全": int(n8), "筹码稳定": int(n9),
                "情绪热度": int(n10),
            },
            raw={"s1": s1, "s2": s2, "s3": s3, "s4": s4, "s5": s5,
                 "s6": s6, "s7": s7, "s8": s8, "s9": s9, "s10": s10},
        )


def _classify_signal(score, chg5, rsi, safety, mom):
    """信号分类（从 stock_screener_backup 恢复，供 get_simulated_stock_pool 和 app/renderers 使用）"""
    if score >= 70 and mom >= 65 and safety >= 55 and 30 <= rsi <= 70:
        return "强势买入", "badge-strong", "积极关注"
    if (score >= 55 and score < 70) or (rsi < 35 and score >= 45) or (safety >= 60 and mom >= 50):
        return "逢低吸纳", "badge-attention", "分批布局"
    if score < 40 or safety < 35 or rsi > 80:
        return "建议回避", "badge-watch", "谨慎对待"
    return "观望等待", "badge-hold", "等待信号"


DIM_NAMES = ["趋势结构", "动量强度", "板块共振", "北向资金", "机构净买",
             "板块资金热度", "量价配合", "估值安全", "筹码稳定", "情绪热度"]
RAW_KEYS = ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10"]
