"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from data.financial import get_financial_data
from data.sector import _classify_stock_sector
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer

def calculate_dilemma_reversal_score(code, kline_df, stock_pool_context=None):
    """
    困境反转模型（抓周期股）四层简化版评分（Layer 4 完整实现，Layers 1-3 占位）。
    
    维度（满分100）：
    - L1_拐点（25分）：ROE环比.>1.0→6+NPR>1.20→7+NPR-1>0.70→4+NPR-2>0→3+RevR>1.0→5
    - L2_反转（15分）：毛利率恢复率>0.90→7+经营现金流恢复率>0.90→8
    - L3_安全垫（20分）：PB<2.0→8+负债率<70%→7+商誉/净资产<20%→5
    - L4_技术资金（40分）：
      * 突破均线（10分）：>MA250→10，否则0
      * MACD信号（10分）：标准金叉→10，DIF加速转正→5
      * 主力放量（10分）：5日均量≥60日均量1.2倍→10，否则0
      * 低位启动（10分）：250日位置≤50%→10，否则0
    
    kline_df: 含 'close'/'收盘', 'open'/'开盘', 'high'/'最高', 'low'/'最低', 'volume'/'成交量' 等列
    """
    close_col = '收盘' if '收盘' in kline_df.columns else 'close'
    open_col = '开盘' if '开盘' in kline_df.columns else 'open'
    high_col = '最高' if '最高' in kline_df.columns else 'high'
    low_col = '最低' if '最低' in kline_df.columns else 'low'
    volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'
    
    closes = kline_df[close_col].values.astype(float)
    opens = kline_df[open_col].values.astype(float)
    highs = kline_df[high_col].values.astype(float)
    lows = kline_df[low_col].values.astype(float)
    volumes = kline_df[volume_col].values.astype(float)
    n = len(closes)
    
    if n < 60:
        return {"pass": False, "综合评分": 0,
                "L1_拐点": 0, "L2_反转": 0, "L3_安全垫": 0, "L4_技术资金": 0}
    
    # --- L1_拐点（25分）：财务恢复率（优先）→ 技术面近似（fallback） ---
    l1_score = 0
    fin_dr = stock_pool_context.get('fin') if stock_pool_context else None
    fin_ok = bool(fin_dr and fin_dr.get('success'))
    # 🔧 财务数据空值检测：API返回success=True但关键字段全为0/None → 视为无效，回退技术面
    if fin_ok:
        _fin_key_fields = ['roe_ttm', 'roe_recovery_q', 'np_recovery_q', 'np_recovery_q_1',
                           'np_recovery_q_2', 'rev_recovery_q', 'gm_recovery_q', 'ocf_recovery_q',
                           'pb', 'debt_ratio', 'goodwill_ratio']
        fin_ok = any(fin_dr.get(f) for f in _fin_key_fields if fin_dr.get(f) is not None)
    if fin_ok:
        # roe_ttm > 0 且 ROE环比恢复率 > 1.0（环比改善）
        if fin_dr.get('roe_ttm', 0) > 0 and fin_dr.get('roe_recovery_q', 0) > 1.0:
            l1_score += 6
        # 净利润恢复率 T/ABS(T-4) > 1.20
        if fin_dr.get('np_recovery_q', 0) > 1.20:
            l1_score += 7
        # T-1期 净利润恢复率 > 0.70
        if fin_dr.get('np_recovery_q_1', 0) > 0.70:
            l1_score += 4
        # T-2期 净利润 > 0（不亏损）
        if fin_dr.get('np_recovery_q_2', 0) > 0:
            l1_score += 3
        # 营收恢复率 > 1.0
        if fin_dr.get('rev_recovery_q', 0) > 1.0:
            l1_score += 5
    else:
        # 🔧 P0修复: 技术面fallback收紧，满分上限18（财务路径满分25，体现"无财务数据的惩罚"）
        # 原 fallback 为 10+8+7=25 过于宽松 → 回调深度分档 + 负面过滤
        l1_fallback_max = 18  # fallback满分上限

        # --- A. 回调深度分档（0~9分） ---
        if n >= 60:
            high_60 = float(np.max(highs[-60:]))
            if high_60 > 0:
                drawdown_pct = (high_60 - closes[-1]) / high_60 * 100
                # 深度回调 > 50% → 拐点概率最高
                if drawdown_pct >= 50:
                    l1_score += 9
                elif drawdown_pct >= 40:
                    l1_score += 7
                elif drawdown_pct >= 30:
                    l1_score += 5
                elif drawdown_pct >= 20:
                    l1_score += 3
                else:
                    l1_score += 1  # 浅回调，拐点确认不充分

        # --- B. 均线止跌分档（0~6分） ---
        if n >= 20:
            low_20 = float(np.min(lows[-20:]))
            low_20_pos = int(np.argmin(lows[-20:]))
            days_since_low = 19 - low_20_pos
            # 走平天数越多，止跌越确定
            if days_since_low >= 7:
                l1_score += 6   # 底部已确立超过一周
            elif days_since_low >= 4:
                l1_score += 4   # 底部确立4天以上
            elif days_since_low >= 2:
                l1_score += 2   # 底部确立但时间短

        # --- C. 量能确认（0~3分） ---
        if n >= 20:
            vol_ma5 = np.mean(volumes[-5:])
            vol_ma20 = np.mean(volumes[-20:])
            if vol_ma20 > 0:
                vol_ratio = vol_ma5 / vol_ma20
                if vol_ratio > 1.3:
                    l1_score += 3   # 放量转折
                elif vol_ratio > 1.0:
                    l1_score += 2   # 温和放量
                elif vol_ratio > 0.8:
                    l1_score += 1   # 量能平稳

        # --- D. 负面过滤（扣分项） ---
        # 近期仍有跌停 → 扣3分
        for i in range(max(-5, -n), 0):
            if lows[i] > 0 and (closes[i] - opens[i]) / lows[i] < -0.095:
                l1_score -= 3
                break
        # 近5日单日跌幅>7% → 扣2分
        for i in range(max(-5, -n), -1):
            if closes[i] > 0:
                daily_chg = (closes[i+1] - closes[i]) / closes[i] * 100
                if daily_chg < -7:
                    l1_score -= 2
                    break

        # 上限封顶
        l1_score = max(0, min(l1_score, l1_fallback_max))

    # --- L2_反转（15分）：毛利率+经营现金流（优先）→ 技术面近似（fallback） ---
    l2_score = 0
    if fin_ok:
        if fin_dr.get('gm_recovery_q', 0) > 0.90:
            l2_score += 7
        if fin_dr.get('ocf_recovery_q', 0) > 0.90:
            l2_score += 8
    else:
        # 技术面近似：MACD信号(8) + 量价配合(7)
        if n >= 35:
            ema12_d = pd.Series(closes[-60:]).ewm(span=12, adjust=False).mean().values
            ema26_d = pd.Series(closes[-60:]).ewm(span=26, adjust=False).mean().values
            dif_d = ema12_d - ema26_d
            if len(dif_d) >= 3:
                if dif_d[-2] <= 0 and dif_d[-1] > 0:
                    l2_score += 8  # MACD金叉
                elif dif_d[-1] > dif_d[-2] > dif_d[-3] and dif_d[-1] > -0.02 * closes[-1]:
                    l2_score += 4  # DIFF连续递增且接近零轴
        if n >= 4:
            up_vol_days = 0
            for i in range(-3, 0):
                if closes[i] > closes[i - 1] and volumes[i] > volumes[i - 1]:
                    up_vol_days += 1
            if up_vol_days >= 2:
                l2_score += 7  # 近3日有2日放量上涨
            elif up_vol_days >= 1:
                l2_score += 3

    # --- L3_安全垫（20分）：PB/负债率/商誉（优先）→ 技术面近似（fallback） ---
    l3_score = 0
    if fin_ok:
        if fin_dr.get('pb', 999) < 2.0:
            l3_score += 8
        if fin_dr.get('debt_ratio', 999) < 0.70:
            l3_score += 7
        if fin_dr.get('goodwill_ratio', 999) < 0.20:
            l3_score += 5
    else:
        # 技术面近似：250日位置低(10) + 回撤充分(10)
        if n >= 60:
            n250 = min(250, n)
            low_250 = float(np.min(lows[-n250:]))
            high_250 = float(np.max(highs[-n250:]))
            if high_250 > low_250:
                pos_pct = (closes[-1] - low_250) / (high_250 - low_250) * 100
                if pos_pct <= 25:
                    l3_score += 10
                elif pos_pct <= 40:
                    l3_score += 7
                elif pos_pct <= 60:
                    l3_score += 4
            n60 = min(60, n)
            high_60 = float(np.max(highs[-n60:]))
            if high_60 > 0:
                drawdown_60 = (closes[-1] / high_60 - 1.0) * 100
                if drawdown_60 <= -30:
                    l3_score += 10
                elif drawdown_60 <= -20:
                    l3_score += 7
                elif drawdown_60 <= -15:
                    l3_score += 4
    
    # --- L4_技术资金（40分）---
    l4_score = 0
    
    # 1) 突破250日线 (10分)
    if n >= 250:
        ma250 = np.mean(closes[-250:])
        if closes[-1] > ma250:
            l4_score += 10
    
    # 2) 周线MACD金叉 (10分) — 用近5根日线模拟周线趋势
    if n >= 30:
        weekly_closes = closes[-25:]
        w_close = []
        for i in range(0, len(weekly_closes), 5):
            seg = weekly_closes[i:i+5]
            w_close.append(seg[-1])
        if len(w_close) >= 9:
            ema12 = pd.Series(w_close).ewm(span=12, adjust=False).mean().values
            ema26 = pd.Series(w_close).ewm(span=26, adjust=False).mean().values
            dif = ema12 - ema26
            if len(dif) >= 3 and dif[-2] <= 0 and dif[-1] > 0:
                l4_score += 10
            elif len(dif) >= 2 and dif[-2] <= 0 and dif[-1] < dif[-2] * -1:
                # DIF 从负转正加速
                l4_score += 5
    
    # 3) 主力放量：5日均量 vs 60日均量 (10分)
    if n >= 60:
        vol_ma5 = np.mean(volumes[-5:])
        vol_ma60 = np.mean(volumes[-60:])
        if vol_ma60 > 0:
            vol_ratio = vol_ma5 / vol_ma60
            if vol_ratio >= 1.2:
                l4_score += 10
    
    # 4) 低位启动：股价在250日位置 (10分)
    if n >= 250:
        low_250 = np.min(lows[-250:])
        high_250 = np.max(highs[-250:])
        if high_250 > low_250:
            position_pct = (closes[-1] - low_250) / (high_250 - low_250) * 100
            if position_pct <= 50:
                l4_score += 10
    
    total = l1_score + l2_score + l3_score + l4_score
    
    return {
        "pass": True,
        "综合评分": total,
        "L1_拐点": l1_score,
        "L2_反转": l2_score,
        "L3_安全垫": l3_score,
        "L4_技术资金": l4_score,
    }


# ═══════════════════════════════════════════════════
#  DilemmaScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

DILEMMA_DIM_NAMES = ["L1_拐点", "L2_反转", "L3_安全垫", "L4_技术资金"]
DILEMMA_RAW_KEYS = ["l1", "l2", "l3", "l4"]


@register_scorer
class DilemmaScorer(BaseScorer):
    """困境反转模型：四层评分（L1_拐点/L2_反转/L3_安全垫/L4_技术资金）"""

    model_name = "dilemma"

    def compute(self, si: ScoreInput) -> ScoreResult:
        code = si.code
        kline_df = si.kline_df
        ctx = si.stock_pool_context

        if kline_df is None or len(kline_df) < 60:
            return ScoreResult(
                score=0, passed=False, filter_msg="K线不足60日",
                dimensions={k: 0 for k in DILEMMA_DIM_NAMES},
                raw={k: 0 for k in DILEMMA_RAW_KEYS},
            )

        close_col = '收盘' if '收盘' in kline_df.columns else 'close'
        open_col = '开盘' if '开盘' in kline_df.columns else 'open'
        high_col = '最高' if '最高' in kline_df.columns else 'high'
        low_col = '最低' if '最低' in kline_df.columns else 'low'
        volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'

        closes = kline_df[close_col].values.astype(float)
        opens = kline_df[open_col].values.astype(float)
        highs = kline_df[high_col].values.astype(float)
        lows = kline_df[low_col].values.astype(float)
        volumes = kline_df[volume_col].values.astype(float)
        n = len(closes)

        fin_dr = ctx.get('fin') if ctx else None
        fin_ok = bool(fin_dr and fin_dr.get('success'))
        if fin_ok:
            _keys = ['roe_ttm', 'roe_recovery_q', 'np_recovery_q', 'np_recovery_q_1',
                     'np_recovery_q_2', 'rev_recovery_q', 'gm_recovery_q', 'ocf_recovery_q',
                     'pb', 'debt_ratio', 'goodwill_ratio']
            fin_ok = any(fin_dr.get(f) for f in _keys if fin_dr.get(f) is not None)

        # L1_拐点
        l1_score = 0
        if fin_ok:
            if fin_dr.get('roe_ttm', 0) > 0 and fin_dr.get('roe_recovery_q', 0) > 1.0: l1_score += 6
            if fin_dr.get('np_recovery_q', 0) > 1.20: l1_score += 7
            if fin_dr.get('np_recovery_q_1', 0) > 0.70: l1_score += 4
            if fin_dr.get('np_recovery_q_2', 0) > 0: l1_score += 3
            if fin_dr.get('rev_recovery_q', 0) > 1.0: l1_score += 5
        else:
            _l1_max = 18
            if n >= 60:
                high_60 = float(np.max(highs[-60:]))
                if high_60 > 0:
                    dd = (high_60 - closes[-1]) / high_60 * 100
                    if dd >= 50: l1_score += 9
                    elif dd >= 40: l1_score += 7
                    elif dd >= 30: l1_score += 5
                    elif dd >= 20: l1_score += 3
                    else: l1_score += 1
            if n >= 20:
                low_20_pos = int(np.argmin(lows[-20:]))
                days_since = 19 - low_20_pos
                if days_since >= 7: l1_score += 6
                elif days_since >= 4: l1_score += 4
                elif days_since >= 2: l1_score += 2
            if n >= 20:
                vol_ma5 = np.mean(volumes[-5:])
                vol_ma20 = np.mean(volumes[-20:])
                if vol_ma20 > 0:
                    vr = vol_ma5 / vol_ma20
                    if vr > 1.3: l1_score += 3
                    elif vr > 1.0: l1_score += 2
                    elif vr > 0.8: l1_score += 1
            for i in range(max(-5, -n), 0):
                if lows[i] > 0 and (closes[i] - opens[i]) / lows[i] < -0.095: l1_score -= 3; break
            for i in range(max(-5, -n), -1):
                if closes[i] > 0:
                    if (closes[i + 1] - closes[i]) / closes[i] * 100 < -7: l1_score -= 2; break
            l1_score = max(0, min(l1_score, _l1_max))

        # L2_反转
        l2_score = 0
        if fin_ok:
            if fin_dr.get('gm_recovery_q', 0) > 0.90: l2_score += 7
            if fin_dr.get('ocf_recovery_q', 0) > 0.90: l2_score += 8
        else:
            if n >= 35:
                ema12_d = pd.Series(closes[-60:]).ewm(span=12, adjust=False).mean().values
                ema26_d = pd.Series(closes[-60:]).ewm(span=26, adjust=False).mean().values
                dif_d = ema12_d - ema26_d
                if len(dif_d) >= 3:
                    if dif_d[-2] <= 0 and dif_d[-1] > 0: l2_score += 8
                    elif dif_d[-1] > dif_d[-2] > dif_d[-3] and dif_d[-1] > -0.02 * closes[-1]: l2_score += 4
            if n >= 4:
                up_days = sum(1 for i in range(-3, 0) if closes[i] > closes[i - 1] and volumes[i] > volumes[i - 1])
                if up_days >= 2: l2_score += 7
                elif up_days >= 1: l2_score += 3

        # L3_安全垫
        l3_score = 0
        if fin_ok:
            if fin_dr.get('pb', 999) < 2.0: l3_score += 8
            if fin_dr.get('debt_ratio', 999) < 0.70: l3_score += 7
            if fin_dr.get('goodwill_ratio', 999) < 0.20: l3_score += 5
        else:
            if n >= 60:
                n250 = min(250, n)
                low_250 = float(np.min(lows[-n250:]))
                high_250 = float(np.max(highs[-n250:]))
                if high_250 > low_250:
                    pp = (closes[-1] - low_250) / (high_250 - low_250) * 100
                    if pp <= 25: l3_score += 10
                    elif pp <= 40: l3_score += 7
                    elif pp <= 60: l3_score += 4
                high_60 = float(np.max(highs[-60:]))
                if high_60 > 0:
                    dd60 = (closes[-1] / high_60 - 1) * 100
                    if dd60 <= -30: l3_score += 10
                    elif dd60 <= -20: l3_score += 7
                    elif dd60 <= -15: l3_score += 4

        # L4_技术资金
        l4_score = 0
        if n >= 250:
            ma250 = np.mean(closes[-250:])
            if closes[-1] > ma250: l4_score += 10
        if n >= 30:
            wc = [closes[-25:][i:i+5][-1] for i in range(0, 25, 5)]
            if len(wc) >= 9:
                ema12 = pd.Series(wc).ewm(span=12, adjust=False).mean().values
                ema26 = pd.Series(wc).ewm(span=26, adjust=False).mean().values
                dif = ema12 - ema26
                if len(dif) >= 3 and dif[-2] <= 0 and dif[-1] > 0: l4_score += 10
                elif len(dif) >= 2 and dif[-2] <= 0 and dif[-1] < dif[-2] * -1: l4_score += 5
        if n >= 60:
            v5 = np.mean(volumes[-5:])
            v60 = np.mean(volumes[-60:])
            if v60 > 0 and v5 / v60 >= 1.2: l4_score += 10
        if n >= 250:
            low_250 = np.min(lows[-250:])
            high_250 = np.max(highs[-250:])
            if high_250 > low_250:
                pp = (closes[-1] - low_250) / (high_250 - low_250) * 100
                if pp <= 50: l4_score += 10

        total = l1_score + l2_score + l3_score + l4_score

        return ScoreResult(
            score=total, passed=True,
            dimensions={
                "L1_拐点": l1_score, "L2_反转": l2_score,
                "L3_安全垫": l3_score, "L4_技术资金": l4_score,
            },
            raw={"l1": l1_score, "l2": l2_score, "l3": l3_score, "l4": l4_score},
        )
