"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from core.config import DEFAULT_GC_PARAMS, DEFAULT_GC_WEIGHTS, _VERBOSE
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer
from data.dde import _get_dde_or_fallback
from data.sector import _get_cached_sector_data, _classify_stock_sector

def _get_gc_params():
    return dict(DEFAULT_GC_PARAMS)

def _compute_macd(closes, fast=12, slow=26, sig=9):
    """返回 (DIF, DEA, MACD柱) 数组，长度与输入一致"""
    if len(closes) < slow + sig:
        return np.full(len(closes), np.nan), np.full(len(closes), np.nan), np.full(len(closes), np.nan)
    ema_fast = pd.Series(closes).ewm(span=fast, adjust=False).mean()
    ema_slow = pd.Series(closes).ewm(span=slow, adjust=False).mean()
    dif = (ema_fast - ema_slow).values
    dea = pd.Series(dif).ewm(span=sig, adjust=False).mean().values
    macd_hist = 2 * (dif - dea)
    return dif, dea, macd_hist

def _get_hot_sector_names_set():
    """返回当前热门板块名称集合，用于板块反向惩罚"""
    import subprocess, json
    helper = os.path.join(os.path.dirname(__file__), "temp", "fetch_hot_sectors.ps1")
    if not os.path.exists(helper):
        return set()
    try:
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", helper, "-N", "6"],
            capture_output=True, text=True, timeout=60
        )
        data = json.loads(result.stdout)
        return {s['name'] for s in data.get('sectors', [])}
    except Exception:
        return set()

def _gc_score_decline(kline_df):
    """回撤越深、急跌形态越明显，分数越高"""
    closes = kline_df['收盘'].values.astype(float)
    n = len(closes)
    half = min(60, n)
    recent = closes[-half:]
    peak_idx = int(np.argmax(recent))
    peak_val = recent[peak_idx]
    current = closes[-1]
    decline_pct = (peak_val - current) / peak_val * 100

    # 基础分：回撤深度（线性映射：30%→12分，50%→28分）
    base = min(28, max(5, (decline_pct - 25) * 0.8 + 8))

    # 急跌加分：检查从高点以来是否有连续大阴线
    post_peak = recent[peak_idx:]
    big_drops = 0
    for i in range(1, len(post_peak)):
        day_chg = (post_peak[i] - post_peak[i-1]) / post_peak[i-1] * 100
        if day_chg < -5:
            big_drops += 1
    crash_bonus = min(2, big_drops * 0.5)

    return min(30, base + crash_bonus)

def _gc_score_steady(kline_df):
    """不再创新低 + 底部K线形态"""
    closes = kline_df['收盘'].values.astype(float)
    opens = kline_df['开盘'].values.astype(float) if '开盘' in kline_df.columns else closes
    highs = kline_df['最高'].values.astype(float) if '最高' in kline_df.columns else closes
    lows = kline_df['最低'].values.astype(float) if '最低' in kline_df.columns else closes
    n = len(closes)

    half = min(60, n)
    recent_lows = lows[-half:]
    stage_low = recent_lows.min()

    # 不创新低天数
    steady_days = 0
    for i in range(n - 1, max(0, n - 10) - 1, -1):
        if lows[i] > stage_low * 1.005:
            steady_days += 1
        else:
            break
    steady_score = min(14, steady_days * 3.5)

    # 底部K线形态：最近3天
    kline_bonus = 0
    for i in range(max(0, n-3), n):
        body = abs(closes[i] - opens[i])
        lower_shadow = min(opens[i], closes[i]) - lows[i]
        upper_shadow = highs[i] - max(opens[i], closes[i])
        total_range = highs[i] - lows[i] if highs[i] > lows[i] else 1
        # 长下影线
        if lower_shadow > body * 1.5 and lower_shadow > total_range * 0.4:
            kline_bonus += 2
        # 小阳线
        if closes[i] > opens[i] and body < total_range * 0.3:
            kline_bonus += 1
        # 十字星
        if body < total_range * 0.15:
            kline_bonus += 1

    # 当日收阳线 + 站上MA5/MA10
    if closes[-1] > opens[-1]:
        kline_bonus += 2
    if n >= 10:
        ma5 = pd.Series(closes).rolling(5).mean().values[-1]
        ma10 = pd.Series(closes).rolling(10).mean().values[-1]
        if closes[-1] > ma5 and closes[-1] > ma10:
            kline_bonus += 2

    return min(20, steady_score + min(6, kline_bonus))

def _gc_score_ma(kline_df):
    """5日线走平/拐头 + 收盘站上5日线 + MA20/MA60长期趋势方向"""
    closes = kline_df['收盘'].values.astype(float)
    n = len(closes)
    if n < 7:
        return 0

    ma5 = pd.Series(closes).rolling(5).mean().values
    cur_ma5 = ma5[-1] if not np.isnan(ma5[-1]) else 0
    prev_ma5 = ma5[-3] if n >= 8 and not np.isnan(ma5[-3]) else cur_ma5

    score = 0
    # 5日线斜率
    slope = (ma5[-1] - ma5[-3]) / ma5[-3] * 100 if ma5[-3] > 0 and not np.isnan(ma5[-3]) else -99
    if slope > 0.5:
        score += 8
    elif slope > -0.3:
        score += 5
    elif slope > -1.0:
        score += 2

    # 收盘站上5日线
    if closes[-1] > cur_ma5 and cur_ma5 > 0:
        score += 6
    elif closes[-1] > cur_ma5 * 0.98:
        score += 3

    # MA20方向
    if n >= 25:
        ma20 = pd.Series(closes).rolling(20).mean().values
        if not np.isnan(ma20[-1]) and not np.isnan(ma20[-6]):
            ma20_slope = (ma20[-1] - ma20[-6]) / ma20[-6] * 100 if ma20[-6] > 0 else 0
            if ma20_slope > 0.3:
                score += 4
            elif ma20_slope > 0:
                score += 2
            elif ma20_slope < -1.0:
                score -= 2  # 20日线明显向下，扣分

    # MA60方向
    if n >= 65:
        ma60 = pd.Series(closes).rolling(60).mean().values
        if not np.isnan(ma60[-1]) and not np.isnan(ma60[-11]):
            ma60_slope = (ma60[-1] - ma60[-11]) / ma60[-11] * 100 if ma60[-11] > 0 else 0
            if ma60_slope > 0.5:
                score += 2
            elif ma60_slope < -1.0:
                score -= 3  # 60日线明显向下，下跌通道扣分

    return max(0, min(20, score))

def _gc_score_volume(kline_df):
    """企稳日量能 vs 5日均量，低于volume_ratio阈值直接0分"""
    volumes = kline_df['成交量'].values.astype(float)
    n = len(volumes)
    if n < 6:
        return 0
    ma5_vol = np.mean(volumes[-6:-1])
    today_vol = volumes[-1]
    if ma5_vol <= 0:
        return 0
    ratio = today_vol / ma5_vol

    params = _get_gc_params()
    min_ratio = params.get("volume_ratio", 1.0)
    if ratio < min_ratio:
        return 0

    # 下跌缩量检查（前5天均值 vs 更早5天）
    early_vol = np.mean(volumes[max(0,n-20):max(0,n-10)]) if n >= 20 else ma5_vol
    shrink_bonus = 2 if early_vol > 0 and ma5_vol < early_vol * 0.7 else 0

    # 放量评分
    if ratio >= 2.0:
        return min(15, 12 + shrink_bonus)
    elif ratio >= 1.5:
        return min(15, 9 + shrink_bonus)
    elif ratio >= min_ratio:
        return min(15, 6 + shrink_bonus)
    return 0

def _gc_score_macd(kline_df):
    """DIFF走平、绿柱缩短、金叉"""
    closes = kline_df['收盘'].values.astype(float)
    dif, dea, hist = _compute_macd(closes)
    if np.isnan(dif[-1]):
        return 0
    n = len(dif)

    score = 0
    # DIFF走平（不再持续向下）
    dif_slope = dif[-1] - dif[-3] if n >= 3 and not np.isnan(dif[-3]) else -99
    if dif_slope > 0.02:
        score += 5
    elif dif_slope > -0.01:
        score += 3

    # 绿柱缩短
    if n >= 3 and not np.isnan(hist[-1]) and not np.isnan(hist[-3]):
        if hist[-1] < 0 and hist[-1] > hist[-3]:
            score += 5

    # MACD金叉（DIFF上穿DEA）
    if n >= 2 and not np.isnan(dif[-2]) and not np.isnan(dea[-2]):
        if dif[-2] <= dea[-2] and dif[-1] > dea[-1]:
            score += 5
        elif dif[-1] > dea[-1] and dif[-3] <= dea[-3]:
            score += 3

    return min(15, score)

def _gc_score_fund_confirm(stock_data, kline_df):
    """
    资金确认维度：
    - 优先：近3日主力净流入方向（正流入且占比>0 则得分）
    - 替代：MACD金叉当日成交量 / 5日均量（无法获取主力资金时）
    """
    inst_net = stock_data.get("inst_net_buy_3d", 0)
    north_net = stock_data.get("north_net_buy", 0)
    main_net = inst_net + north_net

    if main_net != 0:
        if main_net > 0:
            return 10
        else:
            return 0
    else:
        if kline_df is None or len(kline_df) < 6:
            return 5
        volumes = kline_df['成交量'].values.astype(float)
        if len(volumes) < 6:
            return 5
        ma5_vol = np.mean(volumes[-6:-1]) if len(volumes) >= 6 else volumes[-1]
        today_vol = volumes[-1]
        if ma5_vol <= 0:
            return 5
        ratio = today_vol / ma5_vol
        if ratio >= 1.5:
            return 10
        elif ratio >= 1.2:
            return 7
        elif ratio >= 1.0:
            return 5
        else:
            return 2

def _gc_score_sector(stock_data):
    """
    板块确认维度：
    - 无概念板块映射 → -5
    - 有映射但不在当前热门板块中 → -3
    - 在热门板块中 → 0
    """
    sector = stock_data.get('板块', '')
    if not sector:
        return -5
    hot = _get_hot_sector_names_set()
    if hot and sector not in hot:
        return -3
    return 0

def calculate_golden_cross_score(stock_data, kline_df, weights=None):
    """
    强势超跌金叉模型主评分函数
    P1: 所有子维度先做百分位归一化，再加权
    stock_data: 股票基本数据（来自行情DataFrame的一行）
    kline_df: 该股票的K线DataFrame
    weights: 权重 dict（含 fund_weight）
    返回 dict，包含各维度分、综合评分、信号分类等
    """
    code = stock_data.get('代码', '')
    name = stock_data.get('名称', '')

    # 硬过滤
    hf_result = _gc_hard_filter(code, kline_df)
    passed, filter_info = hf_result[0], hf_result[1]
    if not passed:
        return {
            "pass": False, "filter_msg": filter_info,
            "综合评分": 0, "下跌形态": 0, "K线止跌": 0,
            "均线拐头": 0, "量能确认": 0, "MACD反转": 0, "资金确认": 0,
            "板块确认": 0,
            "信号": "不达标", "signal_class": "badge-hold",
            "_raw": {},
        }

    # 七维原始分
    s1 = _gc_score_decline(kline_df)
    s2 = _gc_score_steady(kline_df)
    s3 = _gc_score_ma(kline_df)
    s4 = _gc_score_volume(kline_df)
    s5 = _gc_score_macd(kline_df)
    s6 = _gc_score_fund_confirm(stock_data, kline_df)
    s7 = _gc_score_sector(stock_data)

    if weights is None:
        weights = dict(DEFAULT_GC_WEIGHTS)

    total = int(
        s1 * weights.get("下跌形态", 28) / 30 +
        s2 * weights.get("K线止跌", 18) / 20 +
        s3 * weights.get("均线拐头", 18) / 20 +
        s4 * weights.get("量能确认", 13) / 15 +
        s5 * weights.get("MACD反转", 13) / 15 +
        s6 * weights.get("资金确认", 10) / 10 +
        s7
    )

    if s1 >= 24 and s2 >= 14 and s5 >= 10 and total >= 70:
        signal = "买点A-急跌反弹"
        sig_cls = "badge-strong"
        advice = "高弹性，10%-15%仓位"
    elif s2 >= 10 and s3 >= 12 and total >= 55:
        signal = "买点B-阴跌修复"
        sig_cls = "badge-attention"
        advice = "轻仓试错，5%-8%仓位"
    elif total >= 40:
        signal = "观察"
        sig_cls = "badge-hold"
        advice = "等信号"
    else:
        signal = "放弃"
        sig_cls = "badge-hold"
        advice = "条件不充分"

    return {
        "pass": True, "filter_msg": filter_info,
        "综合评分": total,
        "下跌形态": int(s1), "K线止跌": int(s2),
        "均线拐头": int(s3), "量能确认": int(s4),
        "MACD反转": int(s5), "资金确认": int(s6),
        "板块确认": int(s7),
        "信号": signal, "signal_class": sig_cls, "建议": advice,
        "_raw": {"s1": s1, "s2": s2, "s3": s3, "s4": s4, "s5": s5, "s6": s6, "s7": s7},
    }

def _run_golden_cross_scan(codes_tuple, params_json, weights_json):
    """
    批量扫描全市场，返回结果列表（按综合评分降序）
    P1: 两遍扫描 — 第一遍收集原始分 → 百分位归一化 → 第二遍计算最终总分
    codes_tuple: 全市场股票 (代码, 名称, 板块) 列表的元组
    """
    codes = list(codes_tuple)
    weights = json.loads(weights_json) if isinstance(weights_json, str) else weights_json
    
    # P0: 获取龙虎榜资金数据供资金确认维度使用
    lhb_data = {}
    try:
        lhb_data = _get_cached_dragon_tiger()
    except Exception:
        pass
    
    total = len(codes)
    # Progress handled by caller
    step = max(1, total // 100)
    
    # ===== 第一遍：收集所有通过硬过滤的原始分 =====
    raw_results = []  # [(code, name, sector, close, raw_scores_dict, filter_info, kline_np)]
    for i, (code, name, sector) in enumerate(codes):
        if i % step == 0:
            progress.progress(min(i / total, 1.0),
                              text=f"金叉模型扫描 {i}/{total} — {name}")
        try:
            kline_df = get_stock_kline(code, days=60)
            if kline_df is None or len(kline_df) < 30:
                continue
            lhb = lhb_data.get(code, {})
            stock_data = {
                "代码": code, "名称": name, "板块": sector,
                "inst_net_buy_3d": lhb.get("inst_net_buy_3d", 0),
                "north_net_buy": lhb.get("north_net_buy", 0),
            }
            score = calculate_golden_cross_score(stock_data, kline_df, weights=weights)
            if score["pass"]:
                _raw = score.get("_raw", {})
                raw_results.append({
                    "code": code, "name": name, "sector": sector,
                    "close": kline_df['收盘'].values[-1] if '收盘' in kline_df.columns else '',
                    "filter_msg": score.get("filter_msg", ""),
                    "signal": score["信号"],
                    "signal_class": score["signal_class"],
                    "advice": score["建议"],
                    "_s1": _raw.get("s1", 0),
                    "_s2": _raw.get("s2", 0),
                    "_s3": _raw.get("s3", 0),
                    "_s4": _raw.get("s4", 0),
                    "_s5": _raw.get("s5", 0),
                    "_s6": _raw.get("s6", 0),
                    "_s7": _raw.get("s7", 0),
                })
        except Exception:
            continue
    
    if not raw_results:
        progress.empty()
        return []
    
    # ===== P1: 百分位归一化（六个维度分别做） =====
    n = len(raw_results)
    def _pct_norm(vals, full_score):
        arr = np.array(vals, dtype=float)
        if n <= 1 or np.all(arr == arr[0]):
            return np.full_like(arr, full_score * 0.5)
        ranks = np.argsort(np.argsort(arr)) + 1
        percentiles = ranks / n
        return (percentiles * full_score).clip(0, full_score)
    
    s1_arr = _pct_norm([r["_s1"] for r in raw_results], 30)
    s2_arr = _pct_norm([r["_s2"] for r in raw_results], 20)
    s3_arr = _pct_norm([r["_s3"] for r in raw_results], 20)
    s4_arr = _pct_norm([r["_s4"] for r in raw_results], 15)
    s5_arr = _pct_norm([r["_s5"] for r in raw_results], 15)
    s6_arr = _pct_norm([r["_s6"] for r in raw_results], 10)
    
    # ===== 第二遍：计算归一化后的加权总分 =====
    results = []
    for i, r in enumerate(raw_results):
        s1n, s2n, s3n, s4n, s5n, s6n = s1_arr[i], s2_arr[i], s3_arr[i], s4_arr[i], s5_arr[i], s6_arr[i]
        w1 = weights.get("下跌形态", 28)
        w2 = weights.get("K线止跌", 18)
        w3 = weights.get("均线拐头", 18)
        w4 = weights.get("量能确认", 13)
        w5 = weights.get("MACD反转", 13)
        w6 = weights.get("资金确认", 10)
        total = int(s1n * w1 / 30 + s2n * w2 / 20 + s3n * w3 / 20 +
                    s4n * w4 / 15 + s5n * w5 / 15 + s6n * w6 / 10 + r["_s7"])
        
        if total < 30:
            continue
        
        results.append({
            "pass": True,
            "代码": r["code"], "名称": r["name"], "板块": r["sector"],
            "收盘": r["close"],
            "金叉评分": total,
            "下跌形态": int(s1_arr[i]), "K线止跌": int(s2_arr[i]),
            "均线拐头": int(s3_arr[i]), "量能确认": int(s4_arr[i]),
            "MACD反转": int(s5_arr[i]), "资金确认": int(s6_arr[i]),
            "板块确认": int(r["_s7"]),
            "信号": r["signal"], "signal_class": r["signal_class"],
            "建议": r["advice"], "filter_msg": r["filter_msg"],
        })
    
    progress.empty()
    results.sort(key=lambda x: x["金叉评分"], reverse=True)
    return results[:30]

def get_hot_concept_stocks(n=6):
    """通过 PowerShell 子进程调用东方财富 API，按资金加速比（今日/(5日/5)）取 Top N 板块的全部成分股"""
    import subprocess, json, sys
    helper = os.path.join(os.path.dirname(__file__), "temp", "fetch_hot_sectors.ps1")
    if not os.path.exists(helper):
        if _VERBOSE: print(f"[金叉模型] helper脚本不存在: {helper}")
        return set()
    try:
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", helper, "-N", str(n)],
            capture_output=True, text=True, timeout=60
        )
        data = json.loads(result.stdout)
        if "error" in data:
            if _VERBOSE: print(f"[金叉模型] 加速板块获取失败: {data['error']}")
            return set()
        codes = data.get("codes", [])
        sectors = data.get("sectors", [])
        if _VERBOSE: print(f"[金叉模型] 资金加速Top{n}板块:")
        for s in sectors:
            tag = "反转" if s.get("reversal") else f"{s.get('accel_ratio',0):.1f}x"
            if _VERBOSE: print(f"  {s['name']}({s['code']}): 今日{s['today_inflow']}亿 / 5日{s['day5_inflow']}亿 → {tag} | {s['count']}只成分股")
        if _VERBOSE: print(f"总计 {len(codes)} 只成分股")
        return set(codes)
    except Exception as e:
        if _VERBOSE: print(f"[金叉模型] 子进程调用失败: {e}")
        return set()

def get_volprice_sectors(n=6):
    """通过量价背离 x 资金加速 综合评分选板块，返回 Top N 板块的全部成分股"""
    import subprocess, json, sys
    helper = os.path.join(os.path.dirname(__file__), "temp", "fetch_volprice_sectors.ps1")
    if not os.path.exists(helper):
        print(f"[金叉模型-量价] helper脚本不存在: {helper}")
        return set()
    try:
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", helper, "-N", str(n), "-topAccel", "50"],
            capture_output=True, text=True, timeout=90
        )
        data = json.loads(result.stdout)
        if "error" in data:
            print(f"[金叉模型-量价] 获取失败: {data['error']}")
            return set()
        codes = data.get("codes", [])
        sectors = data.get("sectors", [])
        if _VERBOSE: print(f"[金叉模型-量价] 量价+资金综合Top{n}板块:")
        for s in sectors:
            tag = "反转" if s.get("reversal") else f"{s.get('accel_ratio',0):.1f}x"
            if _VERBOSE: print(f"  {s['name']}({s['code']}): 综合={s.get('composite')} 加速={tag} 量价背离={s.get('divergence')} | {s['count']}只成分股")
        if _VERBOSE: print(f"总计 {len(codes)} 只成分股")
        return set(codes)
    except Exception as e:
        print(f"[金叉模型-量价] 子进程调用失败: {e}")
        return set()


def _gc_hard_filter(code, kline_df):
    """
    入库硬条件 — 双通道：
    通道A（零下通道）：主升涨幅 + 回撤 + MACD DIFF < 0
    通道B（水上通道）：回调洗盘后 MACD 零轴上方金叉，四条件缺一不可
    返回 (通过, 信息, 通道标识: 'zero_below'/'water_above'/None)
    """
    if kline_df is None or len(kline_df) < 40:
        return False, "K线不足40日", None
    closes = kline_df['收盘'].values.astype(float)
    n = len(closes)
    params = _get_gc_params()

    half = min(60, n)
    recent = closes[-half:]
    rise_pct = (recent.max() - recent[0]) / recent[0] * 100
    peak_idx = int(np.argmax(recent))
    peak_val = recent[peak_idx]
    current = closes[-1]
    decline = (peak_val - current) / peak_val * 100
    dif, _, _ = _compute_macd(closes)

    # 通道A：零下通道
    if not np.isnan(dif[-1]) and dif[-1] < 0:
        if rise_pct < params["main_rise_pct"]:
            return False, f"主升涨幅{rise_pct:.0f}%<{params['main_rise_pct']}%", None
        if decline < params["decline_pct"]:
            return False, f"回撤{decline:.0f}%<{params['decline_pct']}%", None
        return True, f"零下 主升{rise_pct:.0f}% 回撤{decline:.0f}% DIFF={dif[-1]:.3f}", "zero_below"

    # 通道B：水上通道
    if n < 25:
        return False, "K线不足25日 不适合水上通道", None
    ma20 = pd.Series(closes).rolling(20).mean().values
    cur_ma20 = ma20[-1]
    if np.isnan(cur_ma20) or cur_ma20 <= 0:
        return False, "MA20无效", None
    if closes[-1] < cur_ma20:
        return False, "水上通道: 股价低于20日线", None
    deviation = (closes[-1] - cur_ma20) / cur_ma20 * 100
    if deviation > 25:
        return False, f"水上通道: 乖离率{deviation:.0f}%>25% 高位风险", None

    if n < 65:
        return False, "K线不足65日 无法判断60日线方向", None
    ma60 = pd.Series(closes).rolling(60).mean().values
    if np.isnan(ma60[-1]) or np.isnan(ma60[-11]):
        return False, "MA60无效", None
    ma60_slope = (ma60[-1] - ma60[-11]) / ma60[-11] * 100 if ma60[-11] > 0 else 0
    if ma60_slope <= 0:
        return False, f"水上通道: 60日线向下({ma60_slope:.2f}%) 下跌通道风险", None

    recent20 = closes[-20:]
    recent20_peak = recent20.max()
    recent20_trough = recent20.min()
    recent20_decline = (recent20_peak - recent20_trough) / recent20_peak * 100
    if recent20_decline < 10:
        return False, f"水上通道: 近20日回撤{recent20_decline:.0f}%<10% 无充分洗盘", None

    if '成交量' not in kline_df.columns:
        return False, "水上通道: 无成交量数据", None
    volumes = kline_df['成交量'].values.astype(float)
    if len(volumes) < 6:
        return False, "水上通道: 成交量数据不足", None
    ma5_vol = np.mean(volumes[-6:-1])
    if ma5_vol <= 0:
        return False, "水上通道: 5日均量无效", None
    today_vol = volumes[-1]
    vol_ratio = today_vol / ma5_vol
    if vol_ratio < 1.2:
        return False, f"水上通道: 量比{vol_ratio:.1f}<1.2 缩量不可靠", None

    return True, f"水上 乖离{deviation:.0f}% 回撤{recent20_decline:.0f}% MA60↑ 量比{vol_ratio:.1f}", "water_above"


# ═══════════════════════════════════════════════════
#  GoldenCrossScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

GC_DIM_NAMES = ["下跌形态", "K线止跌", "均线拐头", "量能确认", "MACD反转", "资金确认", "板块确认"]
GC_RAW_KEYS = ["s1", "s2", "s3", "s4", "s5", "s6", "s7"]


@register_scorer
class GoldenCrossScorer(BaseScorer):
    """强势超跌金叉模型：七维评分（下跌形态/K线止跌/均线拐头/量能确认/MACD反转/资金确认/板块确认）"""

    model_name = "golden_cross"

    def compute(self, si: ScoreInput) -> ScoreResult:
        sd = si.stock_data
        kline_df = si.kline_df
        weights = si.weights or dict(DEFAULT_GC_WEIGHTS)
        code = sd.get('代码', '')

        # 硬过滤
        hf_result = _gc_hard_filter(code, kline_df)
        passed, filter_info, channel = hf_result[0], hf_result[1], hf_result[2] if len(hf_result) > 2 else None
        if not passed:
            return ScoreResult(
                score=0, passed=False, filter_msg=filter_info,
                position_msg="过滤未通过",
                dimensions={k: 0 for k in GC_DIM_NAMES},
                raw={k: 0 for k in GC_RAW_KEYS},
            )

        # 七维原始分
        s1 = _gc_score_decline(kline_df)
        s2 = _gc_score_steady(kline_df)
        s3 = _gc_score_ma(kline_df)
        s4 = _gc_score_volume(kline_df)
        s5 = _gc_score_macd(kline_df)
        s6 = _gc_score_fund_confirm(sd, kline_df)
        s7 = _gc_score_sector(sd)

        # 百分位归一化（s1~s6 使用满分值归一化，s7 保持负值原样）
        n1 = s1 / 30 * 100
        n2 = s2 / 20 * 100
        n3 = s3 / 20 * 100
        n4 = s4 / 15 * 100
        n5 = s5 / 15 * 100
        n6 = s6 / 10 * 100

        total = int(
            n1 * weights.get("下跌形态", 28) / 100 +
            n2 * weights.get("K线止跌", 18) / 100 +
            n3 * weights.get("均线拐头", 18) / 100 +
            n4 * weights.get("量能确认", 13) / 100 +
            n5 * weights.get("MACD反转", 13) / 100 +
            n6 * weights.get("资金确认", 10) / 100 +
            s7
        )

        # 信号分类
        if s1 >= 24 and s2 >= 14 and s5 >= 10 and total >= 70:
            signal = "买点A-急跌反弹"
            sig_cls = "badge-strong"
            advice = "高弹性，10%-15%仓位"
        elif s2 >= 10 and s3 >= 12 and total >= 55:
            signal = "买点B-阴跌修复"
            sig_cls = "badge-attention"
            advice = "轻仓试错，5%-8%仓位"
        elif total >= 40:
            signal = "观察"
            sig_cls = "badge-hold"
            advice = "等信号"
        else:
            signal = "放弃"
            sig_cls = "badge-hold"
            advice = "条件不充分"

        return ScoreResult(
            score=total, passed=True, filter_msg=filter_info,
            position_msg=advice,
            signal=signal, signal_class=sig_cls, advice=advice,
            dimensions={
                "下跌形态": int(n1), "K线止跌": int(n2), "均线拐头": int(n3),
                "量能确认": int(n4), "MACD反转": int(n5), "资金确认": int(n6),
                "板块确认": int(s7),
            },
            raw={"s1": s1, "s2": s2, "s3": s3, "s4": s4, "s5": s5, "s6": s6, "s7": s7},
        )
