"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import numpy as np
from core.config import DEFAULT_LOWBUY_PARAMS, DEFAULT_LOWBUY_WEIGHTS, _industry_pe_cache
from data.sector import _get_cached_dragon_tiger, _get_cached_sector_data, _get_sector_fund_flow, _classify_stock_sector
from data.financial import get_financial_data
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer

def _get_lowbuy_params():
    """获取低吸参数，自动检测代码默认值更新并刷新 session_state。
    
    当 DEFAULT_LOWBUY_PARAMS._params_version 递增时，
    session_state 中缓存的旧参数会被自动替换为新默认值。
    """
    current_version = DEFAULT_LOWBUY_PARAMS.get("_params_version", 0)
    cached = None
    if cached is None:
        pass  # lowbuy_params stored in app layer
        return dict(DEFAULT_LOWBUY_PARAMS)
    cached_version = cached.get("_params_version", 0)
    if cached_version < current_version:
        # 代码默认值已更新，完全替换为新默认值
        pass  # lowbuy_params stored in app layer
        return dict(DEFAULT_LOWBUY_PARAMS)
    return cached

def lb_score_decline_depth(stock_data, kline_df):
    """下跌幅度越深, 得分越高"""
    closes = kline_df["收盘"].values.astype(float)
    n = len(closes)
    if n < 20:
        return 0
    high_20 = max(closes[-20:])
    low_20 = min(closes[-20:])
    current = closes[-1]
    if high_20 <= 0:
        return 0
    drop_pct = (high_20 - current) / high_20 * 100
    if drop_pct >= 20: return 30
    elif drop_pct >= 15: return 25
    elif drop_pct >= 10: return 20
    elif drop_pct >= 7: return 15
    elif drop_pct >= 5: return 10
    elif drop_pct >= 3: return 5
    return 0

def lb_score_stabilization(stock_data, kline_df):
    """下跌放缓 + 波动收窄 + 近端止跌回升 = 企稳"""
    closes = kline_df["收盘"].values.astype(float)
    n = len(closes)
    if n < 15:
        return 0
    score = 0

    # 条件A: 近5日 vs 前5日——斜率从下跌转为走平/微升
    recent = closes[-5:]
    past = closes[-10:-5]
    try:
        s1 = np.polyfit(range(len(past)), past, 1)[0]
        s2 = np.polyfit(range(len(recent)), recent, 1)[0]
        # s2 需要从下跌转为至少不跌（反转信号）
        if s2 > 0 and s1 < 0:
            score += 14  # 从跌转涨，明确反转
        elif s2 >= 0 and s1 < 0:
            score += 10  # 从跌转平
        elif s2 > s1 and s1 < 0:
            score += 6   # 跌势放缓
        elif s2 > s1:
            score += 3   # 改善但非反转
    except:
        pass

    # 条件B: 波动率收窄
    recent_std = np.std(recent) / np.mean(recent) * 100 if np.mean(recent) > 0 else 999
    past_std = np.std(past) / np.mean(past) * 100 if np.mean(past) > 0 else 999
    if recent_std < past_std * 0.7:
        score += 11
    elif recent_std < past_std * 0.9:
        score += 6
    elif recent_std < past_std:
        score += 3
    return min(score, 25)

def lb_score_volume_recovery(stock_data, kline_df):
    """成交量从低位恢复上升 - v2: 持续放量而非单日尖刺"""
    volumes = kline_df["成交量"].values.astype(float)
    n = len(volumes)
    if n < 15:
        return 0
    # 用近2日均量 vs 前7日均量做对比，捕捉持续放量
    avg_vol_2d = np.mean(volumes[-2:])
    avg_vol_prior7 = np.mean(volumes[-9:-2])
    if avg_vol_prior7 <= 0 or avg_vol_2d <= 0:
        return 0
    ratio = avg_vol_2d / avg_vol_prior7
    if ratio >= 1.8: return 20
    elif ratio >= 1.4: return 15
    elif ratio >= 1.15: return 10
    elif ratio >= 1.0: return 5
    return 0

def lb_score_ma_support(stock_data, kline_df):
    """股价接近或站上短期均线 + MA5拐头向上（底部金叉前兆）"""
    close = stock_data["close"]
    ma5 = stock_data["ma5"]
    ma10 = stock_data["ma10"]
    ma20 = stock_data["ma20"]
    score = 0

    # 价格位置分 (满分7)
    if close > ma5:
        score += 4
    elif close > ma5 * 0.98:
        score += 2
    if close > ma10:
        score += 3
    elif close > ma10 * 0.98:
        score += 1

    # MA5 拐头确认 (满分8): 从K线数据计算MA5斜率变化
    closes_all = kline_df["收盘"].values.astype(float)
    n = len(closes_all)
    if n >= 8:
        ma5_now = np.mean(closes_all[-5:])
        ma5_3d_ago = np.mean(closes_all[-8:-3])
        ma5_change = (ma5_now - ma5_3d_ago) / ma5_3d_ago * 100 if ma5_3d_ago > 0 else 0
        if ma5_change > 0.3:
            score += 8   # MA5 明确拐头向上
        elif ma5_change >= 0:
            score += 4   # 走平或微升
        elif ma5_change > -0.3:
            score += 2   # 跌势趋缓
    return min(score, 15)

def lb_score_valuation(stock_data):
    """行业相对PE打分 + 亏损拦截 + 景气修正系数。满分10。"""
    sector = stock_data.get("sector", "")
    pe_raw = float(stock_data.get("pe_raw", 0) or 0)

    # ===== 亏损拦截（优先级最高） =====
    if pe_raw <= 0:
        return 0

    stats = _industry_pe_cache.get("stats", {}) or {}
    info = stats.get(sector) if sector else None

    if info:
        median = info["median"]
        p25 = info["p25"]
        p75 = info["p75"]
        if pe_raw <= p25:
            base = 10
        elif pe_raw <= median:
            base = 8
        elif pe_raw <= p75:
            base = 5
        else:
            base = 2
    else:
        # fallback: absolute PE percentile
        pe_pct = float(stock_data.get("pe_hist_percent", 50) or 50)
        if pe_pct <= 20:
            base = 10
        elif pe_pct <= 40:
            base = 8
        elif pe_pct <= 60:
            base = 6
        elif pe_pct <= 80:
            base = 3
        else:
            base = 0

    # ===== 景气修正系数（TODO: 接入 akshare stock_yjbb_em 净利润同比/环比） =====
    coeff = _get_earnings_growth_coeff(stock_data)
    return int(base * coeff)

def lb_score_chip(stock_data, kline_df):
    """低换手+缩量=筹码锁定"""
    t = float(stock_data.get("turnover_rate", 5) or 5)
    volumes = kline_df["成交量"].values.astype(float)
    vol_ratio = volumes[-1] / np.mean(volumes[-10:]) if len(volumes) >= 10 and np.mean(volumes[-10:]) > 0 else 1
    score = 0
    if 3 <= t <= 6:
        score += 6
    elif 1 <= t < 3 or 6 < t <= 8:
        score += 3
    if vol_ratio < 0.8:
        score += 4
    elif vol_ratio < 1.1:
        score += 2
    return min(score, 10)

def lb_score_fund_flow(stock_data, kline_df):
    """
    主力资金信号：
    - 优先：近3日主力净流入 / 流通市值
    - 替代：近3日成交额均值 / 近20日成交额均值（量能活跃度）
    """
    # 尝试获取主力资金
    inst_net = stock_data.get("inst_net_buy_3d", 0)
    north_net = stock_data.get("north_net_buy", 0)
    main_net = inst_net + north_net

    if main_net != 0:
        cap = stock_data.get("float_cap", 1e9)
        ratio = abs(main_net) / max(cap, 1e7) * 100
        if main_net > 0:
            if ratio > 0.5: return 10
            elif ratio > 0.2: return 7
            elif ratio > 0.1: return 5
            else: return 3
        else:
            return 0
    else:
        # 替代：近3日成交额均值 / 近20日成交额均值
        if kline_df is None or len(kline_df) < 20:
            return 0
        try:
            amounts = kline_df["成交额"].values.astype(float) if "成交额" in kline_df.columns else kline_df["成交量"].values.astype(float)
        except:
            return 0
        if len(amounts) < 20:
            return 0
        avg_3d = np.mean(amounts[-3:])
        avg_20d = np.mean(amounts[-20:])
        if avg_20d <= 0:
            return 0
        ratio = avg_3d / avg_20d
        if ratio >= 1.8: return 10
        elif ratio >= 1.4: return 7
        elif ratio >= 1.1: return 5
        elif ratio >= 0.8: return 3
        else: return 1

def calculate_lowbuy_score(stock_data, kline_df, params=None, weights=None):
    """低吸模型专用评分函数 - 旧版 dict 接口。新代码请使用 LowBuyScorer。"""
    scorer = LowBuyScorer()
    si = ScoreInput(stock_data=stock_data, kline_df=kline_df,
                    params=params or _get_lowbuy_params(),
                    weights=weights or DEFAULT_LOWBUY_WEIGHTS)
    result = scorer.score(score_input=si)
    return {
        "pass": result.passed,
        "综合评分": int(result.score),
        "下跌幅度": int(result.dimensions.get("下跌幅度", 0)),
        "企稳信号": int(result.dimensions.get("企稳信号", 0)),
        "量能恢复": int(result.dimensions.get("量能恢复", 0)),
        "均线支撑": int(result.dimensions.get("均线支撑", 0)),
        "估值吸引": int(result.dimensions.get("估值吸引", 0)),
        "筹码沉淀": int(result.dimensions.get("筹码沉淀", 0)),
        "主力资金": int(result.dimensions.get("主力资金", 0)),
        "_raw": result.raw,
    }

def _check_low_buy_conditions(kline_df, params):
    """
    检查单只股票是否满足低吸条件
    返回 (通过, 信号强度, 信号标签, 分析摘要)
    """
    if kline_df is None or len(kline_df) < params['decline_days'] + 5:
        return False, 0, "", "", "badge-hold"
    
    closes = kline_df['收盘'].values.astype(float)
    volumes = kline_df['成交量'].values.astype(float)
    n = len(closes)
    
    decline_days = params['decline_days']
    vol_rise_days = params['vol_rise_days']
    chg_low = params['chg_low'] / 100.0
    chg_high = params['chg_high'] / 100.0
    
    # ===== 条件5：前一日涨幅在1%~5%区间 =====
    if n < 2:
        return False, 0, "", "", "badge-hold"
    yesterday_change = (closes[-1] - closes[-2]) / closes[-2]
    if not (chg_low <= yesterday_change <= chg_high):
        return False, 0, "", "", "badge-hold"
    
    # ===== 条件1：日K线逐步下移至少N天 =====
    if n < decline_days + 2:
        return False, 0, "", "", "badge-hold"
    # 取前decline_days天的收盘价（不含最近3天的反弹）
    # 即检查在反弹之前的下跌趋势
    lookback_end = max(n - 3, decline_days + 1)
    lookback_start = lookback_end - decline_days
    if lookback_start < 0:
        return False, 0, "", "", "badge-hold"
    
    past_closes = closes[lookback_start:lookback_end]
    if len(past_closes) < 3:
        return False, 0, "", "", "badge-hold"
    
    # 线性回归斜率为负 = 下跌趋势
    x_past = np.arange(len(past_closes))
    try:
        slope_past = np.polyfit(x_past, past_closes, 1)[0]
    except:
        return False, 0, "", "", "badge-hold"
    
    if slope_past >= 0:
        return False, 0, "", "", "badge-hold"  # 没有下跌趋势
    
    # 下跌幅度检查（至少跌了decline_decline%）
    total_decline_pct = (past_closes[0] - past_closes[-1]) / past_closes[0] * 100
    if total_decline_pct < 2:  # v5.2 relaxed
        return False, 0, "", "", "badge-hold"  # 跌幅太小不算低吸
    
    # ===== 条件2：下跌趋势逐步放缓并回稳 =====
    # 比较近段和远段的跌幅
    mid = len(past_closes) // 2
    if mid < 2:
        return False, 0, "", "", "badge-hold"
    
    # 前半段跌幅 vs 后半段跌幅
    first_half_decline = (past_closes[0] - past_closes[mid]) / past_closes[0] if past_closes[0] > 0 else 0
    second_half_decline = (past_closes[mid] - past_closes[-1]) / past_closes[mid] if past_closes[mid] > 0 else 0
    
    # 后半段跌幅应小于前半段（跌势放缓）
    # 或者后半段开始走平/微涨
    decline_slowing = (second_half_decline < first_half_decline * 0.8) or (second_half_decline <= 0)
    
    # 或者用波动率收窄来判断回稳
    recent_vol_std = np.std(closes[-5:]) if n >= 5 else 999
    past_vol_std = np.std(past_closes) if len(past_closes) > 3 else 0
    vol_narrowing = recent_vol_std < past_vol_std * 0.8
    
    if not (decline_slowing or vol_narrowing):
        return False, 0, "", "", "badge-hold"
    
    # ===== 条件3：出现N日及以上交易量上升趋势 =====
    if n < vol_rise_days + 1:
        return False, 0, "", "", "badge-hold"
    
    recent_volumes = volumes[-vol_rise_days:]
    vol_increasing = all(recent_volumes[i] > recent_volumes[i-1] for i in range(1, len(recent_volumes)))
    if not vol_increasing:
        return False, 0, "", "", "badge-hold"
    
    # ===== 条件4：股价缓慢上升（近3日趋势向上但幅度小） =====
    if n < 3:
        return False, 0, "", "", "badge-hold"
    recent_3 = closes[-3:]
    x_3 = np.arange(3)
    try:
        slope_3 = np.polyfit(x_3, recent_3, 1)[0]
    except:
        return False, 0, "", "", "badge-hold"
    
    if slope_3 < -0.001 * np.mean(recent_3):  # v5.2 relaxed
        return False, 0, "", "", "badge-hold"
    
    avg_price = np.mean(recent_3)
    relative_slope = slope_3 / avg_price if avg_price > 0 else 0
    if relative_slope > 0.02:  # 上升太快不算低吸
        return False, 0, "", "", "badge-hold"
    
    # ===== 全部通过，计算信号强度 =====
    # 信号强度基于：量能回升幅度、偏离均线距离、跌幅深度
    vol_increase_ratio = (volumes[-1] / volumes[-vol_rise_days-1] - 1) * 100 if volumes[-vol_rise_days-1] > 0 else 0
    
    # 偏离20日均线程度
    ma20 = np.mean(closes[-20:]) if n >= 20 else np.mean(closes)
    deviation_from_ma = (closes[-1] - ma20) / ma20 * 100 if ma20 > 0 else 0
    
    # 综合信号强度 (0-100)
    signal_strength = 50
    signal_strength += min(20, max(0, vol_increase_ratio * 3))  # 量能回升贡献
    signal_strength += min(15, max(0, abs(deviation_from_ma) * 2))  # 偏离均线贡献（越偏离底部越高）
    signal_strength += min(15, max(0, total_decline_pct))  # 跌幅深度贡献
    signal_strength = int(max(30, min(95, signal_strength)))
    
    # 信号标签
    if signal_strength >= 75:
        label = "强烈低吸"
        badge_class = "badge-lowbuy-strong"
    elif signal_strength >= 55:
        label = "适度低吸"
        badge_class = "badge-lowbuy-mild"
    else:
        label = "轻度低吸"
        badge_class = "badge-lowbuy-mild"
    
    summary = f"跌幅{total_decline_pct:.1f}% | 量能连升{vol_rise_days}日(+{vol_increase_ratio:.0f}%) | 昨日涨{yesterday_change*100:.1f}%"
    
    return True, signal_strength, label, summary, badge_class


def _get_earnings_growth_coeff(stock_data):
    """净利润景气修正系数（0~1.2），乘到估值基础分。
    TODO: 接入 akshare stock_yjbb_em(date="20260630")
    当前默认 1.0（中性，不对基础分做修正）。
    """
    return 1.0


# ═══════════════════════════════════════════════════
#  LowBuyScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

LOWBUY_DIM_NAMES = ["下跌幅度", "企稳信号", "量能恢复", "均线支撑", "估值吸引", "筹码沉淀", "主力资金"]
LOWBUY_RAW_KEYS = ["s1", "s2", "s3", "s4", "s5", "s6", "s7"]


@register_scorer
class LowBuyScorer(BaseScorer):
    """低吸模型：七维评分（下跌幅度/企稳信号/量能恢复/均线支撑/估值吸引/筹码沉淀/主力资金）"""

    model_name = "lowbuy"

    def compute(self, si: ScoreInput) -> ScoreResult:
        sd = si.stock_data
        kline_df = si.kline_df
        weights = si.weights or DEFAULT_LOWBUY_WEIGHTS
        params = si.params or {}

        # 七维原始分
        s1 = lb_score_decline_depth(sd, kline_df)      # 0~30
        s2 = lb_score_stabilization(sd, kline_df)       # 0~25
        s3 = lb_score_volume_recovery(sd, kline_df)     # 0~20
        s4 = lb_score_ma_support(sd, kline_df)          # 0~15
        s5 = lb_score_valuation(sd)                     # 0~10
        s6 = lb_score_chip(sd, kline_df)                # 0~10
        s7 = lb_score_fund_flow(sd, kline_df)           # 0~10

        # 百分位归一化
        n1 = s1 / 30 * 100
        n2 = s2 / 25 * 100
        n3 = s3 / 20 * 100
        n4 = s4 / 15 * 100
        n5 = s5 / 10 * 100
        n6 = s6 / 10 * 100
        n7 = s7 / 10 * 100

        total = int(
            n1 * weights.get("下跌幅度", 23) / 100 +
            n2 * weights.get("企稳信号", 18) / 100 +
            n3 * weights.get("量能恢复", 14) / 100 +
            n4 * weights.get("均线支撑", 14) / 100 +
            n5 * weights.get("估值吸引", 14) / 100 +
            n6 * weights.get("筹码沉淀", 9) / 100 +
            n7 * weights.get("主力资金", 8) / 100
        )

        # 7-8月二季报窗口：估值权重上浮、筹码权重下调
        current_month = datetime.now().month
        if current_month in [7, 8]:
            total = int(
                n1 * weights.get("下跌幅度", 23) / 100 +
                n2 * weights.get("企稳信号", 18) / 100 +
                n3 * weights.get("量能恢复", 14) / 100 +
                n4 * weights.get("均线支撑", 14) / 100 +
                n5 * 17 / 100 +
                n6 * 6 / 100 +
                n7 * weights.get("主力资金", 8) / 100
            )

        if total >= 75:
            pos_msg = "深度低吸，仓位30%~50%"
        elif total >= 55:
            pos_msg = "适度低吸，仓位10%~20%"
        else:
            pos_msg = "分数不足55，放弃不参与"

        return ScoreResult(
            score=total, passed=True,
            position_msg=pos_msg,
            dimensions={
                "下跌幅度": int(n1), "企稳信号": int(n2), "量能恢复": int(n3),
                "均线支撑": int(n4), "估值吸引": int(n5), "筹码沉淀": int(n6),
                "主力资金": int(n7),
            },
            raw={"s1": s1, "s2": s2, "s3": s3, "s4": s4, "s5": s5, "s6": s6, "s7": s7},
        )


def calculate_lowbuy_score_v2(stock_data, kline_df, params=None, weights=None):
    """旧版接口兼容包装 — 调用 LowBuyScorer 并转换返回值为旧 dict 格式。"""
    scorer = LowBuyScorer()
    si = ScoreInput(stock_data=stock_data, kline_df=kline_df,
                    params=params or {}, weights=weights or DEFAULT_LOWBUY_WEIGHTS)
    result = scorer.score(score_input=si)

    return {
        "pass": result.passed,
        "综合评分": int(result.score),
        "下跌幅度": int(result.dimensions.get("下跌幅度", 0)),
        "企稳信号": int(result.dimensions.get("企稳信号", 0)),
        "量能恢复": int(result.dimensions.get("量能恢复", 0)),
        "均线支撑": int(result.dimensions.get("均线支撑", 0)),
        "估值吸引": int(result.dimensions.get("估值吸引", 0)),
        "筹码沉淀": int(result.dimensions.get("筹码沉淀", 0)),
        "主力资金": int(result.dimensions.get("主力资金", 0)),
        "_raw": result.raw,
    }
