"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from data.sector import _classify_stock_sector, _get_sector_fund_flow, _get_cached_sector_data
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer

def _calc_5d_gain(closes):
    """从收盘价数组计算近5日涨跌幅(%)"""
    if len(closes) < 6:
        return 0
    return (closes[-1] / closes[-6] - 1.0) * 100

def calculate_oversold_rebound_score(kline_df, stock_data=None):
    """超跌反弹模型：空间/情绪量能/择时确认/板块共振 四维评分。

    kline_df: 含 收盘/开盘/最高/最低/成交量 列（支持中英文列名）
    stock_data: 可选，含 sector 字段用于板块共振加成
    返回: {pass, 综合评分, 空间维度, 情绪量能, 择时确认, 板块共振}
    """
    close_col = '收盘' if '收盘' in kline_df.columns else 'close'
    open_col = '开盘' if '开盘' in kline_df.columns else 'open'
    high_col = '最高' if '最高' in kline_df.columns else 'high'
    low_col = '最低' if '最低' in kline_df.columns else 'low'
    volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'

    closes = kline_df[close_col].values.astype(float)
    opens = kline_df[open_col].values.astype(float)
    highs = kline_df[high_col].values.astype(float)
    lows = kline_df[low_col].values.astype(float)
    volumes = kline_df[volume_col].values.astype(float)
    n = len(closes)

    if n < 20:
        return {"pass": True, "综合评分": 0, "空间维度": 0, "情绪量能": 0, "择时确认": 0, "板块共振": 0}

    # ============ 一、空间维度（满分40）============
    space_score = 0

    # 1. 跌幅达标（25分）— 近120日最高点回调幅度
    if n >= 120:
        high_120 = float(np.max(highs[-120:]))
    elif n >= 60:
        high_120 = float(np.max(highs[-n:]))
    else:
        high_120 = float(np.max(highs[-n:]))
    if high_120 > 0:
        drawdown = (closes[-1] / high_120 - 1.0) * 100  # 负值 = 下跌
        if drawdown <= -50:
            space_score += 25
        elif drawdown <= -40:
            space_score += 20
        elif drawdown <= -30:
            space_score += 15
        elif drawdown < -10:
            space_score += 5

    # 2. BIAS负乖离（15分）— 相对MA20
    if n >= 20:
        ma20 = float(np.mean(closes[-20:]))
        if ma20 > 0:
            bias = (closes[-1] / ma20 - 1.0) * 100
            if bias < -15:
                space_score += 15
            elif bias < -10:
                space_score += 10
            elif bias < -5:
                space_score += 5

    # ============ 二、情绪量能维度（满分30）============
    sentiment_score = 0

    # 1. 成交量萎缩（15分）
    if n >= 60:
        vol_ma5 = float(np.mean(volumes[-5:]))
        vol_max_60 = float(np.max(volumes[-60:]))
        if vol_max_60 > 0:
            vol_ratio = vol_ma5 / vol_max_60
            if vol_ratio <= 0.25:
                sentiment_score += 15
            elif vol_ratio <= 0.33:
                sentiment_score += 12
            elif vol_ratio <= 0.5:
                sentiment_score += 7
            else:
                sentiment_score += 2

    # 1b. 连续下跌天数加分
    consecutive_down = 0
    for i in range(-1, -n, -1):
        if closes[i] < closes[i - 1]:
            consecutive_down += 1
        else:
            break
    if consecutive_down >= 8:
        sentiment_score += 8
    elif consecutive_down >= 5:
        sentiment_score += 5
    elif consecutive_down >= 3:
        sentiment_score += 3

    # 2. K线止跌信号（15分）— 近3日
    if n >= 3:
        kline_signals = 0
        for i in range(max(-3, -n), 0):
            body = abs(closes[i] - opens[i])
            if closes[i] >= opens[i]:
                lower_shadow = opens[i] - lows[i]
            else:
                lower_shadow = closes[i] - lows[i]
            amplitude = highs[i] - lows[i]

            # 长下影线（下影线 >= 实体2倍）
            if body > 0 and lower_shadow >= body * 2:
                kline_signals = max(kline_signals, 8)

            # 十字星
            if amplitude > 0 and body / amplitude < 0.3:
                kline_signals = max(kline_signals, 5)

        # 连续2日小阳线且不创新低
        bar1_positive = closes[-1] > opens[-1]
        bar2_positive = closes[-2] > opens[-2]
        recent_low = float(np.min(lows[-3:]))
        if n >= 6:
            prev_low = float(np.min(lows[-6:-3]))
        else:
            prev_low = recent_low
        if bar1_positive and bar2_positive and recent_low >= prev_low:
            kline_signals += 7

        sentiment_score += min(kline_signals, 15)

    # ============ 三、择时确认维度（满分30）============
    timing_score = 0

    # 1. 站上MA5（10分）
    if n >= 6:
        ma5 = float(np.mean(closes[-5:]))
        ma5_prev = float(np.mean(closes[-6:-1]))
        if closes[-1] > ma5:
            if ma5 >= ma5_prev:
                timing_score += 10
            else:
                timing_score += 5

    # 2. KDJ J值拐头（5分）
    if n >= 13:
        try:
            # 计算 KDJ（9,3,3）
            k_values = [50.0, 50.0]  # 初始值
            d_values = [50.0, 50.0]
            for idx in range(8, n):
                low_9 = float(np.min(lows[idx - 8:idx + 1]))
                high_9 = float(np.max(highs[idx - 8:idx + 1]))
                rsv = ((closes[idx] - low_9) / (high_9 - low_9) * 100) if high_9 > low_9 else 50.0
                k = 2.0 / 3.0 * k_values[-1] + 1.0 / 3.0 * rsv
                d = 2.0 / 3.0 * d_values[-1] + 1.0 / 3.0 * k
                k_values.append(k)
                d_values.append(d)
            j_vals = [3.0 * k_values[i] - 2.0 * d_values[i] for i in range(len(k_values))]
            if len(j_vals) >= 3:
                j_now = j_vals[-1]
                j_prev = j_vals[-2]
                if j_now < 0 and j_now > j_prev:
                    timing_score += 5
        except Exception:
            pass

    # 3. MACD绿柱缩短/底背离（5分）
    if n >= 27:
        try:
            ema12 = pd.Series(closes).ewm(span=12, adjust=False).mean().values
            ema26 = pd.Series(closes).ewm(span=26, adjust=False).mean().values
            dif = ema12 - ema26
            dea = pd.Series(dif).ewm(span=9, adjust=False).mean().values
            macd_bar = 2.0 * (dif - dea)

            if len(macd_bar) >= 3:
                bar_now = abs(macd_bar[-1])
                bar_prev = abs(macd_bar[-2])
                # 绿柱缩短
                if macd_bar[-1] < 0 and bar_now < bar_prev:
                    timing_score += 5
        except Exception:
            pass

    # 4. 放量转强（10分）
    if n >= 5:
        vol_ma5 = float(np.mean(volumes[-5:]))
        if len(volumes) >= 2:
            if volumes[-1] > volumes[-2] * 1.2 and volumes[-1] > vol_ma5 * 1.2:
                if closes[-1] > opens[-1]:
                    timing_score += 10
                else:
                    timing_score += 5

    # ============ 四、板块共振加成（+10，不计入满分100）============
    sector_bonus = 0
    if stock_data and stock_data.get("sector"):
        sector_name = stock_data["sector"]
        fund_flows = _get_sector_fund_flow()
        sector_fallback_used = False
        if fund_flows:
            sector_flow = fund_flows.get(sector_name, None)
            if sector_flow is not None and sector_flow > 0:
                sector_bonus = 10
            else:
                sector_fallback_used = True
        else:
            sector_fallback_used = True

        # 🔧 P0修复: 板块资金流不可用时，用板块涨跌幅+涨停数做fallback
        if sector_fallback_used and sector_bonus == 0:
            try:
                sector_data, _ = _get_cached_sector_data()
                if sector_data and sector_name in sector_data:
                    sd = sector_data[sector_name]
                    # pytdx 数据字段为 daily_gain / limit_up_count，非中文键名
                    sec_gain = float(sd.get('daily_gain', 0) or 0)
                    sec_zt = int(sd.get('limit_up_count', 0) or 0)
                    # 板块涨幅>1%且涨停≥3 → +10; 涨幅>0 → +5
                    if sec_gain > 1.0 and sec_zt >= 3:
                        sector_bonus = 10
                    elif sec_gain > 0 and sec_zt >= 1:
                        sector_bonus = 5
                    elif sec_gain > 0:
                        sector_bonus = 3
                    # daily_gain/limit_up_count 为0时（pytdx未填充），尝试多级fallback
                    elif sec_gain == 0 and sec_zt == 0:
                        # 第3层fallback：从K线计算5日涨幅，侧面反映板块可能有企稳
                        _chg5 = _calc_5d_gain(closes) if n >= 6 else 0
                        if _chg5 > 5:
                            sector_bonus = 3
                elif sector_data is not None and sector_name not in sector_data:
                    # 第4层fallback：板块不在 sector_data 中，用个股自身5日涨幅
                    _chg5 = _calc_5d_gain(closes) if n >= 6 else 0
                    if _chg5 > 5:
                        sector_bonus = 3
                elif sector_data is None:
                    # sector_data为空 → 用个股5日涨幅做弱fallback
                    _chg5 = _calc_5d_gain(closes) if n >= 6 else 0
                    if _chg5 > 5:
                        sector_bonus = 3
            except Exception:
                pass

    total = space_score + sentiment_score + timing_score

    return {
        "pass": True,
        "综合评分": total,
        "空间维度": space_score,
        "情绪量能": sentiment_score,
        "择时确认": timing_score,
        "板块共振": sector_bonus,
    }


# ═══════════════════════════════════════════════════
#  OversoldScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

OVERSOLD_DIM_NAMES = ["空间维度", "情绪量能", "择时确认", "板块共振"]
OVERSOLD_RAW_KEYS = ["space", "sentiment", "timing", "sector"]


@register_scorer
class OversoldScorer(BaseScorer):
    """超跌反弹模型：四维评分（空间维度/情绪量能/择时确认/板块共振）"""

    model_name = "oversold"

    def compute(self, si: ScoreInput) -> ScoreResult:
        kline_df = si.kline_df
        sd = si.stock_data

        if kline_df is None or len(kline_df) < 20:
            return ScoreResult(
                score=0, passed=False, filter_msg="K线不足20日",
                dimensions={k: 0 for k in OVERSOLD_DIM_NAMES},
                raw={k: 0 for k in OVERSOLD_RAW_KEYS},
            )

        close_col = '收盘' if '收盘' in kline_df.columns else 'close'
        open_col = '开盘' if '开盘' in kline_df.columns else 'open'
        high_col = '最高' if '最高' in kline_df.columns else 'high'
        low_col = '最低' if '最低' in kline_df.columns else 'low'
        volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'

        closes = kline_df[close_col].values.astype(float)
        opens = kline_df[open_col].values.astype(float)
        highs = kline_df[high_col].values.astype(float)
        lows = kline_df[low_col].values.astype(float)
        volumes = kline_df[volume_col].values.astype(float)
        n = len(closes)

        # 一、空间维度（满分40）
        space_score = 0
        if n >= 120:
            high_120 = float(np.max(highs[-120:]))
        elif n >= 60:
            high_120 = float(np.max(highs[-60:]))
        else:
            high_120 = float(np.max(highs[-n:]))
        if high_120 > 0:
            dd = (closes[-1] / high_120 - 1.0) * 100
            if dd <= -50: space_score += 25
            elif dd <= -40: space_score += 20
            elif dd <= -30: space_score += 15
            elif dd < -10: space_score += 5

        if n >= 20:
            ma20 = float(np.mean(closes[-20:]))
            if ma20 > 0:
                bias = (closes[-1] / ma20 - 1.0) * 100
                if bias < -15: space_score += 15
                elif bias < -10: space_score += 10
                elif bias < -5: space_score += 5

        # 二、情绪量能维度（满分30）
        sentiment_score = 0
        if n >= 60:
            v5 = float(np.mean(volumes[-5:]))
            v60 = float(np.max(volumes[-60:]))
            if v60 > 0:
                vr = v5 / v60
                if vr <= 0.25: sentiment_score += 15
                elif vr <= 0.33: sentiment_score += 12
                elif vr <= 0.5: sentiment_score += 7
                else: sentiment_score += 2

        cd = 0
        for i in range(-1, -n, -1):
            if closes[i] < closes[i - 1]: cd += 1
            else: break
        if cd >= 8: sentiment_score += 8
        elif cd >= 5: sentiment_score += 5
        elif cd >= 3: sentiment_score += 3

        if n >= 3:
            ks = 0
            for i in range(max(-3, -n), 0):
                body = abs(closes[i] - opens[i])
                ls = (opens[i] - lows[i]) if closes[i] >= opens[i] else (closes[i] - lows[i])
                amp = highs[i] - lows[i]
                if body > 0 and ls >= body * 2: ks = max(ks, 8)
                if amp > 0 and body / amp < 0.3: ks = max(ks, 5)
            b1 = closes[-1] > opens[-1]
            b2 = closes[-2] > opens[-2]
            rl = float(np.min(lows[-3:]))
            pl = float(np.min(lows[-6:-3])) if n >= 6 else rl
            if b1 and b2 and rl >= pl: ks += 7
            sentiment_score += min(ks, 15)

        # 三、择时确认维度（满分30）
        timing_score = 0
        if n >= 6:
            ma5 = float(np.mean(closes[-5:]))
            ma5_prev = float(np.mean(closes[-6:-1]))
            if closes[-1] > ma5:
                timing_score += 10 if ma5 >= ma5_prev else 5

        if n >= 13:
            try:
                k_vals, d_vals = [50.0, 50.0], [50.0, 50.0]
                for idx in range(8, n):
                    low9 = float(np.min(lows[idx - 8:idx + 1]))
                    high9 = float(np.max(highs[idx - 8:idx + 1]))
                    rsv = ((closes[idx] - low9) / (high9 - low9) * 100) if high9 > low9 else 50.0
                    k = 2.0 / 3.0 * k_vals[-1] + 1.0 / 3.0 * rsv
                    d = 2.0 / 3.0 * d_vals[-1] + 1.0 / 3.0 * k
                    k_vals.append(k); d_vals.append(d)
                j_vals = [3 * k_vals[i] - 2 * d_vals[i] for i in range(len(k_vals))]
                if len(j_vals) >= 3 and j_vals[-1] < 0 and j_vals[-1] > j_vals[-2]:
                    timing_score += 5
            except Exception: pass

        if n >= 27:
            try:
                ema12 = pd.Series(closes).ewm(span=12, adjust=False).mean().values
                ema26 = pd.Series(closes).ewm(span=26, adjust=False).mean().values
                dif = ema12 - ema26
                dea = pd.Series(dif).ewm(span=9, adjust=False).mean().values
                macd_bar = 2.0 * (dif - dea)
                if len(macd_bar) >= 3 and macd_bar[-1] < 0 and abs(macd_bar[-1]) < abs(macd_bar[-2]):
                    timing_score += 5
            except Exception: pass

        if n >= 5:
            v5 = float(np.mean(volumes[-5:]))
            if len(volumes) >= 2:
                if volumes[-1] > volumes[-2] * 1.2 and volumes[-1] > v5 * 1.2:
                    timing_score += 10 if closes[-1] > opens[-1] else 5

        # 四、板块共振加成
        sector_bonus = 0
        if sd and sd.get("sector"):
            sn = sd["sector"]
            fund_flows = _get_sector_fund_flow()
            sf_used = False
            if fund_flows:
                sf = fund_flows.get(sn)
                if sf is not None and sf > 0: sector_bonus = 10
                else: sf_used = True
            else: sf_used = True

            if sf_used and sector_bonus == 0:
                try:
                    sdata, _ = _get_cached_sector_data()
                    if sdata and sn in sdata:
                        sd2 = sdata[sn]
                        sg = float(sd2.get('daily_gain', 0) or 0)
                        sz = int(sd2.get('limit_up_count', 0) or 0)
                        if sg > 1.0 and sz >= 3: sector_bonus = 10
                        elif sg > 0 and sz >= 1: sector_bonus = 5
                        elif sg > 0: sector_bonus = 3
                        elif sg == 0 and sz == 0:
                            c5 = _calc_5d_gain(closes) if n >= 6 else 0
                            if c5 > 5: sector_bonus = 3
                    elif sdata is not None and sn not in sdata:
                        c5 = _calc_5d_gain(closes) if n >= 6 else 0
                        if c5 > 5: sector_bonus = 3
                    elif sdata is None:
                        c5 = _calc_5d_gain(closes) if n >= 6 else 0
                        if c5 > 5: sector_bonus = 3
                except Exception: pass

        total = space_score + sentiment_score + timing_score

        return ScoreResult(
            score=total, passed=True,
            dimensions={
                "空间维度": space_score, "情绪量能": sentiment_score,
                "择时确认": timing_score, "板块共振": sector_bonus,
            },
            raw={"space": space_score, "sentiment": sentiment_score,
                 "timing": timing_score, "sector": sector_bonus},
        )
