"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import numpy as np
from core.config import _VERBOSE
from data.dde import _load_dde_data, _get_dde_or_fallback, get_resonance_cache, save_resonance_cache, _get_resonance_cross_ref
from data.sector import _get_cached_sector_data
from core.scorer_base import BaseScorer, ScoreInput, ScoreResult, register_scorer

def get_resonance_data(quotes_df):
    """
    基于东方财富DDE数据计算共振模型四维评分：
    1. 资金流向 (30分)：特大单净比 + 大单净比
    2. DDE决策   (20分)：DDX + DDY + DDZ + 连续天数
    3. K线结构   (25分)：由 calculate_resonance_score 从行情数据补充
    4. 板块热度   (25分)：由 calculate_resonance_score 从板块数据补充

    quotes_df: fetch_all_a_stocks() 返回的行情 DataFrame
    """
    dde_df = _get_dde_or_fallback(quotes_df)
    if dde_df is None:
        return None
    
    if quotes_df is None or len(quotes_df) == 0:
        return None
    
    # 过滤 ST/退市
    quotes_df = quotes_df[~quotes_df['名称'].str.contains('ST|退市|N|C', na=False)].copy()
    
    # 交集：DDE数据 ∩ 行情数据
    valid_codes = set(dde_df['代码']) & set(quotes_df['代码'])
    if _VERBOSE: print(f"[共振模型] DDE+行情交集: {len(valid_codes)} 只")
    
    if len(valid_codes) == 0:
        return None
    
    # 用 DDX 全局排名归一化（DDX 是 DDE 核心指标）
    dde_sorted = dde_df.set_index('代码')
    
    # 分数归一化辅助函数
    def normalize_rank(series, max_score, center=0.5):
        """按百分位排名映射到 [0, max_score]"""
        ranked = series.rank(pct=True)
        return (ranked * max_score).clip(0, max_score)
    
    # ----- 1. 资金流向 (30分) -----
    # 特大单净比 + 大单净比 = 主力资金净流向
    # P0: 持续性过滤 — 特大单净比>0 且大单净比>0 同时满足才给满分
    dde_sorted['资金流向_raw'] = (dde_sorted['特大单净比'] + dde_sorted['大单净比']).fillna(0)
    dde_sorted['资金流向'] = normalize_rank(dde_sorted['资金流向_raw'], 30)
    # 持续性标记：双条件同时满足
    dde_sorted['_both_positive'] = ((dde_sorted['特大单净比'] > 0) & (dde_sorted['大单净比'] > 0)).astype(float)
    dde_sorted['_one_positive'] = ((dde_sorted['特大单净比'] > 0) | (dde_sorted['大单净比'] > 0)).astype(float)
    # 只有一项满足给一半分（相对于满分30的比例）
    dde_sorted['资金流向_persist'] = dde_sorted['资金流向'] * (
        dde_sorted['_both_positive'] * 1.0 + (1 - dde_sorted['_both_positive']) * dde_sorted['_one_positive'] * 0.5
    )
    
    # ----- 2. DDE决策 (20分) -----
    # P0: DDX 平滑 — 用近3日 DDX 均值替代单日 DDX（用 5日DDX/5 近似3日均值）
    dde_sorted['DDX_3d_mean'] = dde_sorted['5日DDX'].fillna(dde_sorted['DDX']) / 5
    # DDX (权重0.4) + DDY (0.2) + DDZ (0.2) + 连续天数加成 (0.2)
    dde_sorted['DDX_norm'] = normalize_rank(dde_sorted['DDX_3d_mean'].fillna(0), 8)
    dde_sorted['DDY_norm'] = normalize_rank(dde_sorted['DDY'].fillna(0), 4)
    dde_sorted['DDZ_norm'] = normalize_rank(dde_sorted['DDZ'].fillna(0), 4)
    
    # 连续天数：正值 DDX 时连续天数越多越好，负值 DDX 时连续越少越好
    dde_sorted['连续加成'] = dde_sorted.apply(
        lambda r: min(4, max(0, r['连续'] * 0.5)) if r.get('DDX', 0) >= 0 else max(0, 4 - r['连续'] * 0.5), axis=1
    )
    dde_sorted['DDE决策'] = (
        dde_sorted['DDX_norm'] + dde_sorted['DDY_norm'] + dde_sorted['DDZ_norm'] + dde_sorted['连续加成']
    ).clip(0, 20)
    
    # ----- 构建结果 -----
    # P0: 资金流向改用持续性过滤后的分数
    result = {}
    for code in valid_codes:
        row = dde_sorted.loc[code]
        result[code] = {
            'money_flow_score': round(float(row['资金流向_persist']), 1),
            'dde_proxy_score': round(float(row['DDE决策']), 1),
            'kline_structure_raw': 0,      # K线原始分，由 calculate_resonance_score 补充
            'sector_heat_raw': 5,           # 板块原始分，由 calculate_resonance_score 补充
            'kline_structure_score': 0,     # 归一化后
            'sector_heat_score': 5,         # 归一化后
        }
    
    if _VERBOSE: print(f"[共振模型] 生成评分数据: {len(result)} 只")
    return result if result else None

def calculate_resonance_score(resonance_data, quotes_df=None):
    """
    计算四维共振综合评分（满分100）
    资金流向 30分 + DDE决策 20分 + K线结构 25分 + 板块热度 25分
    P1: K线结构和板块热度使用百分位归一化
    """
    if resonance_data is None:
        return {}
    
    sector_data = _get_cached_sector_data()
    codes = list(resonance_data.keys())
    
    # ===== 第一遍：计算所有股票的 K线和板块 原始分 =====
    kl_raw = {}
    sh_raw = {}
    for code in codes:
        rd = resonance_data[code]
        
        # ----- K线结构原始分 -----
        kl_score = 10.0
        if quotes_df is not None:
            row = quotes_df[quotes_df['代码'] == code]
            if len(row) > 0:
                r = row.iloc[0]
                chg5 = float(r.get('5日涨幅', 0) or 0)
                chg5_score = min(15, max(0, 7.5 + chg5 * 0.75))
                vol_ratio_q = float(r.get('量比', 1) or 1)
                vol_score_k = min(10, max(0, vol_ratio_q * 5))
                kl_score = chg5_score + vol_score_k
        kl_raw[code] = kl_score
        
        # ----- 板块热度原始分 -----
        sh_score = 10.0
        sector_found = False
        if quotes_df is not None and sector_data:
            row = quotes_df[quotes_df['代码'] == code]
            if len(row) > 0:
                sector = str(row.iloc[0].get('板块', ''))
                if sector and sector in sector_data:
                    sd = sector_data[sector]
                    sec_chg = float(sd.get('涨幅', 0) or 0)
                    sec_chg_score = min(15, max(0, 7.5 + sec_chg * 0.5))
                    zt_count = int(sd.get('涨停数', 0) or 0)
                    zt_score = min(10, zt_count * 1.5)
                    sh_score = sec_chg_score + zt_score
                    sector_found = True

        # 🔧 P0修复: 板块数据不可用时，用个股自身表现替代（避免全部12.5无区分度）
        if not sector_found and quotes_df is not None:
            row = quotes_df[quotes_df['代码'] == code]
            if len(row) > 0:
                r = row.iloc[0]
                chg5 = float(r.get('5日涨幅', 0) or 0)
                chg20 = float(r.get('涨跌幅_20d', 0) or 0)
                vol_ratio = float(r.get('量比', 1) or 1)
                # 用个股5日+20日涨幅和量比近似估计板块热度
                proxy_chg = (chg5 * 0.6 + chg20 * 0.4)  # 加权涨跌幅
                proxy_score = min(15, max(0, 7.5 + proxy_chg * 0.5))
                proxy_vol = min(10, max(0, vol_ratio * 3))
                sh_score = proxy_score + proxy_vol
        sh_raw[code] = sh_score
    
    # ===== P1: 百分位归一化（K线和板块） =====
    kl_arr = np.array([kl_raw[c] for c in codes])
    sh_arr = np.array([sh_raw[c] for c in codes])
    
    # 纯 numpy 实现 rank → percentile → 0~max_score
    def _percentile_norm(raw_arr, max_score):
        if len(raw_arr) <= 1 or np.all(raw_arr == raw_arr[0]):
            return np.full_like(raw_arr, max_score * 0.5, dtype=float)
        ranks = np.argsort(np.argsort(raw_arr)) + 1  # 最小=1, 最大=N
        percentiles = ranks / len(raw_arr)
        return (percentiles * max_score).clip(0, max_score)
    
    kl_norm = _percentile_norm(kl_arr, 25)
    sh_norm = _percentile_norm(sh_arr, 25)
    
    # ===== 组装最终得分 =====
    scores = {}
    for i, code in enumerate(codes):
        rd = resonance_data[code]
        mf_score = rd.get('money_flow_score', 0)
        dde_score = rd.get('dde_proxy_score', 0)
        kl_final = round(float(kl_norm[i]), 1)
        sh_final = round(float(sh_norm[i]), 1)
        
        rd['kline_structure_raw'] = round(kl_raw[code], 1)
        rd['sector_heat_raw'] = round(sh_raw[code], 1)
        rd['kline_structure_score'] = kl_final
        rd['sector_heat_score'] = sh_final
        
        total = mf_score + dde_score + kl_final + sh_final
        scores[code] = {
            'total': round(total, 1),
            'money_flow': round(mf_score, 1),
            'dde_proxy': round(dde_score, 1),
            'kline_structure': kl_final,
            'sector_heat': sh_final,
        }
    
    return scores

def _classify_resonance_style(code, resonance_data, quotes_df):
    """
    轻量分类：基于行情快照+DDE数据判断共振标的当前状态
    - 盘中走强：涨跌幅 ≥ 2% 且 量比 ≥ 1.0 且 DDE决策 ≥ 10 → 今日已启动
    - 超跌待反转：涨跌幅 ≤ 0% 且 换手率 ≤ 10% 且 DDE决策 ≤ 10 → 回调末端
    - 蓄势待发：不满足以上任一 → 未启动，等待催化
    注意：标签描述当前状态，综合评分描述未来潜力，两者独立。
    """
    if quotes_df is None:
        return '蓄势待发'
    
    row = quotes_df[quotes_df['代码'] == code]
    if len(row) == 0:
        return '蓄势待发'
    
    r = row.iloc[0]
    chg = float(r.get('涨跌幅', 0) or 0)
    vol_ratio = float(r.get('量比', 1) or 1)
    turnover = float(r.get('换手率', 5) or 5)
    
    rd = resonance_data.get(code, {}) if resonance_data else {}
    dde_score = float(rd.get('dde_proxy_score', 10))
    
    if chg >= 2 and vol_ratio >= 1.0 and dde_score >= 10:
        return '盘中走强'
    
    if chg <= 0 and turnover <= 10 and dde_score <= 10:
        return '超跌待反转'
    
    return '蓄势待发'

def get_dde_confirmation_scores():
    """全量DDE校正分：code -> 资金流向(30)+DDE决策(20) = 满分50
    
    独立评分函数，不依赖共振模型的其他部分。
    对全部DDE覆盖股票进行 normalize_rank 排名赋予校正分，
    供追高/低吸模型的Top30表格插入 DDE资金确认列。
    """
    dde_df = _load_dde_data()
    if dde_df is None or len(dde_df) == 0:
        return {}
    
    dde_sorted = dde_df.set_index('代码')
    
    def _norm_rank(series, max_score):
        ranked = series.rank(pct=True)
        return (ranked * max_score).clip(0, max_score)
    
    dde_sorted['资金流向_raw'] = (dde_sorted['特大单净比'] + dde_sorted['大单净比']).fillna(0)
    dde_sorted['资金流向'] = _norm_rank(dde_sorted['资金流向_raw'], 30)
    
    dde_sorted['DDX_norm'] = _norm_rank(dde_sorted['DDX'].fillna(0), 8)
    dde_sorted['DDY_norm'] = _norm_rank(dde_sorted['DDY'].fillna(0), 4)
    dde_sorted['DDZ_norm'] = _norm_rank(dde_sorted['DDZ'].fillna(0), 4)
    
    dde_sorted['连续加成'] = dde_sorted.apply(
        lambda r: min(4, max(0, r['连续'] * 0.5)) if r.get('DDX', 0) >= 0
        else max(0, 4 - r['连续'] * 0.5), axis=1
    )
    dde_sorted['DDE决策'] = (dde_sorted['DDX_norm'] + dde_sorted['DDY_norm']
                             + dde_sorted['DDZ_norm'] + dde_sorted['连续加成']).clip(0, 20)
    
    dde_sorted['校正分'] = (dde_sorted['资金流向'] + dde_sorted['DDE决策']).round(1)
    
    result = {}
    for code in dde_sorted.index:
        result[code] = float(dde_sorted.loc[code, '校正分'])
    return result


# ═══════════════════════════════════════════════════
#  ResonanceScorer — 新 Scorer 基类实现
# ═══════════════════════════════════════════════════

RESONANCE_DIM_NAMES = ["资金流向", "DDE决策", "K线结构", "板块热度"]
RESONANCE_RAW_KEYS = ["money_flow", "dde", "kline", "sector"]


@register_scorer
class ResonanceScorer(BaseScorer):
    """共振模型：四维评分（资金流向30/DDE决策20/K线结构25/板块热度25）"""

    model_name = "resonance"

    def compute(self, si: ScoreInput) -> ScoreResult:
        """注意：共振模型的单只股票评分需要完整的 resonance_data 上下文。
        如果 si.resonance_data 为空，将使用 si.quotes_df 现场计算。
        """
        code = si.code
        rd = si.resonance_data
        quotes_df = si.quotes_df

        # 如果没有预计算的 resonance_data，现场计算
        if not rd and quotes_df is not None:
            rd = get_resonance_data(quotes_df)

        # 从 resonance_data 取当前股票的数据
        stock_rd = rd.get(code, {}) if rd else {}
        if not stock_rd:
            return ScoreResult(
                score=0, passed=False, filter_msg="无共振数据",
                dimensions={k: 0 for k in RESONANCE_DIM_NAMES},
                raw={k: 0 for k in RESONANCE_RAW_KEYS},
            )

        mf = stock_rd.get('money_flow_score', 0)      # 资金流向
        dde = stock_rd.get('dde_proxy_score', 0)       # DDE决策
        kl = stock_rd.get('kline_structure_score', 0)   # K线结构
        sh = stock_rd.get('sector_heat_score', 0)        # 板块热度

        total = round(mf + dde + kl + sh, 1)

        # 信号分类
        if total >= 80:
            signal = "强烈共振"
            sig_cls = "badge-strong"
            pos_msg = "主力资金+板块共振，建议关注"
        elif total >= 65:
            signal = "温和共振"
            sig_cls = "badge-attention"
            pos_msg = "资金温和流入，可跟踪观察"
        elif total >= 50:
            signal = "初步信号"
            sig_cls = "badge-hold"
            pos_msg = "有资金关注但未形成合力"
        else:
            signal = "无信号"
            sig_cls = "badge-hold"
            pos_msg = "资金面偏弱"

        return ScoreResult(
            score=total, passed=True,
            signal=signal, signal_class=sig_cls, position_msg=pos_msg,
            dimensions={
                "资金流向": round(mf, 1), "DDE决策": round(dde, 1),
                "K线结构": round(kl, 1), "板块热度": round(sh, 1),
            },
            raw={"money_flow": mf, "dde": dde, "kline": kl, "sector": sh},
        )
