"""Auto-generated by refactor_split.py — DO NOT edit manually."""
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from core.scoring.golden_cross import _get_gc_params, _compute_macd

def hard_filter_v3(stock_data):
    """满足任意一条直接淘汰（7条硬过滤规则）。return: (True=保留, msg)
    1. 3日涨幅 > 15% → 淘汰（短期过热）
    2. 距MA60涨幅 > 80% → 淘汰（中长期乖离过大）
    3. 缩量新高顶背离 → 淘汰
    4. 机构连续2日净卖出 → 淘汰
    5. MACD高位顶背离 → 淘汰
    6. 连续6交易日累计涨幅 > 25% → 淘汰（中期过热）
    7. 所属板块资金净流出 → 淘汰（板块无主力资金支持）
    """
    if stock_data["3d_gain"] > 15:
        return False, f"3日涨幅{stock_data['3d_gain']:.1f}%>15%"
    if stock_data["ma60"] > 0 and (stock_data["close"] / stock_data["ma60"] - 1) > 0.8:
        return False, f"距MA60涨幅>{80}%"
    if stock_data["vol_today"] < stock_data["ma5_vol"] * 0.8 and stock_data["new_high_2d"]:
        return False, "缩量新高顶背离"
    if stock_data["inst_net_sell_2d"]:
        return False, "机构连续2日净卖出"
    if stock_data["macd_top_divergence"]:
        return False, "MACD高位顶背离"
    if stock_data.get("6d_gain", 0) > 25:
        return False, f"6日累计涨幅{stock_data['6d_gain']:.1f}%>25%"
    if stock_data.get("sector_fund_outflow", False):
        return False, f"板块{stock_data.get('sector', '')}资金净流出"
    return True, "过滤通过"

def _gc_hard_filter(code, kline_df):
    """
    入库硬条件 — 双通道：
    通道A（零下通道）：主升涨幅 + 回撤 + MACD DIFF < 0（原有逻辑）
    通道B（水上通道）：回调洗盘后 MACD 零轴上方金叉，四条件缺一不可
      1) 价格在20日线上方但乖离率≤25%
      2) 60日线方向向上
      3) 近20日有过≥10%回撤
      4) 当日成交量≥5日均量1.2倍
    返回 (通过, 信息, 通道标识: 'zero_below'/'water_above'/None)
    """
    if kline_df is None or len(kline_df) < 40:
        return False, "K线不足40日", None
    closes = kline_df['收盘'].values.astype(float)
    n = len(closes)
    params = _get_gc_params()

    half = min(60, n)
    recent = closes[-half:]
    rise_pct = (recent.max() - recent[0]) / recent[0] * 100
    peak_idx = int(np.argmax(recent))
    peak_val = recent[peak_idx]
    current = closes[-1]
    decline = (peak_val - current) / peak_val * 100
    dif, _, _ = _compute_macd(closes)

    # ---------- 通道A：零下通道（原有逻辑） ----------
    if not np.isnan(dif[-1]) and dif[-1] < 0:
        if rise_pct < params["main_rise_pct"]:
            return False, f"主升涨幅{rise_pct:.0f}%<{params['main_rise_pct']}%", None
        if decline < params["decline_pct"]:
            return False, f"回撤{decline:.0f}%<{params['decline_pct']}%", None
        return True, f"零下 主升{rise_pct:.0f}% 回撤{decline:.0f}% DIFF={dif[-1]:.3f}", "zero_below"

    # ---------- 通道B：水上通道（新增） ----------
    # 条件1: 价格在20日线上方但乖离率≤25%
    if n < 25:
        return False, "K线不足25日 不适合水上通道", None
    ma20 = pd.Series(closes).rolling(20).mean().values
    cur_ma20 = ma20[-1]
    if np.isnan(cur_ma20) or cur_ma20 <= 0:
        return False, "MA20无效", None
    if closes[-1] < cur_ma20:
        return False, "水上通道: 股价低于20日线", None
    deviation = (closes[-1] - cur_ma20) / cur_ma20 * 100
    if deviation > 25:
        return False, f"水上通道: 乖离率{deviation:.0f}%>25% 高位风险", None

    # 条件2: 60日线方向向上
    if n < 65:
        return False, "K线不足65日 无法判断60日线方向", None
    ma60 = pd.Series(closes).rolling(60).mean().values
    if np.isnan(ma60[-1]) or np.isnan(ma60[-11]):
        return False, "MA60无效", None
    ma60_slope = (ma60[-1] - ma60[-11]) / ma60[-11] * 100 if ma60[-11] > 0 else 0
    if ma60_slope <= 0:
        return False, f"水上通道: 60日线向下({ma60_slope:.2f}%) 下跌通道风险", None

    # 条件3: 近20日有过≥10%回撤（确认是回调洗盘）
    recent20 = closes[-20:]
    recent20_peak = recent20.max()
    recent20_trough = recent20.min()
    recent20_decline = (recent20_peak - recent20_trough) / recent20_peak * 100
    if recent20_decline < 10:
        return False, f"水上通道: 近20日回撤{recent20_decline:.0f}%<10% 无充分洗盘", None

    # 条件4: 当日成交量≥5日均量1.2倍
    if '成交量' not in kline_df.columns:
        return False, "水上通道: 无成交量数据", None
    volumes = kline_df['成交量'].values.astype(float)
    if len(volumes) < 6:
        return False, "水上通道: 成交量数据不足", None
    ma5_vol = np.mean(volumes[-6:-1])
    if ma5_vol <= 0:
        return False, "水上通道: 5日均量无效", None
    today_vol = volumes[-1]
    vol_ratio = today_vol / ma5_vol
    if vol_ratio < 1.2:
        return False, f"水上通道: 量比{vol_ratio:.1f}<1.2 缩量不可靠", None

    return True, f"水上 乖离{deviation:.0f}% 回撤{recent20_decline:.0f}% MA60↑ 量比{vol_ratio:.1f}", "water_above"

def hard_filter_oversold_rebound(kline_df, stock_data=None):
    """超跌反弹硬过滤 — 满足任一即淘汰。
    规则：
    1. ST/*ST
    2. 近60日最高点回调幅度 < 15%（跌太少），但若近20日跌幅>=5%且连续下跌>=3天则放行
    3. 近5日出现过跌停（排除暴雷股）
    4. 近3日连续放量下跌（排除出货型下跌）
    5. 股价 < 1元（排除仙股）
    返回: (True=保留, filter_msg)
    """
    close_col = '收盘' if '收盘' in kline_df.columns else 'close'
    open_col = '开盘' if '开盘' in kline_df.columns else 'open'
    high_col = '最高' if '最高' in kline_df.columns else 'high'
    volume_col = '成交量' if '成交量' in kline_df.columns else 'volume'

    closes = kline_df[close_col].values.astype(float)
    opens = kline_df[open_col].values.astype(float)
    highs = kline_df[high_col].values.astype(float)
    volumes = kline_df[volume_col].values.astype(float)
    n = len(closes)

    # 5. 股价 < 1 元
    if stock_data:
        price = stock_data.get("close", closes[-1] if n > 0 else 0)
    else:
        price = closes[-1] if n > 0 else 0
    if price < 1.0:
        return False, f"股价{price:.2f}<1元"

    if n < 20:
        return False, "K线数据不足20日"

    # 2. 近60日最高点回调幅度 < 20%（例外：近20日跌幅≥10%且连续下跌≥5天放行）
    n60 = min(60, n)
    high_60 = float(np.max(highs[-n60:]))
    if high_60 > 0:
        drawdown_60 = (closes[-1] / high_60 - 1.0) * 100
    else:
        drawdown_60 = 0.0

    # 计算近20日涨跌幅 和 连续下跌天数（用于例外放行判断）
    change_20d = (closes[-1] / closes[-21] - 1) * 100 if n >= 21 else (closes[-1] / closes[0] - 1) * 100
    consecutive_down = 0
    for i in range(-1, -n, -1):
        if closes[i] < closes[i - 1]:
            consecutive_down += 1
        else:
            break

    # 例外放行：近20日跌幅>=5% 且 连续下跌>=3天
    exception_pass = (change_20d <= -5 and consecutive_down >= 3)

    if drawdown_60 > -15 and not exception_pass:
        return False, f"近60日回调{drawdown_60:.1f}%>-15%（跌幅不够，20日跌{change_20d:.1f}%，连跌{consecutive_down}天）"

    # 3. 近5日出现过跌停
    for i in range(max(-5, -n), 0):
        if n + i - 1 >= 0 and closes[i] > 0 and opens[i] > 0:
            daily_chg = (closes[i] / closes[i - 1] - 1) * 100 if i > -n else 0
            if daily_chg <= -9.9:
                return False, f"近5日内出现跌停"

    # 4. 近3日连续放量下跌（量逐日放大 + 每日收阴）
    if n >= 4:
        fail_count = 0
        for i in range(-3, 0):
            if closes[i] < opens[i] and i > -n:
                if i > -n + 1 and volumes[i] > volumes[i - 1]:
                    fail_count += 1
        if fail_count >= 2:
            return False, "近3日连续放量下跌"

    return True, "过滤通过"
