"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
from functools import lru_cache
from core.protocols import NullSink, AppState
from core.config import BASE_DIR, DEFAULT_LOWBUY_WEIGHTS, DEFAULT_WEIGHTS, _app_cache
from core.scoring.chase_high import calculate_v3_total_score, calculate_five_dimensions_score, _build_stock_data, _classify_signal
from core.scoring.lowbuy import calculate_lowbuy_score, _check_low_buy_conditions, lb_score_valuation, lb_score_chip, _get_lowbuy_params
from core.scoring.golden_cross import calculate_golden_cross_score
from core.scoring.resonance import get_dde_confirmation_scores, calculate_resonance_score, _classify_resonance_style, get_resonance_data
from core.scoring.canslim import calculate_canslim_score
from core.scoring.dilemma import calculate_dilemma_reversal_score
from core.scoring.oversold import calculate_oversold_rebound_score
from core.filters import hard_filter_v3, _gc_hard_filter, hard_filter_oversold_rebound
from data.market import fetch_all_a_stocks, preprocess_stock_data, get_stock_kline, get_kline_with_today, get_all_spot_data, _supplement_tencent_quotes, read_tdx_day_file, calculate_dynamic_recommend_count
from data.cache import save_cache_data
from data.dde import _load_dde_data
from data.financial import get_financial_data
from data.sector import _get_cached_dragon_tiger, _get_cached_sector_data, _get_sector_fund_flow, fetch_dragon_tiger_v3, fetch_sector_board_v3, _classify_stock_sector
from data.tdx_provider import tdx_available, fetch_all_quotes_tdx, fetch_kline_tdx, get_today_quote_single, fetch_sector_data_tdx, resolve_market

def screen_low_buy_stocks(df_market, params=None, sink=None, lowbuy_weights=None):
    """
    低吸模型主筛选函数 (v6 - 完全独立评分体系)
    """
    if sink is None:
        sink = NullSink()
    if lowbuy_weights is None:
        lowbuy_weights = DEFAULT_LOWBUY_WEIGHTS
    # [DEBUG] 统计初始化 — 放最前面，确保任何提前返回都能保存
    _dbg = {"total": 0, "no_kline": 0, "no_new_low": 0, "reversal1": 0, "reversal2": 0, "reversal3": 0,
            "build_err": 0, "score_fail": 0, "decline": 0, "stabil": 0, "vol_rec": 0,
            "ma_sup": 0, "val": 0, "chip": 0, "fund": 0, "total_score": 0, "passed": 0,
            "decline_20d_fail": 0}
    
    if params is None:
        params = _get_lowbuy_params()
    
    # [DEBUG] 确认运行时参数
    _dbg["_params_debug"] = {k: params.get(k) for k in [
        'min_stabilization', 'min_volume_recovery', 'reversal_bottom_pct',
        'reversal_require_uptrend', 'min_total_score', '_params_version'
    ]}
    
    if df_market is None or len(df_market) == 0:
        return pd.DataFrame()
    
    df = df_market.copy()
    
    # 获取辅助数据
    lhb_data = {}
    sector_data = {}
    stock_sector_map = {}
    try:
        lhb_data = _get_cached_dragon_tiger()
        sector_data, stock_sector_map = _get_cached_sector_data()
    except Exception:
        pass

    # 预计算行业PE分布（低吸S5维度用）
    _get_industry_pe_stats(df_market, stock_sector_map)
    
    # ===== 预筛 =====
    pre_db = [f"入参: decline_20d=[{params.get('decline_20d_low',-50)},{params.get('decline_20d_high',0)}] max_vol_ratio={params.get('max_vol_ratio',3)}"]
    pre_db.append(f"原始: {len(df)}只")
    
    if '涨跌幅' in df.columns:
        df = df[df['涨跌幅'] < 9.5]
        pre_db.append(f"涨幅<9.5%: {len(df)}只")
    if '最新价' in df.columns:
        df = df[(df['最新价'] >= 3) & (df['最新价'] <= 200)]
        pre_db.append(f"价格3-200: {len(df)}只")
    
    decline_low = params.get('decline_20d_low', -50)
    decline_high = params.get('decline_20d_high', 0)
    # 10日跌幅过滤延后到逐只K线循环中执行（避免追高模型fillna(0)假数据污染）
    # 此处只做轻量预筛：如果有真实20d数据且明显不符合，提前剔除
    if '涨跌幅_20d' in df.columns:
        df['涨跌幅_20d'] = pd.to_numeric(df['涨跌幅_20d'], errors='coerce')
        has_real = df['涨跌幅_20d'].notna() & (df['涨跌幅_20d'] != 0)  # 0=fillna填充，非真实数据
        pre_db.append(f"20d有真实数据: {has_real.sum()}/{len(df)}只")
        if has_real.any():
            # 仅对真实数据应用跌幅过滤；无真实数据的放过（在K线循环中再查）
            in_range = has_real & ((df['涨跌幅_20d'] >= decline_low) & (df['涨跌幅_20d'] <= decline_high))
            df = df[in_range | ~has_real]
            pre_db.append(f"20d跌幅[{decline_low},{decline_high}]: {in_range.sum()}只通过")
    
    max_vol_ratio = params.get('max_vol_ratio', 3.0)
    if '量比' in df.columns:
        df['量比'] = pd.to_numeric(df['量比'], errors='coerce').fillna(1.0)
        df = df[df['量比'] <= max_vol_ratio]
        pre_db.append(f"量比<={max_vol_ratio}: {len(df)}只")
    
    sample_n = min(len(df), 928)
    pre_db.append(f"预筛后: {len(df)}只 取前{sample_n}")
    _dbg["_pre"] = " | ".join(pre_db)
    
    if len(df) == 0:
        return pd.DataFrame()
    
    df = df.head(sample_n)
    
    # ===== 逐只验证 =====
    results = []
    total = len(df)
    no_new_low_days = params.get('no_new_low_days', 1)
    sink.on_progress(0, total, "低吸筛选中...")
    
    for i, (idx, row) in enumerate(df.iterrows()):
        _dbg["total"] += 1
        if i % 20 == 0:
            sink.on_status(f"🔍 低吸筛选中... ({i+1}/{total}) 已找到 {len(results)} 只")
        
        code = str(row.get('代码', ''))
        kline = get_stock_kline(code, days=max(60, no_new_low_days + 15))
        if kline is None or len(kline) < 10:
            _dbg["no_kline"] += 1; continue
        
        closes = kline['收盘'].values.astype(float)
        n = len(closes)
        
        # 10日跌幅预检（使用K线真实数据，避免fillna(0)假数据）
        if n >= 12:
            kline_chg_10d = (closes[-1] / closes[-12] - 1) * 100
            if kline_chg_10d < decline_low or kline_chg_10d > decline_high:
                _dbg["decline_20d_fail"] += 1; continue
        else:
            kline_chg_10d = None
        
        # K线条件: 不创新低
        if n >= no_new_low_days:
            recent_lows = closes[-no_new_low_days:]
            if closes[-1] <= min(recent_lows) * 0.998:
                _dbg["no_new_low"] += 1; continue
        else:
            _dbg["no_new_low"] += 1; continue
        
        # ===== 硬性反转确认: 底部已过 + 近端止跌回升 =====
        if n < 15:
            _dbg["reversal1"] += 1; continue
        # 找到近15日最低点位置
        low_idx_15 = np.argmin(closes[-15:])
        low_pos = 15 - low_idx_15  # 最低点距今多少天（1=昨天, >=15表示超过15天）
        if low_pos < 1:
            _dbg["reversal1"] += 1; continue  # 最低点就是今天，还没确认反转
        # 近3日均线必须高于最低点一定百分比（确认已脱离底部）
        avg_close_3d = np.mean(closes[-3:])
        min_close_15d = np.min(closes[-15:])
        rev_bottom_pct = params.get('reversal_bottom_pct', 0.2) / 100.0
        if min_close_15d > 0 and (avg_close_3d - min_close_15d) / min_close_15d < rev_bottom_pct:
            _dbg["reversal2"] += 1; continue
        # MA3今日 > MA3前日: 今日均价高于前日（确认企稳，可通过参数关闭）
        if params.get('reversal_require_uptrend', False):
            if np.mean(closes[-3:]) <= np.mean(closes[-4:-1]):
                _dbg["reversal3"] += 1; continue  # MA3未走强
        
        # 机构数据
        lhb_info = lhb_data.get(code, {})
        inst_net_3d = lhb_info.get('inst_net_buy_3d', 0)
        
        # 构建评分数据
        try:
            stock_data = _build_stock_data(row, kline, lhb_data, sector_data, stock_sector_map)
        except Exception:
            _dbg["build_err"] += 1; continue
        
        # 低吸专用评分
        try:
            score_result = calculate_lowbuy_score(stock_data, kline, params)
        except Exception:
            _dbg["score_fail"] += 1; continue
        
        if not score_result.get('pass', False):
            _dbg["score_fail"] += 1; continue
        
        # 六维→七维门槛 — 用原始分(_raw), 而非归一化值(0-100)
        _raw = score_result.get('_raw', {})
        s_decline = _raw.get('s1', 0)     # raw 0-30
        s_stabil = _raw.get('s2', 0)      # raw 0-25
        s_vol_rec = _raw.get('s3', 0)     # raw 0-20
        s_ma = _raw.get('s4', 0)          # raw 0-15
        s_val = _raw.get('s5', 0)         # raw 0-10
        s_chip = _raw.get('s6', 0)        # raw 0-10
        s_fund = _raw.get('s7', 0)        # raw 0-10
        s_total = score_result.get('综合评分', 0)  # 0-100 归一化总分
        
        if s_decline < params.get('min_decline_depth', 8):
            _dbg["decline"] += 1; continue
        if s_stabil < params.get('min_stabilization', 10):
            _dbg["stabil"] += 1; continue
        if s_vol_rec < params.get('min_volume_recovery', 8):
            _dbg["vol_rec"] += 1; continue
        if s_ma < params.get('min_ma_support', 4):
            _dbg["ma_sup"] += 1; continue
        if s_val < params.get('min_valuation_attr', 4):
            _dbg["val"] += 1; continue
        if s_chip < params.get('min_chip_settle', 3):
            _dbg["chip"] += 1; continue
        if s_fund < params.get('min_fund_flow', 2):
            _dbg.setdefault("fund", 0); _dbg["fund"] += 1; continue
        if s_total < params.get('min_total_score', 20):
            _dbg["total_score"] += 1; continue
        
        _dbg["passed"] += 1
        
        # 信号分级
        # 强烈低吸：≥55分 + 机构净买 + 估值原始分≥7（二季报窗口强化基本面约束）
        if s_total >= 55 and inst_net_3d > 0 and s_val >= 7:
            label = "强烈低吸"
            badge_class = "badge-lowbuy-strong"
        elif s_total >= 40:
            label = "标准低吸"
            badge_class = "badge-lowbuy-mild"
        else:
            label = "谨慎低吸"
            badge_class = "badge-lowbuy-mild"
        
        chg_10d = kline_chg_10d if kline_chg_10d is not None else float(row.get('涨跌幅_20d', 0) or 0)
        sec_name = _classify_stock_sector(code, row.get('名称', ''), sector_data, stock_sector_map) or '其他'
        summary = f"10日跌{chg_10d:.1f}% | 综合{s_total}分 | 机构3日净买{inst_net_3d:.0f}万"
        # 谨慎低吸 + 估值维度弱 → 单只仓位上限压缩至2成
        if label == "谨慎低吸" and s_val <= 5:
            summary += " | 限仓2成"
        
        results.append({
            "代码": code,
            "名称": row.get('名称', ''),
            "板块": sec_name,
            "最新价": row.get('最新价', 0),
            "涨跌幅": row.get('涨跌幅', 0),
            "信号强度": s_total,
            "信号": label,
            "信号类": badge_class,
            "分析摘要": summary,
            "综合评分": s_total,
            "下跌幅度": s_decline,
            "企稳信号": s_stabil,
            "量能恢复": s_vol_rec,
            "均线支撑": s_ma,
            "估值吸引": s_val,
            "筹码沉淀": s_chip,
            "主力资金": s_fund,
            "_raw": {"s1": s_decline, "s2": s_stabil, "s3": s_vol_rec, 
                     "s4": s_ma, "s5": s_val, "s6": s_chip, "s7": s_fund,
                     "inst_net_3d": inst_net_3d, "chg_10d": chg_10d, "sec_name": sec_name},
            "龙虎榜": inst_net_3d,
            "换手率": row.get('换手率', 0),
            "量比": row.get('量比', 0),
            "成交额": row.get('成交额', 0),
            "20日涨幅": f"{chg_10d:+.1f}%",
        })
        
        if len(results) >= 50:
            break
    
    sink.on_progress(total, total, "低吸筛选完成")
    
    if not results:
        return pd.DataFrame()
    
    result_df = _apply_lowbuy_percentile_normalization(results, lowbuy_weights)
    
    result_df = result_df.sort_values('综合评分', ascending=False).head(50)
    result_df['涨跌幅_显示'] = result_df['涨跌幅'].apply(lambda x: f"{x:+.2f}%")
    result_df['换手率_显示'] = result_df['换手率'].apply(lambda x: f"{x:.1f}%" if pd.notna(x) else "N/A")
    result_df['量比_显示'] = result_df['量比'].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")
    
    return result_df.reset_index(drop=True)


def _apply_lowbuy_percentile_normalization(results, lowbuy_weights):
    """对低吸结果做百分位归一化 + 加权总分 + 信号分级"""
    if lowbuy_weights is None:
        lowbuy_weights = DEFAULT_LOWBUY_WEIGHTS
    n_res = len(results)
    if n_res > 1:
        def _pct_norm_vals(vals, full_score):
            arr = np.array(vals, dtype=float)
            if np.all(arr == arr[0]):
                return np.full_like(arr, full_score * 0.5)
            ranks = np.argsort(np.argsort(arr)) + 1
            return (ranks / n_res * full_score).clip(0, full_score)
        
        s1_arr = _pct_norm_vals([r["_raw"]["s1"] for r in results], 30)
        s2_arr = _pct_norm_vals([r["_raw"]["s2"] for r in results], 25)
        s3_arr = _pct_norm_vals([r["_raw"]["s3"] for r in results], 20)
        s4_arr = _pct_norm_vals([r["_raw"]["s4"] for r in results], 15)
        s5_arr = _pct_norm_vals([r["_raw"]["s5"] for r in results], 10)
        s6_arr = _pct_norm_vals([r["_raw"]["s6"] for r in results], 10)
        s7_arr = _pct_norm_vals([r["_raw"]["s7"] for r in results], 10)
        
        weights = lowbuy_weights
        w1, w2, w3 = weights.get("下跌幅度", 23), weights.get("企稳信号", 18), weights.get("量能恢复", 14)
        w4, w5, w6 = weights.get("均线支撑", 14), weights.get("估值吸引", 14), weights.get("筹码沉淀", 9)
        w7 = weights.get("主力资金", 8)
        
        for i, r in enumerate(results):
            n1 = s1_arr[i] / 30 * 100
            n2 = s2_arr[i] / 25 * 100
            n3 = s3_arr[i] / 20 * 100
            n4 = s4_arr[i] / 15 * 100
            n5 = s5_arr[i] / 10 * 100
            n6 = s6_arr[i] / 10 * 100
            n7 = s7_arr[i] / 10 * 100
            total_n = int(n1 * w1/100 + n2 * w2/100 + n3 * w3/100 + n4 * w4/100 + n5 * w5/100 + n6 * w6/100 + n7 * w7/100)
            
            r["综合评分"] = total_n
            r["信号强度"] = total_n
            r["下跌幅度"] = int(s1_arr[i])
            r["企稳信号"] = int(s2_arr[i])
            r["量能恢复"] = int(s3_arr[i])
            r["均线支撑"] = int(s4_arr[i])
            r["估值吸引"] = int(s5_arr[i])
            r["筹码沉淀"] = int(s6_arr[i])
            r["主力资金"] = int(s7_arr[i])
            
            inst_net_3d = r["_raw"]["inst_net_3d"]
            if total_n >= 55 and inst_net_3d > 0:
                r["信号"] = "强烈低吸"
                r["信号类"] = "badge-lowbuy-strong"
            elif total_n >= 40:
                r["信号"] = "标准低吸"
                r["信号类"] = "badge-lowbuy-mild"
            else:
                r["信号"] = "谨慎低吸"
                r["信号类"] = "badge-lowbuy-mild"
            r["分析摘要"] = f"10日跌{r['_raw']['chg_10d']:.1f}% | 综合{total_n}分 | 机构3日净买{inst_net_3d:.0f}万"
    
    result_df = pd.DataFrame(results)
    return result_df
    
    result_df['涨跌幅_显示'] = result_df['涨跌幅'].apply(lambda x: f"{x:+.2f}%")
    result_df['换手率_显示'] = result_df['换手率'].apply(lambda x: f"{x:.1f}%" if pd.notna(x) else "N/A")
    result_df['量比_显示'] = result_df['量比'].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")
    
    return result_df.reset_index(drop=True)

def _get_sector(code):
    """根据代码判断板块"""
    if code.startswith('688'):
        return '科创板'
    elif code.startswith('6'):
        return '主板'
    elif code.startswith('000') or code.startswith('001'):
        return '主板'
    elif code.startswith('002'):
        return '中小板'
    elif code.startswith('300'):
        return '创业板'
    elif code.startswith('8') or code.startswith('4'):
        return '北交所'
    return '其他'

def get_stock_pool_chase_high(sample_source="全市场A股", sink=None, weights=None):
    """追高模型股票池"""
    if sink is None:
        sink = NullSink()
    if weights is None:
        weights = DEFAULT_WEIGHTS
    """追高模型股票池"""
    df_raw = fetch_all_a_stocks()
    if df_raw is None:
        return pd.DataFrame()
    
    # 🌟 样本来源过滤
    if sample_source == "热门板块":
        hot_codes = get_hot_concept_stocks(6)
        if hot_codes:
            df_raw['代码'] = df_raw['代码'].astype(str).str.zfill(6)
            df_raw = df_raw[df_raw['代码'].isin(hot_codes)]
        else:
            sink.on_warning("未能获取热门板块数据，回退为全市场扫描")
    elif sample_source == "量价":
        vp_codes = get_volprice_sectors(6)
        if vp_codes:
            df_raw['代码'] = df_raw['代码'].astype(str).str.zfill(6)
            df_raw = df_raw[df_raw['代码'].isin(vp_codes)]
        else:
            sink.on_warning("未能获取量价反转板块数据，回退为全市场扫描")
    
    # state updates delegated to caller
    
    df = preprocess_stock_data(df_raw)
    if df is None or len(df) == 0:
        return pd.DataFrame()
    
    # raw_stock_data delegated to caller
    
    # 批量计算涨跌幅
    df['涨跌幅'] = pd.to_numeric(df['涨跌幅'], errors='coerce').fillna(0)
    df = df[df['涨跌幅'] < 20]  # v5: pre-filter daily gain < 20%

    # 防御性补列：pytdx 不提供量比/换手率/市盈率/市净率，akshare 也不保证一定有
    for _col, _default in [('量比', 1), ('换手率', 0), ('市盈率-动态', None), ('市净率', None)]:
        if _col in df.columns:
            if _default is None:
                df[_col] = pd.to_numeric(df[_col], errors='coerce')  # 保留 NaN，显示为 N/A
            else:
                df[_col] = pd.to_numeric(df[_col], errors='coerce').fillna(_default)
        else:
            df[_col] = float(_default) if _default is not None else np.nan
    
    df['初筛分'] = (
        df['涨跌幅'].clip(-10, 10) * 3 +
        df['量比'].clip(0, 4) * 5 +
        (100 - df['换手率'].clip(0, 15)) * 0.5
    )
    df = df.sort_values('初筛分', ascending=False).reset_index(drop=True)
    
    # 计算历史涨跌幅（前500只）
    top500_codes = df.head(200)['代码'].tolist()  # 优化：200只足够覆盖Top30展示
    price_changes = {}
    sink.on_progress(0, len(top500_codes), "计算涨跌幅数据...")
    
    def _fetch_kline_pc(code):
        kline = get_stock_kline(code, days=80)
        if kline is not None and len(kline) >= 4:
            pc = {
                3: round((kline['收盘'].iloc[-1] / kline['收盘'].iloc[-4] - 1) * 100, 2) if len(kline) >= 4 else None,
                5: round((kline['收盘'].iloc[-1] / kline['收盘'].iloc[-6] - 1) * 100, 2) if len(kline) >= 6 else None,
                10: round((kline['收盘'].iloc[-1] / kline['收盘'].iloc[-11] - 1) * 100, 2) if len(kline) >= 11 else None,
                20: round((kline['收盘'].iloc[-1] / kline['收盘'].iloc[-21] - 1) * 100, 2) if len(kline) >= 21 else None,
            }
            pc['_kline'] = kline
            return code, pc
        return code, None

    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(_fetch_kline_pc, code) for code in top500_codes]
        done_count = 0
        for future in as_completed(futures):
            done_count += 1
            if done_count % 50 == 0:
                sink.on_progress(done_count, len(top500_codes), f"计算涨跌幅数据... ({done_count}/{len(top500_codes)})")
            try:
                code, pc = future.result(timeout=15)
                if pc is not None:
                    price_changes[code] = pc
            except Exception:
                pass
    
    sink.on_progress(total, total, "低吸筛选完成")
    
    df['涨跌幅_3d'] = df['代码'].map(lambda x: price_changes.get(x, {}).get(3, None))
    df['涨跌幅_5d'] = df['代码'].map(lambda x: price_changes.get(x, {}).get(5, None))
    df['涨跌幅_10d'] = df['代码'].map(lambda x: price_changes.get(x, {}).get(10, None))
    df['涨跌幅_20d'] = df['代码'].map(lambda x: price_changes.get(x, {}).get(20, None))
    df['涨跌幅_3d'] = df['涨跌幅_3d'].fillna(df['涨跌幅'] * 2)
    df['涨跌幅_5d'] = df['涨跌幅_5d'].fillna(df['涨跌幅'] * 3)
    df['涨跌幅_10d'] = df['涨跌幅_10d'].fillna(df['涨跌幅'] * 5)
    df['涨跌幅_20d'] = df['涨跌幅_20d'].fillna(0)  # 仅初筛排序用，显示前会重新格式化为N/A

    # 但 fillna(0) 导致显示 "+0.0%" 而非 "N/A"：覆盖显示列为真正N/A
    df['涨跌幅_20d_display'] = df['代码'].map(lambda x: price_changes.get(x, {}).get(20, None))

    df['_kline_cache'] = df['代码'].map(lambda x: price_changes.get(x, {}).get('_kline'))
    
    # 计算RSI（前200只）
    top200_codes = df.head(100)['代码'].tolist()  # 优化：100只足够
    rsi_dict = batch_calculate_rsi(top200_codes, max_count=100) or {}
    df['RSI'] = df['代码'].astype(str).map(lambda x: rsi_dict.get(x, None))  # 不再 fillna(50)
    
    # ====== v3: 获取龙虎榜+板块数据（使用模块级缓存） ======
    sink.on_status("获取龙虎榜+板块数据...")
    lhb_data = _get_cached_dragon_tiger()
    sector_data, stock_sector_map = _get_cached_sector_data()
    sink.on_status("")

    # ====== v3八维评分 ======
    score_results = []
    for idx, row in df.iterrows():
        sd = _build_stock_data(row, row.get('_kline_cache'), lhb_data, sector_data, stock_sector_map)
        result = calculate_v3_total_score(sd)
        result['代码'] = row['代码']
        result['position_msg'] = result.get('position_msg', '')
        score_results.append(result)

    score_df = pd.DataFrame(score_results)

    # ====== P1: 六维百分位归一化（追高模型）— v2 N/A感知版 ======
    score_df, df = _apply_chase_percentile_normalization(score_df, df, score_results, weights)

    for col in ['趋势结构', '动量强度', '板块共振', '北向资金', '机构净买', '板块资金热度',
                '量价配合', '估值安全', '筹码稳定', '情绪热度', '综合评分', 'position_msg']:
        if col in score_df.columns:
            df[col] = score_df[col]
    
    # 信号分类
    def classify(row):
        # P0修复: 追高模型信号由综合评分驱动，不再使用低吸模型的 _classify_signal
        # 与 position_msg 保持同一口径，避免 93分→"观望等待" 的矛盾
        score = row['综合评分']
        if score >= 85:
            return ("强势买入", "badge-strong", "积极关注")
        elif score >= 70:
            return ("逢低吸纳", "badge-attention", "分批布局")
        elif score >= 55:
            return ("观望等待", "badge-hold", "等待信号")
        else:
            return ("建议回避", "badge-watch", "谨慎对待")
    
    signals = df.apply(classify, axis=1)
    df['信号'] = [s[0] for s in signals]
    df['信号类'] = [s[1] for s in signals]
    df['建议'] = [s[2] for s in signals]
    
    # 格式化
    df['3日涨幅'] = df['涨跌幅_3d'].apply(lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A")
    df['5日涨幅'] = df['涨跌幅_5d'].apply(lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A")
    df['10日涨幅'] = df['涨跌幅_10d'].apply(lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A")
    df['20日涨幅'] = df['涨跌幅_20d_display'].apply(lambda x: f"{x:+.1f}%" if pd.notna(x) else "N/A")
    df['换手率_显示'] = df['换手率'].apply(lambda x: f"{x:.1f}%" if pd.notna(x) else "N/A")
    df['PE_显示'] = df['市盈率-动态'].apply(lambda x: f"{x:.1f}" if pd.notna(x) and x > 0 else "N/A")
    df['PB_显示'] = df['市净率'].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")
    df['RSI_显示'] = df['RSI'].apply(lambda x: f"{x:.1f}" if pd.notna(x) else "N/A")
    df['量比_显示'] = df['量比'].apply(lambda x: f"{x:.2f}" if pd.notna(x) else "N/A")
    # 🔧 用 pytdx 概念板块映射替代代码前缀分类
    _, sector_map = fetch_sector_board_v3()
    if sector_map:
        import re
        valid_map = {k: v for k, v in sector_map.items() if re.search(r'[\u4e00-\u9fff]', v)}
        df['板块'] = df['代码'].map(valid_map).fillna('')
    else:
        df['板块'] = df['代码'].apply(_get_sector)
    
    output_cols = [
        '代码', '名称', '板块', '综合评分', '趋势结构', '动量强度', '板块共振',
        '北向资金', '机构净买', '板块资金热度', '量价配合', '估值安全', '筹码稳定', '情绪热度',
        '3日涨幅', '5日涨幅', '10日涨幅', '20日涨幅',
        '换手率_显示', '量比_显示', 'RSI_显示', 'PE_显示', 'PB_显示',
        '信号', '信号类', '建议', '最新价', '涨跌幅', 'position_msg'
    ]
    output_cols = [c for c in output_cols if c in df.columns]
    # N/A维度渲染为"N/A"（_raw 中值为-1的维度标记为数据不可用）
    _dim_na_map = {
        '趋势结构': 's1', '动量强度': 's2', '板块共振': 's3',
        '北向资金': 's4', '机构净买': 's5', '板块资金热度': 's6',
        '量价配合': 's7', '估值安全': 's8', '情绪热度': 's10'
    }
    for dim_col, raw_key in _dim_na_map.items():
        if dim_col in df.columns:
            df[dim_col] = df[dim_col].astype(object)  # 先转为object以容纳"N/A"字符串
            for i, r in enumerate(score_results):
                if r['_raw'].get(raw_key, 0) < 0:
                    df.loc[i, dim_col] = "N/A"

    if len(df) == 0 or '信号' not in df.columns:
        return pd.DataFrame(columns=['代码','名称','板块','综合评分','信号','趋势结构','动量强度','板块共振','北向资金','机构净买','板块资金热度','量价配合','估值安全','筹码稳定','情绪热度'])
    return df[output_cols].sort_values('综合评分', ascending=False).reset_index(drop=True)


def _apply_chase_percentile_normalization(score_df, df, score_results, weights):
    """追高模型 P1: 六维百分位归一化 + 动态权重重分配 + 信号分类"""
    if weights is None:
        weights = DEFAULT_WEIGHTS
    if len(score_df) <= 1:
        return score_df, df
    
    # N/A感知百分位归一化：-1值不参与排名，返回0分（不污染排名分布）
    def _pct_norm_na(arr_raw):
        arr = np.array(arr_raw, dtype=float)
        valid = arr >= 0
        result = np.zeros_like(arr)
        if not valid.any():
            return result
        valid_arr = arr[valid]
        if np.std(valid_arr) == 0:
            result[valid] = 50.0
        else:
            ranks = np.argsort(np.argsort(valid_arr)) + 1
            result[valid] = ranks / len(valid_arr) * 100
        return result
    
    def _pct_norm_ch(series):
        arr = np.array(series.values, dtype=float)
        if np.std(arr) == 0:
            return np.full_like(arr, 50.0)
        ranks = np.argsort(np.argsort(arr)) + 1
        return ranks / len(arr) * 100
    
    def _safe_arr(arr):
        return np.where(arr < 0, 0, arr)
    
    s1_arr = np.array([r['_raw'].get('s1', 0) for r in score_results], dtype=float)
    s2_arr = np.array([r['_raw'].get('s2', 0) for r in score_results], dtype=float)
    s3_arr = np.array([r['_raw'].get('s3', 0) for r in score_results], dtype=float)
    df['趋势得分_norm'] = _pct_norm_na(s1_arr)
    df['动量得分_norm'] = _pct_norm_na(s2_arr)
    df['板块共振_norm'] = _pct_norm_na(s3_arr)

    s4_raw = np.array([r['_raw'].get('s4', 0) for r in score_results], dtype=float)
    s5_raw = np.array([r['_raw'].get('s5', 0) for r in score_results], dtype=float)
    s4_norm = _pct_norm_na(s4_raw)
    s5_norm = _pct_norm_na(s5_raw)
    s45_arr = _safe_arr(s4_raw) + _safe_arr(s5_raw)
    df['资金得分_norm'] = _pct_norm_ch(pd.Series(s45_arr))
    
    s7_raw = np.array([r['_raw'].get('s7', 0) for r in score_results], dtype=float)
    s10_raw = np.array([r['_raw'].get('s10', 0) for r in score_results], dtype=float)
    df['量价得分_norm'] = _pct_norm_na(s7_raw)
    df['情绪得分_norm'] = _pct_norm_na(s10_raw)
    
    s8_raw = np.array([r['_raw'].get('s8', 0) for r in score_results], dtype=float)
    s9_raw = np.array([r['_raw'].get('s9', 0) for r in score_results], dtype=float)
    s6_raw = np.array([r['_raw'].get('s6', 0) for r in score_results], dtype=float)
    s8_arr = _safe_arr(s8_raw); s9_arr = _safe_arr(s9_raw); s6_arr = _safe_arr(s6_raw)
    s6_norm = s6_arr / 10 * 100; s8_norm = s8_arr / 10 * 100; s9_norm = s9_arr / 7 * 100
    
    W_TREND = weights.get("趋势结构", 15); W_MOM = weights.get("动量强度", 18)
    W_SEC = weights.get("板块共振", 8); W_NORTH = weights.get("北向资金", 15)
    W_INST = weights.get("机构净买", 10); W_VOL = weights.get("量价配合", 14)
    W_SENT = weights.get("情绪热度", 6); W_FUND = weights.get("板块资金热度", 5)
    W_VAL = weights.get("估值安全", 3); W_CHIP = weights.get("筹码稳定", 6)

    na_s4 = s4_raw < 0; na_s5 = s5_raw < 0; na_s6 = s6_raw < 0
    na_s7 = s7_raw < 0; na_s8 = s8_raw < 0; na_s9 = s9_raw < 0; na_s10 = s10_raw < 0

    total_arr = np.zeros(len(score_results))
    for i in range(len(score_results)):
        valid_w = W_TREND + W_MOM + W_SEC
        wsum = (df['趋势得分_norm'].iloc[i] * W_TREND +
                df['动量得分_norm'].iloc[i] * W_MOM +
                df['板块共振_norm'].iloc[i] * W_SEC)
        if not na_s4[i]: valid_w += W_NORTH; wsum += s4_norm[i] * W_NORTH
        if not na_s5[i]: valid_w += W_INST; wsum += s5_norm[i] * W_INST
        if not na_s7[i]: valid_w += W_VOL; wsum += df['量价得分_norm'].iloc[i] * W_VOL
        if not na_s10[i]: valid_w += W_SENT; wsum += df['情绪得分_norm'].iloc[i] * W_SENT
        if not na_s6[i]: valid_w += W_FUND; wsum += s6_norm[i] * W_FUND
        if not na_s8[i]: valid_w += W_VAL; wsum += s8_norm[i] * W_VAL
        if not na_s9[i]: valid_w += W_CHIP; wsum += s9_norm[i] * W_CHIP
        total_arr[i] = wsum / valid_w if valid_w > 0 else 0
    
    df['综合评分'] = total_arr.astype(int)
    for i, r in enumerate(score_results):
        new_score = int(df['综合评分'].iloc[i])
        r['综合评分'] = new_score
        if new_score >= 85: r['position_msg'] = "主线龙头，重仓60%~80%"
        elif new_score >= 70: r['position_msg'] = "支线趋势，轻仓20%~40%"
        else: r['position_msg'] = "分数不足70，放弃不参与"
        score_results[i] = r
    score_df['综合评分'] = df['综合评分'].values
    score_df['position_msg'] = [r.get('position_msg', '') for r in score_results]
    return score_df, df


def get_stock_pool(current_model=None, chase_sample_source=None):
    """获取股票池（根据当前模型）"""
    model = current_model or 'chase_high'
    sample_source = chase_sample_source or '全市场A股'
    if model == 'chase_high':
        return get_stock_pool_chase_high(sample_source)
    else:
        # 低吸模型也返回追高池用于自选股和详情查看
        return get_stock_pool_chase_high(sample_source)

def get_simulated_stock_pool(weights=None):
    """模拟数据（降级用）"""
    today = datetime.now().date()
    date_seed = int(today.strftime('%Y%m%d'))
    rng = np.random.RandomState(date_seed % 9999)
    
    sectors = ['半导体/芯片', 'AI/人工智能', '新能源/锂电', '医药/医疗', '消费电子',
               '软件/云计算', '金融/证券', '化工/材料', '机械设备', '军工/航空']
    
    data = []
    for i in range(200):
        code = f"{i+1:06d}"
        rng_i = np.random.RandomState(hash(code) % 10000 + date_seed)
        sector = sectors[i % len(sectors)]
        
        chg_5d = round(rng_i.randn() * 4 + 1, 1)
        chg_20d = round(chg_5d * 3 + rng_i.randn() * 8, 1)
        turnover = round(max(0.5, 2.5 + rng_i.randn() * 2), 1)
        vol_ratio = round(max(0.3, min(4.0, 1.0 + rng_i.randn() * 0.8)), 2)
        pe = round(max(10, min(80, 30 + rng_i.randn() * 20)), 1)
        pb = round(max(0.5, min(8, pe / 15 + rng_i.randn())), 2)
        rsi = round(max(25, min(80, 50 + rng_i.randn() * 20)), 1)
        
        momentum = int(max(30, min(90, 50 + chg_5d * 4 + rng_i.randn() * 10)))
        vol_price = int(max(30, min(90, 50 + (vol_ratio - 1) * 15 + rng_i.randn() * 10)))
        safety = int(max(30, min(90, 50 + (40 - pe) / 2 if 15 <= pe <= 60 else 30 + rng_i.randn() * 10)))
        chip = int(max(30, min(90, 50 + (5 - turnover) * 3 + rng_i.randn() * 10)))
        sentiment = int(max(25, min(90, 50 + (rsi - 50) * 0.8 + rng_i.randn() * 10)))
        trend = int(max(25, min(90, 50 + chg_20d * 2 + rng_i.randn() * 15)))
        lhb_s = int(max(25, min(90, 50 + rng_i.randn() * 20)))
        sec_s = int(max(25, min(90, 50 + rng_i.randn() * 15)))

        weights = weights
        total = int(
            momentum * weights.get("动量强度", 18)/100 + vol_price * weights.get("量价配合", 14)/100 +
            safety * weights.get("估值安全", 3)/100 + chip * weights.get("筹码稳定", 6)/100 +
            sentiment * weights.get("情绪热度", 6)/100 + trend * weights.get("趋势结构", 15)/100 +
            lhb_s * weights.get("北向资金", 15)/100 + lhb_s * weights.get("机构净买", 10)/100 +
            lhb_s * weights.get("板块资金热度", 5)/100 + sec_s * weights.get("板块共振", 8)/100
        )
        
        signal, sig_cls, advice = _classify_signal(total, chg_5d, rsi, safety, momentum)
        
        data.append({
            "代码": code, "名称": f"模拟股票{i+1:03d}", "板块": sector,
            "综合评分": total, "动量强度": momentum, "量价配合": vol_price,
            "估值安全": safety, "筹码稳定": chip, "情绪热度": sentiment,
            "趋势结构": trend, "北向资金": lhb_s, "机构净买": lhb_s,
            "板块资金热度": lhb_s, "板块共振": sec_s,
            "3日涨幅": f"{round(chg_5d*0.6,1):+.1f}%", "5日涨幅": f"{chg_5d:+.1f}%",
            "10日涨幅": f"{round(chg_5d*1.8,1):+.1f}%", "20日涨幅": f"{chg_20d:+.1f}%",
            "换手率_显示": f"{turnover:.1f}%", "量比_显示": vol_ratio,
            "RSI_显示": f"{rsi:.1f}", "PE_显示": f"{pe:.1f}", "PB_显示": f"{pb:.2f}",
            "信号": signal, "信号类": sig_cls, "建议": advice,
            "最新价": round(10 + rng.rand() * 50, 2), "涨跌幅": chg_5d
        })
    
    return pd.DataFrame(data).sort_values("综合评分", ascending=False).reset_index(drop=True)

def get_stock_detail(code):
    df = get_stock_pool()
    r = df[df["代码"] == code]
    return None if len(r) == 0 else r.iloc[0].to_dict()

def _find_stock_row(code, silent=False):
    """个股股票查找，带多级兜底。
    
    与 fetch_all_a_stocks() 不同：本函数绕过模块级缓存，在 fetch_all_a_stocks()
    返回缓存的残缺数据时，直接调用 akshare 获取全量行情来匹配。
    
    Args:
        code: 6位股票代码字符串
        silent: True 时不打印 st.warning，仅返回结果
    
    Returns:
        (row_dict_or_None, df_raw_or_None)
    """
    code = str(code).strip().zfill(6)
    
    # 第一级：fetch_all_a_stocks（有可能是过期缓存）
    df_raw = fetch_all_a_stocks()
    if df_raw is not None and len(df_raw) > 0:
        df_raw['代码'] = df_raw['代码'].astype(str).str.zfill(6)
        match = df_raw[df_raw['代码'] == code]
        if len(match) > 0:
            return match.iloc[0].to_dict(), df_raw
    
    # 第二级：直接调用 akshare（绕过 pytdx 阻塞和模块级缓存）
    if AKSHARE_AVAILABLE:
        try:
            import threading
            _ak_result = [None]
            def _fetch():
                try:
                    _ak_result[0] = ak.stock_zh_a_spot_em()
                except Exception:
                    pass
            _t = threading.Thread(target=_fetch, daemon=True)
            _t.start()
            _t.join(timeout=10)
            df_em = _ak_result[0]
            if df_em is not None and len(df_em) > 0:
                df_em['代码'] = df_em['代码'].astype(str).str.zfill(6)
                match = df_em[df_em['代码'] == code]
                if len(match) > 0:
                    row = match.iloc[0]
                    result = {k: row[k] for k in row.index}
                    # 尝试更新模块级缓存
                    try:
                        if len(df_em) > 1000:
                            _app_cache['raw_market_data'] = df_em
                            _app_cache['raw_market_time'] = time.time()
                    except Exception:
                        pass
                    return result, df_em
        except Exception:
            pass
    
    # 第三级：从本地缓存文件反查（可能比模块级缓存的版本更新）
    try:
        cache_path = os.path.join(BASE_DIR, 'market_data_cache.json')
        if os.path.exists(cache_path):
            with open(cache_path, 'r', encoding='utf-8') as f:
                cached = json.load(f)
            if cached and 'data' in cached and len(cached['data']) > 0:
                df_cache = pd.DataFrame(cached['data'])
                df_cache['代码'] = df_cache['代码'].astype(str).str.zfill(6)
                match = df_cache[df_cache['代码'] == code]
                if len(match) > 0:
                    return match.iloc[0].to_dict(), df_cache
    except Exception:
        pass
    
    return None, None

def score_single_stock(code, model):
    """个股评分：对单只股票在指定模型下计算各维度分值和总分。
    
    Args:
        code: 6位股票代码字符串
        model: 'chase_high' | 'buy_low' | 'golden_cross' | 'resonance' | 'canslim' | 'dilemma_reversal'
    
    Returns:
        dict: {'success': bool, 'model': str, 'name': str, 'close': float, 'chg': float,
               'dims': {维度名: 分值}, 'total': int, 'pass': bool, 'max_score': int,
               以及可选的 'error', 'signal', 'position_msg', 'filter_msg'}
    """
    try:
        kline250 = get_stock_kline(code, days=250)
        kline60 = get_stock_kline(code, days=60) if model != 'resonance' else None
        
        row_dict, df_raw = _find_stock_row(code)
        if row_dict is None:
            return {"success": False, "error": f"未找到股票代码 {code}"}
        row = pd.Series(row_dict).copy()
        name = str(row.get('名称', ''))
        close_val = float(row.get('最新价', 0) or 0)
        chg_val = float(row.get('涨跌幅', 0) or 0)
        
        lhb_data = _get_cached_dragon_tiger()
        sector_data, stock_sector_map = _get_cached_sector_data()
        
        # 补列
        for _col, _default in [('量比', 1), ('换手率', 0), ('市盈率-动态', 0), ('市净率', 0)]:
            if _col not in row.index:
                row[_col] = _default
            else:
                row[_col] = float(row.get(_col, _default) or 0)
        
        # K线涨跌幅（有K线就用，否则填0）
        kline_for_pc = kline250 if kline250 is not None else kline60
        if kline_for_pc is not None and len(kline_for_pc) >= 4:
            c_col = '收盘' if '收盘' in kline_for_pc.columns else 'close'
            c_arr = kline_for_pc[c_col].values.astype(float)
            n_c = len(c_arr)
            row['涨跌幅_3d'] = round((c_arr[-1] / c_arr[max(0, n_c - 4)] - 1) * 100, 2) if n_c >= 4 else 0
            row['涨跌幅_5d'] = round((c_arr[-1] / c_arr[max(0, n_c - 6)] - 1) * 100, 2) if n_c >= 6 else 0
            row['涨跌幅_10d'] = round((c_arr[-1] / c_arr[max(0, n_c - 11)] - 1) * 100, 2) if n_c >= 11 else 0
            row['涨跌幅_20d'] = round((c_arr[-1] / c_arr[max(0, n_c - 21)] - 1) * 100, 2) if n_c >= 21 else 0
        else:
            row['涨跌幅_3d'] = 0; row['涨跌幅_5d'] = 0; row['涨跌幅_10d'] = 0; row['涨跌幅_20d'] = 0
        row['RSI'] = calculate_rsi(code) or 50
        
        stock_data = _build_stock_data(row, kline250, lhb_data, sector_data, stock_sector_map)
        
        if model == 'chase_high':
            result = calculate_v3_total_score(stock_data)
            dims = {k: result.get(k, 0) for k in [
                "趋势结构","动量强度","板块共振","北向资金","机构净买",
                "板块资金热度","量价配合","估值安全","筹码稳定","情绪热度"]}
            return {"success": True, "model": "chase_high", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "position_msg": result.get("position_msg", ""), "filter_msg": result.get("filter_msg", ""),
                    "max_score": 100}
        
        elif model == 'buy_low':
            if kline60 is None or len(kline60) < 10:
                return {"success": False, "error": "K线数据不足（需要至少10日）"}
            params = _get_lowbuy_params()
            result = calculate_lowbuy_score(stock_data, kline60, params)
            dims = {k: result.get(k, 0) for k in [
                "下跌幅度","企稳信号","量能恢复","均线支撑","估值吸引","筹码沉淀","主力资金"]}
            return {"success": True, "model": "buy_low", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "max_score": 100}
        
        elif model == 'golden_cross':
            if kline60 is None or len(kline60) < 10:
                return {"success": False, "error": "K线数据不足（需要至少10日）"}
            info = {'代码': code, '名称': name}
            result = calculate_golden_cross_score(info, kline60)
            dims = {k: result.get(k, 0) for k in [
                "下跌形态","K线止跌","均线拐头","量能确认","MACD反转","资金确认","板块确认"]}
            return {"success": True, "model": "golden_cross", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "signal": result.get("信号", ""), "max_score": 100}
        
        elif model == 'resonance':
            quotes_df = df_raw
            if quotes_df is None:
                return {"success": False, "error": "无法获取行情数据"}
            quotes_df = quotes_df[~quotes_df['名称'].str.contains('ST|退市|N|C', na=False)]
            rd = get_resonance_data(quotes_df)
            if rd and code in rd:
                scores = calculate_resonance_score(rd, quotes_df)
                if code in scores:
                    sc = scores[code]
                    dims = {
                        "资金流向": sc.get('money_flow', 0),
                        "DDE决策": sc.get('dde_proxy', 0),
                        "K线结构": sc.get('kline_structure', 0),
                        "板块热度": sc.get('sector_heat', 0),
                    }
                    return {"success": True, "model": "resonance", "name": name, "close": close_val, "chg": chg_val,
                            "dims": dims, "total": sc.get('total', 0), "pass": True, "max_score": 100}
            return {"success": False, "error": "共振数据未覆盖该股票（需全市场扫描）"}
        
        elif model == 'canslim':
            if kline250 is None or len(kline250) < 60:
                return {"success": False, "error": "K线数据不足（需要至少60日）"}
            fin_data = get_financial_data(code)
            spot = get_all_spot_data()
            market_cap_raw = (spot.get(code, {}).get("总市值", 0) or 0) * 1e8 if spot else 0
            turnover_raw = spot.get(code, {}).get("换手率", 0) if spot else 0
            ctx = {'fin': fin_data, 'market_cap': market_cap_raw, 'turnover_rate': turnover_raw, 'rps': 50}
            result = calculate_canslim_score(code, kline250, ctx)
            dims = {k: result.get(k, 0) for k in [
                "C_业绩增速","A_持续增长","N_新催化","S_中小盘","L_RPS","I_流动性","M_大势"]}
            return {"success": True, "model": "canslim", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "max_score": 100}
        
        elif model == 'dilemma_reversal':
            if kline250 is None or len(kline250) < 60:
                return {"success": False, "error": "K线数据不足（需要至少60日）"}
            fin_data = get_financial_data(code)
            ctx = {'fin': fin_data}
            result = calculate_dilemma_reversal_score(code, kline250, ctx)
            dims = {k: result.get(k, 0) for k in ["L1_拐点","L2_反转","L3_安全垫","L4_技术资金"]}
            return {"success": True, "model": "dilemma_reversal", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "max_score": 100}
        
        elif model == 'oversold_rebound':
            if kline250 is None or len(kline250) < 60:
                return {"success": False, "error": "K线数据不足（需要至少60日）"}
            ok, filter_msg = hard_filter_oversold_rebound(kline250, stock_data)
            if not ok:
                return {"success": True, "model": "oversold_rebound", "name": name,
                        "close": close_val, "chg": chg_val, "dims": {},
                        "total": 0, "pass": False, "filter_msg": filter_msg, "max_score": 110}
            result = calculate_oversold_rebound_score(kline250, stock_data)
            dims = {k: result.get(k, 0) for k in ["空间维度","情绪量能","择时确认","板块共振"]}
            return {"success": True, "model": "oversold_rebound", "name": name, "close": close_val, "chg": chg_val,
                    "dims": dims, "total": result.get("综合评分", 0), "pass": result.get("pass", False),
                    "max_score": 110}
        
    except Exception as e:
        import traceback
        return {"success": False, "error": str(e), "traceback": traceback.format_exc(), "model": model}
    return {"success": False, "error": f"未知模型: {model}"}

def get_top10_stocks(app_state=None):
    from core.protocols import NullSink
    sink = NullSink()
    """追高模型：动态推荐数量（根据市场状态自动调整）"""
    today = datetime.now().strftime('%Y%m%d')
    weights = (app_state.weights if app_state else DEFAULT_WEIGHTS)
    w_str = '_'.join(f"{k}{v}" for k, v in sorted(weights.items()))
    cache_key = f"top10_{today}_{w_str}"
    if app_state is None or app_state.top10_cache_key != cache_key or app_state.top10_cache is None:
        df = get_stock_pool()
        dyn_n = calculate_dynamic_recommend_count()
        top_n = df.head(dyn_n).copy()
        if app_state:
            app_state.top10_cache = top_n.to_dict('records')
            app_state.top10_cache_key = cache_key
            app_state._chase_dynamic_n = dyn_n
        # 保存到文件缓存
        save_cache_data({
            'chase_high_top10': app_state.top10_cache if app_state else [],
            'lowbuy_top5': app_state.lowbuy_cache if app_state else None,
            'lowbuy_dbg': app_state._lb_dbg if app_state else {},
        })
    return app_state.top10_cache or [] if app_state else []

def get_lowbuy_top5(df_market=None):
    """低吸模型：Top5"""
    if df_market is None:
        df_raw = fetch_all_a_stocks()
        if df_raw is None:
            return pd.DataFrame()
        df_market = preprocess_stock_data(df_raw)
    
    params = _get_lowbuy_params()
    return screen_low_buy_stocks(df_market, params)

from functools import lru_cache

@lru_cache(maxsize=1024)
def calculate_rsi(code, period=14):
    """计算个股RSI指标"""
    df = get_stock_kline(code, days=120)
    if df is None or len(df) < period + 1:
        return None
    delta = df['收盘'].diff()
    gain = delta.copy()
    loss = delta.copy()
    gain[gain < 0] = 0
    loss[loss > 0] = 0
    loss = abs(loss)
    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()
    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return round(rsi.iloc[-1], 1) if not pd.isna(rsi.iloc[-1]) else None

def batch_calculate_rsi(codes, max_count=300, sink=None):
    if sink is None:
        sink = NullSink()
    """批量计算RSI（多线程并行）"""
    rsi_dict = {}
    codes_to_calc = codes[:max_count]
    sink.on_progress(0, len(codes_to_calc), "计算RSI...")
    
    def _calc_one_rsi(code):
        return code, calculate_rsi(code)
    
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = [executor.submit(_calc_one_rsi, code) for code in codes_to_calc]
        done_count = 0
        for future in as_completed(futures):
            done_count += 1
            if done_count % 30 == 0:
                sink.on_progress(done_count, len(codes_to_calc), f"计算RSI... ({done_count}/{len(codes_to_calc)})")
            try:
                code, rsi = future.result(timeout=15)
                if rsi is not None:
                    rsi_dict[code] = rsi
            except Exception:
                pass
    
    sink.on_progress(total, total, "低吸筛选完成")
    return rsi_dict
