"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
def create_candlestick_chart(kline_df, title="", is_realtime=False):
    """Create candlestick chart with volume bars"""
    df = kline_df.copy()
    if len(df) == 0:
        return None
    date_col = None
    for c in df.columns:
        if c == '\u65e5\u671f' or 'date' in c.lower():
            date_col = c
            break
    if date_col is None:
        return None
    dates = pd.to_datetime(df[date_col])
    has_volume = '\u6210\u4ea4\u91cf' in df.columns
    if has_volume:
        fig = make_subplots(rows=2, cols=1, shared_xaxes=True,
                           vertical_spacing=0.03, row_heights=[0.7, 0.3])
        fig.add_trace(go.Candlestick(
            x=dates, open=df['\u5f00\u76d8'], high=df['\u6700\u9ad8'],
            low=df['\u6700\u4f4e'], close=df['\u6536\u76d8'],
            increasing_line_color='#E74C3C', decreasing_line_color='#27AE60',
            increasing_fillcolor='#E74C3C', decreasing_fillcolor='#27AE60',
            name='K\u7ebf'
        ), row=1, col=1)
        vol_colors = ['#E74C3C' if df['\u6536\u76d8'].iloc[i] >= df['\u5f00\u76d8'].iloc[i] else '#27AE60'
                      for i in range(len(df))]
        if is_realtime and len(vol_colors) > 0:
            vol_colors[-1] = 'rgba(100,100,200,0.5)'
        fig.add_trace(go.Bar(
            x=dates, y=df['\u6210\u4ea4\u91cf'],
            marker_color=vol_colors, opacity=0.7, name='\u6210\u4ea4\u91cf',
            marker_line_width=0
        ), row=2, col=1)
    else:
        fig = go.Figure()
        fig.add_trace(go.Candlestick(
            x=dates, open=df['\u5f00\u76d8'], high=df['\u6700\u9ad8'],
            low=df['\u6700\u4f4e'], close=df['\u6536\u76d8'],
            increasing_line_color='#E74C3C', decreasing_line_color='#27AE60',
            increasing_fillcolor='#E74C3C', decreasing_fillcolor='#27AE60',
            name='K\u7ebf'
        ))
    if is_realtime:
        last_idx = len(dates) - 1
        fig.add_annotation(
            x=dates.iloc[last_idx], y=df['\u6700\u9ad8'].iloc[last_idx],
            text='\u25b6 \u672a\u6536\u76d8', showarrow=False,
            font=dict(size=10, color='#C4842D'),
            yshift=12, row=1, col=1
        )
    fig.update_layout(
        height=500 if has_volume else 350,
        paper_bgcolor='white', plot_bgcolor='rgba(250,249,245,0.5)',
        xaxis_rangeslider_visible=False,
        title_text=title if title else '',
        margin=dict(t=50, b=20, l=50, r=20),
        showlegend=False,
    )
    if has_volume:
        fig.update_yaxes(title_text='\u4ef7\u683c', row=1, col=1)
        fig.update_yaxes(title_text='\u6210\u4ea4\u91cf', row=2, col=1)
    return fig

def create_radar_chart(dim_data, weights):
    dims = list(dim_data.keys())
    vals = [dim_data.get(d, 50) for d in dims]
    fig = go.Figure()
    fig.add_trace(go.Scatterpolar(
        r=vals+[vals[0]], theta=dims+[dims[0]], fill='toself', name='当前评分',
        line_color='#C4842D', fillcolor='rgba(196,132,45,0.18)', line=dict(width=2.5)))
    fig.update_layout(polar=dict(radialaxis=dict(visible=True, range=[0,100],
        tickvals=[20,40,60,80,100], tickfont=dict(size=10,color='#AAA'),
        gridcolor='#EEE', linecolor='#DDD'),
        angularaxis=dict(tickfont=dict(size=13,color='#444'), gridcolor='#F0EDE8',
        linecolor='#DDD', direction='clockwise', rotation=90), bgcolor='rgba(0,0,0,0)'),
        showlegend=True, legend=dict(orientation='h', yanchor='bottom', y=-0.12, xanchor='center', x=0.5),
        margin=dict(t=40,b=80,l=60,r=60), height=420,
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    return fig

def create_backtest_equity_chart(bt_df, metrics=None):
    fig = make_subplots(rows=3, cols=1, shared_xaxes=True,
                       vertical_spacing=0.08, row_heights=[0.45, 0.25, 0.3])
    fig.add_trace(go.Scatter(x=bt_df["日期"], y=bt_df["组合净值"],
        mode='lines', line=dict(color='#C4842D', width=2.5),
        fill='tozeroy', fillcolor='rgba(196,132,45,0.08)', name='策略净值'), row=1, col=1)
    fig.add_trace(go.Scatter(x=bt_df["日期"], y=bt_df["基准净值"],
        mode='lines', line=dict(color='#666', width=1.5, dash='dot'), name='沪深300基准'), row=1, col=1)
    colors = ['#E74C3C' if r >= 0 else '#27AE60' for r in bt_df["日收益率"]]
    fig.add_trace(go.Bar(x=bt_df["日期"], y=bt_df["日收益率"]*100,
        marker_color=colors, opacity=0.7, name='日收益率(%)', marker_line_width=0), row=2, col=1)
    fig.add_trace(go.Scatter(x=bt_df["日期"], y=-bt_df["最大回撤"]*100,
        mode='lines', fill='tozeroy', line=dict(color='#E74C3C', width=1.5),
        fillcolor='rgba(231,76,60,0.15)', name='回撤(%)'), row=3, col=1)
    fig.update_yaxes(title_text="净值(元)", row=1, col=1)
    fig.update_yaxes(title_text="收益率(%)", row=2, col=1)
    fig.update_yaxes(title_text="回撤(%)", row=3, col=1)
    m = metrics or {}
    title_text = ""
    if m.get("cumret_raw") is not None:
        cr = m["cumret_raw"]
        clr = "#E74C3C" if cr >= 0 else "#27AE60"
        title_text = f"累计收益: <span style='color:{clr};font-weight:700'>{cr*100:+.1f}%</span>"
    fig.update_layout(height=680, showlegend=True, legend=dict(orientation='h', y=-0.02),
        paper_bgcolor='white', plot_bgcolor='rgba(250,249,245,0.5)',
        title_text=title_text if title_text else "")
    return fig

def create_monthly_heatmap(bt_df):
    df = bt_df.copy()
    df["日期"] = pd.to_datetime(df["日期"])
    df['year'] = df['日期'].dt.year; df['month'] = df['日期'].dt.month
    monthly_pnl = df.groupby(['year','month']).apply(
        lambda g: (g["组合净值"].iloc[-1] / g["组合净值"].iloc[0] - 1) * 100 if len(g) > 1 else 0
    ).reset_index(name='ret')
    pivot = monthly_pnl.pivot(index='month', columns='year', values='ret')
    months_cn = ['', '1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
    pivot.index = [months_cn[m] for m in pivot.index]
    fig = go.Figure(data=go.Heatmap(
        z=pivot.values, x=[str(y) for y in pivot.columns], y=pivot.index,
        text=[[f'{v:.1f}%' if not np.isnan(v) else '' for v in row] for row in pivot.values],
        texttemplate='%{text}', textfont=dict(size=10),
        colorscale=[[0,'#27AE60'], [0.5,'white'], [1,'#E74C3C']],
        zmin=-15, zmax=15, hoverongaps=False, showscale=True,
        colorbar=dict(title='收益率%', thickness=10, len=0.85)))
    fig.update_layout(height=320, paper_bgcolor='white', plot_bgcolor='white',
        xaxis=dict(side='top'), margin=dict(l=50,r=30,t=30,b=20))
    return fig

def create_score_bar(score, width=120):
    color = '#E74C3C' if score >= 70 else '#E67E22' if score >= 50 else '#27AE60'
    return f"""<div style="display:flex;align-items:center;gap:8px;">
<div class="score-bar" style="width:{width}px;"><div class="score-fill" style="width:{score}%;background:{color};"></div></div>
<span style="font-weight:700;font-size:14px;color:#333;min-width:28px;">{score}</span></div>"""
