"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import BASE_DIR, CACHE_DATA_JSON, DEFAULT_GC_PARAMS, DEFAULT_GC_WEIGHTS, DEFAULT_LOWBUY_PARAMS, DEFAULT_ORB_PARAMS, DEFAULT_ORB_WEIGHTS, DEFAULT_WEIGHTS, LOWBUY_WEIGHT_CONFIG, ORB_WEIGHT_CONFIG, SCORE_TIERS, TDX_AVAILABLE, WATCHLIST_JSON, WEIGHT_CONFIG, _app_cache
from core.config import AKSHARE_AVAILABLE
from data.tdx_provider import tdx_available
from core.scoring.chase_high import calculate_v3_total_score, _build_stock_data
from core.scoring.lowbuy import calculate_lowbuy_score, _check_low_buy_conditions, _get_lowbuy_params
from core.scoring.golden_cross import calculate_golden_cross_score
from core.scoring.canslim import calculate_canslim_score
from core.scoring.dilemma import calculate_dilemma_reversal_score
from core.scoring.oversold import calculate_oversold_rebound_score
from core.scoring.resonance import get_dde_confirmation_scores, calculate_resonance_score, _classify_resonance_style
from core.screener import get_stock_pool, get_top10_stocks, get_lowbuy_top5, score_single_stock, _find_stock_row, get_stock_detail, screen_low_buy_stocks
from data.market import get_stock_kline, get_kline_with_today, fetch_all_a_stocks, calculate_dynamic_recommend_count
from data.cache import load_watchlist, save_watchlist, save_cache_data
from app.charts import create_candlestick_chart, create_radar_chart, create_backtest_equity_chart, create_monthly_heatmap, create_score_bar

def render_top_params_panel():
    """页面顶部的可折叠参数调整面板"""
    model = st.session_state.current_model
    
    if model == 'chase_high':
        _render_chase_high_params(prefix="")
    elif model == 'canslim':
        _render_chase_high_params(prefix="cs_")
    elif model == 'dilemma_reversal':
        _render_chase_high_params(prefix="dr_")
    elif model == 'oversold_rebound':
        _render_orb_params()
    elif model == 'rebound_model':
        _render_gc_params()
    else:
        _render_lowbuy_params(model)

def _render_chase_high_params(prefix=""):
    """追高模型参数面板（prefix 用于避免多 Tab 渲染时的 key 冲突）"""
    with st.expander("⚙️ 追高模型 · 十维权重设置(v4)", expanded=False):
        st.markdown("""
        <table class="weight-table">
          <tr><th>维度</th><th>指标依据</th><th>默认</th><th>范围</th></tr>
          <tr><td><b>📐 趋势结构</b></td><td>MA5/10/20/60多头</td><td><b>15%</b></td><td><span class="range-badge">0~35%</span></td></tr>
          <tr><td><b>🚀 动量强度</b></td><td>5日+10日涨幅</td><td><b>18%</b></td><td><span class="range-badge">0~35%</span></td></tr>
          <tr><td><b>🌐 板块共振</b></td><td>板块涨幅/涨停/资金流</td><td><b>8%</b></td><td><span class="range-badge">0~25%</span></td></tr>
          <tr><td><b>👆 北向资金</b></td><td>北向资金近3日净买</td><td><b>15%</b></td><td><span class="range-badge">0~25%</span></td></tr>
          <tr><td><b>🏦 机构净买</b></td><td>机构3日净买额</td><td><b>10%</b></td><td><span class="range-badge">0~25%</span></td></tr>
          <tr><td><b>🔥 板块资金热度</b></td><td>板块资金排名映射</td><td><b>5%</b></td><td><span class="range-badge">0~15%</span></td></tr>
          <tr><td><b>📈 量价配合</b></td><td>量比/振幅/缩量新高</td><td><b>14%</b></td><td><span class="range-badge">0~30%</span></td></tr>
          <tr><td><b>🛡️ 估值安全</b></td><td>PE历史分位(赛道差异化)</td><td><b>3%</b></td><td><span class="range-badge">0~25%</span></td></tr>
          <tr><td><b>🔒 筹码稳定</b></td><td>换手率接力</td><td><b>6%</b></td><td><span class="range-badge">0~20%</span></td></tr>
          <tr><td><b>🎯 情绪热度</b></td><td>热度分(主线/冷门差异化)</td><td><b>6%</b></td><td><span class="range-badge">0~15%</span></td></tr>
        </table>
        """, unsafe_allow_html=True)
        
        # +/- 按钮式权重调整（每次点击改动1%）
        _items = list(WEIGHT_CONFIG.items())
        # 处理 +/- 按钮点击
        for dim, cfg in _items:
            if st.session_state.get(f"{prefix}_winc_{dim}", False):
                cur = st.session_state.weights.get(dim, cfg["default"])
                st.session_state.weights[dim] = min(cfg["max"], cur + 1)
                st.session_state[f"{prefix}_winc_{dim}"] = False
            if st.session_state.get(f"{prefix}_wdec_{dim}", False):
                cur = st.session_state.weights.get(dim, cfg["default"])
                st.session_state.weights[dim] = max(0, cur - 1)
                st.session_state[f"{prefix}_wdec_{dim}"] = False
        # 渲染权重行
        total_w = sum(st.session_state.weights.get(dim, cfg["default"]) for dim, cfg in _items)
        for dim, cfg in _items:
            cur = st.session_state.weights.get(dim, cfg["default"])
            clr = cfg.get("color", "#333")
            bc1, bc2, bc3, bc4, bc5 = st.columns([0.6, 2.5, 0.8, 0.6, 1.2])
            with bc1:
                st.markdown(f"<span style='color:{clr};font-size:13px;'>{cfg['icon']}</span>", unsafe_allow_html=True)
            with bc2:
                st.markdown(f"<span style='font-size:13px;color:#333;font-weight:600;'>{dim}</span>", unsafe_allow_html=True)
            with bc3:
                if st.button("−", key=f"{prefix}wdec_{dim}", help=f"减少1%（当前{cur}%）"):
                    st.session_state[f"{prefix}_wdec_{dim}"] = True
                    st.rerun()
            with bc4:
                st.markdown(f"<span style='font-size:16px;font-weight:800;color:{clr};'>{cur}%</span>", unsafe_allow_html=True)
            with bc5:
                if st.button("+", key=f"{prefix}winc_{dim}", help=f"增加1%（当前{cur}%，上限{cfg['max']}%）"):
                    st.session_state[f"{prefix}_winc_{dim}"] = True
                    st.rerun()
        
        wc = "#27AE60" if total_w == 100 else "#E74C3C"
        st.markdown(f"<span style='font-size:14px;color:{wc};font-weight:700;'>总权重: {total_w}% {'✅' if total_w==100 else '⚠️ 建议100%'}</span>", unsafe_allow_html=True)
        c2, c3 = st.columns(2)
        with c2:
            if st.button("✅ 应用权重", width='stretch', type="primary", key=f"{prefix}chase_apply_weights"):
                st.cache_data.clear()
                st.rerun()
        with c3:
            if st.button("🔄 重置默认", width='stretch', key=f"{prefix}chase_reset_weights"):
                st.session_state.weights = dict(DEFAULT_WEIGHTS)
                st.session_state.top10_cache = None
                st.session_state.top10_cache_key = None
                st.cache_data.clear()
                st.rerun()

def _render_gc_params():
    """强势超跌金叉模型参数面板 — 硬过滤阈值 + 五维权重"""
    with st.expander("⚙️ 金叉模型 · 筛选规则与权重", expanded=False):
        st.markdown("""
        <table class="weight-table">
          <tr><th>维度</th><th>评分依据</th><th>默认</th><th>范围</th></tr>
          <tr><td><b>📉 下跌形态</b></td><td>回撤深度+急跌识别</td><td><b>28%</b></td><td><span class="range-badge">15~40%</span></td></tr>
          <tr><td><b>🛑 K线止跌</b></td><td>不创新低+底部K线</td><td><b>18%</b></td><td><span class="range-badge">10~35%</span></td></tr>
          <tr><td><b>📐 均线拐头</b></td><td>5日线走平+站上5日线</td><td><b>18%</b></td><td><span class="range-badge">10~35%</span></td></tr>
          <tr><td><b>📊 量能确认</b></td><td>放量倍数+缩量验证</td><td><b>13%</b></td><td><span class="range-badge">5~30%</span></td></tr>
          <tr><td><b>✂️ MACD反转</b></td><td>DIFF走平+绿柱缩短+金叉</td><td><b>13%</b></td><td><span class="range-badge">5~30%</span></td></tr>
          <tr><td><b>💰 资金确认</b></td><td>主力净流入方向/量能替代</td><td><b>10%</b></td><td><span class="range-badge">0~20%</span></td></tr>
        </table>
        """, unsafe_allow_html=True)
        
        # 硬过滤阈值
        st.markdown("**硬过滤阈值**")
        cf1, cf2, cf3 = st.columns(3)
        with cf1:
            new_rise = st.number_input("主升涨幅≥%", min_value=20, max_value=100,
                                       value=st.session_state.gc_params.get("main_rise_pct", 50),
                                       step=5, key="gc_rise_pct")
        with cf2:
            new_decline = st.number_input("回撤幅度≥%", min_value=15, max_value=60,
                                          value=st.session_state.gc_params.get("decline_pct", 30),
                                          step=5, key="gc_decline_pct")
        with cf3:
            new_vol = st.number_input("放量倍数≥", min_value=0.5, max_value=5.0,
                                      value=st.session_state.gc_params.get("volume_ratio", 1.0),
                                      step=0.1, key="gc_vol_ratio")
        
        st.markdown("**五维 → 六维权重调整**")
        dims = [
            ("下跌形态", 28, "#E74C3C"),
            ("K线止跌", 18, "#F39C12"),
            ("均线拐头", 18, "#3498DB"),
            ("量能确认", 13, "#2ECC71"),
            ("MACD反转", 13, "#9B59B6"),
            ("资金确认", 10, "#E67E22"),
        ]
        for dim_name, default_w, color in dims:
            cur = st.session_state.gc_weights.get(dim_name, default_w)
            bc1, bc2, bc3, bc4, bc5 = st.columns([0.3, 2.0, 0.6, 0.6, 1.0])
            with bc1:
                st.markdown(f"<span style='color:{color};font-size:16px;'>●</span>", unsafe_allow_html=True)
            with bc2:
                st.markdown(f"<span style='font-size:13px;color:#333;font-weight:600;'>{dim_name}</span>", unsafe_allow_html=True)
            with bc3:
                if st.button("−", key=f"gc_wdec_{dim_name}"):
                    st.session_state.gc_weights[dim_name] = max(0, cur - 1)
                    st.rerun()
            with bc4:
                st.markdown(f"<span style='font-size:16px;font-weight:800;color:{color};'>{st.session_state.gc_weights.get(dim_name, default_w)}%</span>", unsafe_allow_html=True)
            with bc5:
                if st.button("+", key=f"gc_winc_{dim_name}"):
                    st.session_state.gc_weights[dim_name] = min(40, cur + 1)
                    st.rerun()
        
        total = sum(st.session_state.gc_weights.get(d, w) for d, w, _ in dims)
        wc = "#27AE60" if total == 100 else "#E74C3C"
        st.markdown(f"<span style='font-size:14px;color:{wc};font-weight:700;'>总权重: {total}% {'✅' if total==100 else '⚠️ 建议100%'}</span>", unsafe_allow_html=True)
        
        ca1, ca2 = st.columns(2)
        with ca1:
            if st.button("✅ 应用参数", width='stretch', type="primary", key="gc_apply"):
                st.session_state.gc_params["main_rise_pct"] = new_rise
                st.session_state.gc_params["decline_pct"] = new_decline
                st.session_state.gc_params["volume_ratio"] = new_vol
                st.session_state.gc_results = None
                st.session_state.gc_scanned = False
                st.cache_data.clear()
                st.rerun()
        with ca2:
            if st.button("🔄 重置默认", width='stretch', key="gc_reset"):
                st.session_state.gc_params = dict(DEFAULT_GC_PARAMS)
                st.session_state.gc_weights = dict(DEFAULT_GC_WEIGHTS)
                st.session_state.gc_results = None
                st.session_state.gc_scanned = False
                st.cache_data.clear()
                st.rerun()

def _render_orb_params():
    """超跌反弹模型参数面板 — 四维权重设置"""
    with st.expander("⚙️ 超跌反弹模型 · 四维权重设置", expanded=False):
        st.markdown("""
        <table class="weight-table">
          <tr><th>维度</th><th>指标依据</th><th>默认</th><th>范围</th></tr>
          <tr><td><b>📉 空间维度</b></td><td>高位回调幅度 + BIAS乖离</td><td><b>40%</b></td><td><span class="range-badge">0~60%</span></td></tr>
          <tr><td><b>📊 情绪量能</b></td><td>成交量萎缩 + K线止跌信号</td><td><b>30%</b></td><td><span class="range-badge">0~50%</span></td></tr>
          <tr><td><b>🎯 择时确认</b></td><td>MA5站上 + KDJ/MACD + 放量转强</td><td><b>30%</b></td><td><span class="range-badge">0~50%</span></td></tr>
          <tr><td><b>🌐 板块加成</b></td><td>板块资金净流入额外加成</td><td><b>10%</b></td><td><span class="range-badge">0~20%</span></td></tr>
        </table>
        """, unsafe_allow_html=True)

        dims = [
            ("空间维度", 40, "#E74C3C"),
            ("情绪量能", 30, "#3498DB"),
            ("择时确认", 30, "#F39C12"),
            ("板块加成", 10, "#27AE60"),
        ]
        for dim_name, default_w, color in dims:
            cur = st.session_state.orb_weights.get(dim_name, default_w)
            bc1, bc2, bc3, bc4, bc5 = st.columns([0.3, 2.0, 0.6, 0.6, 1.0])
            with bc1:
                st.markdown(f"<span style='color:{color};font-size:16px;'>●</span>", unsafe_allow_html=True)
            with bc2:
                st.markdown(f"<span style='font-size:13px;color:#333;font-weight:600;'>{dim_name}</span>", unsafe_allow_html=True)
            with bc3:
                if st.button("−", key=f"orb_wdec_{dim_name}"):
                    st.session_state.orb_weights[dim_name] = max(0, cur - 1)
                    st.rerun()
            with bc4:
                st.markdown(f"<span style='font-size:16px;font-weight:800;color:{color};'>{st.session_state.orb_weights.get(dim_name, default_w)}%</span>", unsafe_allow_html=True)
            with bc5:
                if st.button("+", key=f"orb_winc_{dim_name}"):
                    cfg = ORB_WEIGHT_CONFIG.get(dim_name, {})
                    st.session_state.orb_weights[dim_name] = min(cfg.get("max", 60), cur + 1)
                    st.rerun()

        total = sum(st.session_state.orb_weights.get(d, w) for d, w, _ in dims)
        wc = "#27AE60" if 90 <= total <= 110 else "#E74C3C"
        st.markdown(f"<span style='font-size:14px;color:{wc};font-weight:700;'>总权重: {total}% {'✅' if 90 <= total <= 110 else '⚠️ 建议前三维度合计约100%'}</span>", unsafe_allow_html=True)

        ca1, ca2 = st.columns(2)
        with ca1:
            if st.button("✅ 应用参数", width='stretch', type="primary", key="orb_apply"):
                st.session_state.orb_results = None
                st.rerun()
        with ca2:
            if st.button("🔄 重置默认", width='stretch', key="orb_reset"):
                st.session_state.orb_weights = dict(DEFAULT_ORB_WEIGHTS)
                st.session_state.orb_params = dict(DEFAULT_ORB_PARAMS)
                st.session_state.orb_results = None
                st.cache_data.clear()
                st.rerun()

def _render_lowbuy_params(model='lowbuy'):
    """低吸模型参数面板（七维评分版，model用于key隔离避免多tab冲突）"""
    prefix = f"lp_{model}"
    with st.expander("⚙️ 低吸模型 · 筛选规则", expanded=False):
        params = _get_lowbuy_params()
        
        st.markdown("""
        <div style="background:#F0FFF4;border:1px solid #C8E6C9;border-radius:8px;padding:12px 16px;margin-bottom:16px;font-size:13px;color:#2E7D32;">
        <b>低吸模型 v4 筛选逻辑：</b><br>
        📊 七维评分：下跌幅度 ≥ min · 企稳信号 ≥ min · 量能恢复 ≥ min · 均线支撑 ≥ min · 估值吸引 ≥ min · 筹码沉淀 ≥ min · 主力资金 ≥ min · 综合 ≥ min<br>
        📉 K线条件：10日跌幅(decline_low ~ decline_high) · 量比 ≤ max · no_new_low_days日不创新低<br>
        🎯 信号分级：<b>综合≥55 + 机构净买→强烈低吸</b> / <b>综合≥40→标准低吸</b> / <b>综合≥25→谨慎低吸</b>
        </div>
        """, unsafe_allow_html=True)
        
        # ---- 第一行: K线预筛条件 ----
        c1, c2, c3 = st.columns(3)
        with c1:
            new_max = st.slider("🎯 每日精选数量", 5, 30, params.get('max_results', 20),
                help="筛选出的股票数量", key=f"{prefix}_max")
            new_decline_low = st.slider("📉 10日跌幅下限(%)", -50, -5, params.get('decline_20d_low', -40),
                help="10日跌幅不低于此值", key=f"{prefix}_dec_low")
            new_decline_high = st.slider("📉 10日跌幅上限(%)", -5, 0, params.get('decline_20d_high', 0),
                help="10日跌幅不高于此值", key=f"{prefix}_dec_high")
        with c2:
            new_max_vr = st.slider("📊 量比上限", 0.5, 3.0, params.get('max_vol_ratio', 2.5),
                step=0.1, help="量比不超过此值", key=f"{prefix}_vr")
            new_fund_wt = st.slider("💰 资金维度权重", 0.0, 0.20, params.get('fund_weight', 0.08),
                step=0.01, help="主力资金维度在综合评分中的权重", key=f"{prefix}_fundwt")
            new_no_low_days = st.slider("📈 不创新低天数", 2, 20, params.get('no_new_low_days', 2),
                help="近N日不创新低", key=f"{prefix}_nolow")

        # ---- 第二行: 反转确认条件 ----
        with c3:
            new_rev_pct = st.slider("📈 脱离底部≥(%)", 0.0, 3.0, params.get('reversal_bottom_pct', 0.2),
                step=0.1, help="近3日均线高于15日最低点的最小百分比，越小越宽松", key=f"{prefix}_rev_pct")
            new_rev_trend = st.checkbox("📈 MA3今日>MA3前日", value=params.get('reversal_require_uptrend', False),
                help="要求今日3日均价高于前日3日均价", key=f"{prefix}_rev_trend")

        # ---- 第三行: 六维门槛 (每列2个) ----
        with st.container():
            c4, c5, c6 = st.columns(3)
            with c4:
                new_min_decline = st.slider("📉 下跌幅度≥", 0, 25, params.get('min_decline_depth', 5),
                    help="raw 0-30，跌幅维度门槛", key=f"{prefix}_decline")
                new_min_stabil = st.slider("🛡️ 企稳信号≥", 0, 20, params.get('min_stabilization', 3),
                    help="raw 0-25，企稳维度门槛", key=f"{prefix}_stabil")
            with c5:
                new_min_vol = st.slider("📈 量能恢复≥", 0, 18, params.get('min_volume_recovery', 2),
                    help="raw 0-20，量能维度门槛", key=f"{prefix}_vol")
                new_min_ma = st.slider("📐 均线支撑≥", 0, 14, params.get('min_ma_support', 4),
                    help="raw 0-15，均线维度门槛", key=f"{prefix}_ma")
            with c6:
                new_min_val = st.slider("💎 估值吸引≥", 0, 9, params.get('min_valuation_attr', 4),
                    help="raw 0-10，估值维度门槛", key=f"{prefix}_val_attr")
                new_min_chip = st.slider("🔒 筹码沉淀≥", 0, 9, params.get('min_chip_settle', 3),
                    help="raw 0-10，筹码维度门槛", key=f"{prefix}_chip_set")
                new_min_fund = st.slider("💰 主力资金≥", 0, 9, params.get('min_fund_flow', 2),
                    help="raw 0-10，资金维度门槛", key=f"{prefix}_fund")
        
        # ---- 第四行: 综合分 + 操作 ----
        nc1, nc2, nc3 = st.columns([2, 1, 1])
        with nc1:
            new_min_total = st.slider("🎯 综合最低分", 10, 60, params.get('min_total_score', 20),
                help="归一化综合评分(0-100)最低门槛，越低越宽松", key=f"{prefix}_total")
            st.markdown(f"""
            <div style="font-size:12px;color:#666;padding:8px 0;">
            当前：10日跌<b>{new_decline_low}%~{new_decline_high}%</b> · 量比≤<b>{new_max_vr}</b> · {new_no_low_days}日不新低 · 脱离≥<b>{new_rev_pct}%</b> · 走高={'✅' if new_rev_trend else '❌'} · 综合≥<b>{new_min_total}</b>分
            </div>
            """, unsafe_allow_html=True)
        with nc2:
            if st.button("✅ 应用参数", width='stretch', type="primary", key=f"{prefix}_apply"):
                st.session_state.lowbuy_params = {
                    '_params_version': DEFAULT_LOWBUY_PARAMS['_params_version'],
                    'max_results': new_max, 'pre_filter_decline': 5,
                    'min_decline_depth': new_min_decline,
                    'min_stabilization': new_min_stabil,
                    'min_volume_recovery': new_min_vol,
                    'min_ma_support': new_min_ma,
                    'min_valuation_attr': new_min_val,
                    'min_chip_settle': new_min_chip,
                    'min_fund_flow': new_min_fund,
                    'min_total_score': new_min_total,
                    'decline_20d_low': new_decline_low, 'decline_20d_high': new_decline_high,
                    'max_vol_ratio': new_max_vr, 'no_new_low_days': new_no_low_days,
                    'reversal_bottom_pct': new_rev_pct,
                    'reversal_require_uptrend': new_rev_trend,
                    'fund_weight': new_fund_wt,
                }
                st.session_state.lowbuy_cache = None
                st.cache_data.clear()
                st.rerun()
        with nc3:
            if st.button("🔄 重置默认", width='stretch', key=f"{prefix}_reset"):
                st.session_state.lowbuy_params = dict(DEFAULT_LOWBUY_PARAMS)
                st.session_state.lowbuy_cache = None
                st.cache_data.clear()
                st.rerun()

def render_sidebar():
    """精简侧边栏 - 只保留导航和基本信息"""
    with st.sidebar:
        st.markdown("""
        <div style="text-align:center;padding:20px 0 10px;border-bottom:1px solid #EDE8E0;margin-bottom:16px;">
        <div style="font-size:36px;">📊</div>
        <div style="font-size:18px;font-weight:700;color:#C4842D;">智能选股系统</div>
        <div style="font-size:11px;color:#BBB;margin-top:4px;">追高 · 低吸 · 双模型策略</div>
        </div>""", unsafe_allow_html=True)
        
        today = datetime.now()
        # 数据源状态指示（同时显示所有可用数据源）
        _ds_parts = []
        if TDX_AVAILABLE:
            _ds_parts.append(f'<span style="color:#2E7D32;">📂 通达信本地</span>')
        if tdx_available():
            _ds_parts.append(f'<span style="color:#1565C0;">📡 pytdx行情</span>')
        if AKSHARE_AVAILABLE:
            _ds_parts.append(f'<span style="color:#F57C00;">🌐 akshare(备用)</span>')
        if not _ds_parts:
            _ds_parts.append(f'<span style="color:#D32F2F;">⚠️ 无数据源</span>')
        _ds_status = ' | '.join(_ds_parts)
        st.markdown(f"""
        <div style="background:#FFF8F0;border-radius:8px;padding:12px;margin-bottom:16px;text-align:center;">
            <div style="font-size:11px;color:#888;">📅 {today.strftime('%Y年%m月%d日 %H:%M')}</div>
            <div style="font-size:13px;color:#C4842D;font-weight:600;">{today.strftime('%A')}</div>
            <div style="font-size:11px;margin-top:6px;">数据源: {_ds_status}</div>
        </div>""", unsafe_allow_html=True)

        page = st.radio("导航", ["🔍 选股筛选", "⭐ 我的自选", "📈 策略回测"],
            label_visibility="collapsed")
        pk = {"🔍 选股筛选": "screener", "⭐ 我的自选": "watchlist", "📈 策略回测": "backtest"}
        if st.session_state.current_page != pk[page]:
            st.session_state.current_page = pk[page]
            st.rerun()

        st.markdown("---")
        
        c1, c2 = st.columns(2)
        with c1:
            if st.button("🔄 刷新", width='stretch', key="sidebar_refresh"):
                st.cache_data.clear(); st.rerun()
        with c2:
            if st.button("🔧 重置权重", width='stretch', key="sidebar_reset_weights"):
                st.session_state.weights = dict(DEFAULT_WEIGHTS)
                st.session_state.top10_cache = None
                st.session_state.top10_cache_key = None
                st.cache_data.clear(); st.rerun()

        wl_count = len(st.session_state.watchlist)
        if wl_count > 0:
            st.markdown(f"""
            <div style="background:#E8F6EF;border-radius:8px;padding:10px;margin-top:12px;text-align:center;">
                <span style="font-size:13px;color:#27AE60;">⭐ 自选股 <b>{wl_count}</b> 只</span>
            </div>""", unsafe_allow_html=True)

        st.markdown("---")
        st.caption("""<div style="text-align:center;color:#BBB;font-size:11px;padding-top:10px;">
        数据来源：pytdx 通达信实时行情<br>
        📊 追高模型：八维强势评分<br>
        📉 低吸模型：底部反转信号<br>
        ⚙️ 参数设置在页面顶部折叠面板</div>""", unsafe_allow_html=True)

def render_filter_bar(df):
    sectors = ["全部"] + sorted(df["板块"].unique().tolist())
    sr_options = [("全部", None), ("强势买入", ("信号", ["强势买入"])),
        ("逢低吸纳", ("信号", ["逢低吸纳"])), ("观望等待", ("信号", ["观望等待"])),
        ("建议回避", ("信号", ["建议回避"]))]
    c1, c2, c3 = st.columns([2, 2, 4])
    with c1: sec = st.selectbox("板块", sectors, label_visibility="collapsed", key="sf_sec")
    with c2:
        slabs = [o[0] for o in sr_options]
        sel_idx = slabs.index(st.selectbox("信号筛选", slabs, label_visibility="collapsed", key="sf_sig"))
        sig_filter = sr_options[sel_idx][1]
    with c3: sw = st.text_input("🔎 搜索代码/名称", "", label_visibility="collapsed", key="sf_search")
    return sec, sig_filter, sw

def render_stats_chase(df):
    t = len(df)
    if t == 0 or '信号' not in df.columns:
        cards = [("📊 0只", "筛选结果", ""), ("0只", "强势买入", ""),
            ("0只", "逢低吸纳", ""), ("0只", "建议回避", ""), ("0分", "平均评分", "")]
        cols = st.columns(5)
        for ic, (vl, lbl, cc) in zip(cols, cards):
            with ic:
                cc_s = f" {cc}" if cc else ""
                st.markdown(f"""<div class="stat-card"><div class="stat-value{cc_s}">{vl}</div><div class="stat-label">{lbl}</div></div>""", unsafe_allow_html=True)
        return
    strong = len(df[df['信号'] == '强势买入'])
    attention = len(df[df['信号'] == '逢低吸纳'])
    watch = len(df[df['信号'] == '建议回避'])
    avg_score = df['综合评分'].mean() if t > 0 else 0
    cards = [(f"📊 {t}只", "筛选结果", ""), (f"🔥 {strong}只", "强势买入", "red" if strong > 3 else ""),
        (f"📈 {attention}只", "逢低吸纳", "orange"), (f"📉 {watch}只", "建议回避", "green"),
        (f"{avg_score:.0f}分", "平均评分", "")]
    cols = st.columns(5)
    for ic, (vl, lbl, cc) in zip(cols, cards):
        with ic:
            cc_s = f" {cc}" if cc else ""
            st.markdown(f"""<div class="stat-card"><div class="stat-value{cc_s}">{vl}</div><div class="stat-label">{lbl}</div></div>""", unsafe_allow_html=True)

def render_stats_lowbuy(df):
    """低吸模型统计数据卡片"""
    t = len(df)
    if t == 0:
        return
    strong = len(df[df['信号'].str.contains('强烈', na=False)])
    cautious = len(df[df['信号'].str.contains('谨慎', na=False)])
    avg_score = df['综合评分'].mean() if '综合评分' in df.columns else 0
    # 平均10日跌幅
    if '20日涨幅' in df.columns:
        try:
            avg_decline = df['20日涨幅'].str.replace('%','').str.replace('+','').astype(float).mean()
            decline_str = f"{avg_decline:.1f}%"
        except:
            decline_str = "N/A"
    else:
        decline_str = "N/A"
    
    cards = [
        (f"📊 {t}只", "筛选结果", ""),
        (f"🔥 {strong}只", "强烈低吸", "red" if strong > 0 else ""),
        (f"📈 {cautious}只", "谨慎低吸", "orange"),
        (f"{avg_score:.0f}分", "平均评分", ""),
        (f"{decline_str}", "平均20日涨幅", "green"),
    ]
    cols = st.columns(5)
    for ic, (vl, lbl, cc) in zip(cols, cards):
        with ic:
            cc_s = f" {cc}" if cc else ""
            st.markdown(f"""<div class="stat-card"><div class="stat-value{cc_s}">{vl}</div><div class="stat-label">{lbl}</div></div>""", unsafe_allow_html=True)

def _diag_stock(diag_code):
    """诊断单只股票在低吸模型中的完整打分流程"""
    code = str(diag_code).strip()
    if not code:
        st.warning("请输入股票代码"); return
    
    params = _get_lowbuy_params()
    
    # 1. 从全市场数据中找到这只股票
    df_market = _app_cache.get('raw_market_data')
    if df_market is None or len(df_market) == 0:
        df_market = fetch_all_a_stocks()
        st.error("无市场数据，请先刷新"); return
    row = df_market[df_market['代码'].astype(str).str.contains(code)]
    if len(row) == 0:
        st.error(f"未找到代码 {code} 的数据"); return
    row = row.iloc[0]
    st.markdown(f"**{row.get('名称', '')} ({code})** · 最新价: {row.get('最新价', 'N/A')} · 涨跌幅: {row.get('涨跌幅', 'N/A')}%")
    
    # 2. 获取K线
    no_new_low_days = params.get('no_new_low_days', 2)
    kline = get_stock_kline(code, days=max(60, no_new_low_days + 15))
    if kline is None or len(kline) < 10:
        st.error("❌ 无法获取K线数据（或K线不足10根）"); return
    closes = kline['收盘'].values.astype(float)
    n = len(closes)
    
    # 3. 逐项检查，显示每步结果
    steps = []
    
    # ---- 预筛检查 ----
    chg = float(row.get('涨跌幅', 99) or 99)
    price = float(row.get('最新价', 0) or 0)
    vr = float(row.get('量比', 99) or 99)
    steps.append(("预筛: 涨幅<9.5%", "✅" if chg < 9.5 else f"❌ 实际{chg}%", chg < 9.5))
    steps.append(("预筛: 价格[3,200]", "✅" if 3 <= price <= 200 else f"❌ 实际{price}", 3 <= price <= 200))
    max_vr = params.get('max_vol_ratio', 2.5)
    steps.append((f"预筛: 量比≤{max_vr}", "✅" if vr <= max_vr else f"❌ 实际{vr:.1f}", vr <= max_vr))
    
    # ---- 10日跌幅（K线真实数据）----
    decline_low = params.get('decline_20d_low', -40)
    decline_high = params.get('decline_20d_high', 0)
    if n >= 12:
        k20d = (closes[-1] / closes[-12] - 1) * 100
        in_range = decline_low <= k20d <= decline_high
        steps.append((f"10日K线跌幅 [{decline_low}%, {decline_high}%]",
                      "✅" if in_range else f"❌ 实际{k20d:.2f}% (不在此范围)", in_range))
        st.metric("10日K线跌幅", f"{k20d:.2f}%", delta=None)
    else:
        steps.append(("10日K线跌幅", f"⚠️ K线仅{n}根(需≥22)", False))
    
    # ---- 不创新低 ----
    if n >= no_new_low_days:
        recent_lows = closes[-no_new_low_days:]
        ok = not (closes[-1] <= min(recent_lows) * 0.998)
        steps.append((f"近{no_new_low_days}日不创新低",
                      "✅" if ok else f"❌ 今日收盘{closes[-1]:.2f} ≤ 近{no_new_low_days}日最低{min(recent_lows):.2f}*0.998", ok))
    else:
        steps.append((f"近{no_new_low_days}日不创新低", f"⚠️ K线不足{n}根", False))
    
    # ---- 反转条件 ----
    if n < 15:
        steps.append(("反转条件", "⚠️ K线<15根", False))
    else:
        low_idx_15 = np.argmin(closes[-15:])
        low_pos = 15 - low_idx_15
        r1_ok = low_pos >= 1
        steps.append((f"反转1: 最低点距今≥1天", "✅" if r1_ok else f"❌ 最低点就在今天(距{low_pos}天)", r1_ok))
        
        avg3d = np.mean(closes[-3:])
        min15d = np.min(closes[-15:])
        rev_pct = params.get('reversal_bottom_pct', 0.2) / 100.0
        detach_pct = (avg3d - min15d) / min15d * 100 if min15d > 0 else 0
        r2_ok = detach_pct >= rev_pct * 100
        steps.append((f"反转2: 脱离底部≥{rev_pct*100:.1f}%",
                      "✅" if r2_ok else f"❌ 实际{detach_pct:.2f}%", r2_ok))
        
        require_ut = params.get('reversal_require_uptrend', False)
        if require_ut:
            r3_ok = np.mean(closes[-3:]) > np.mean(closes[-4:-1])
            ma3_today = np.mean(closes[-3:])
            ma3_prev = np.mean(closes[-4:-1])
            trend_desc = "弱" if ma3_today <= ma3_prev else "强"
            steps.append((f"反转3: MA3今日>MA3前日", "✅" if r3_ok else f"❌ MA3今日{ma3_today:.2f}≤前日{ma3_prev:.2f}", r3_ok))
        else:
            steps.append(("反转3: MA3今日>MA3前日", "⏭️ 已关闭此检查", True))
    
    # ---- 构建评分数据并计算七维分 ----
    try:
        lhb_data = {}
        sector_data = {}
        stock_sector_map = {}
        try:
            lhb_data = _get_cached_dragon_tiger()
            sector_data, stock_sector_map = _get_cached_sector_data()
        except Exception:
            pass
        stock_data = _build_stock_data(row, kline, lhb_data, sector_data, stock_sector_map)
        score_result = calculate_lowbuy_score(stock_data, kline, params)
        
        _raw = score_result.get('_raw', {})
        dims = [
            ("下跌幅度", _raw.get('s1', 0), params.get('min_decline_depth', 5), 30),
            ("企稳信号", _raw.get('s2', 0), params.get('min_stabilization', 10), 25),
            ("量能恢复", _raw.get('s3', 0), params.get('min_volume_recovery', 8), 20),
            ("均线支撑", _raw.get('s4', 0), params.get('ma_ma_support', 8), 15),
            ("估值吸引", _raw.get('s5', 0), params.get('min_valuation_attr', 4), 10),
            ("筹码沉淀", _raw.get('s6', 0), params.get('min_chip_settle', 3), 10),
            ("主力资金", _raw.get('s7', 0), params.get('min_fund_flow', 2), 10),
        ]
        for name, raw_val, threshold, full in dims:
            # fix key name for 均线支撑
            thr = params.get('min_' + ('ma_support' if name == '均线支撑' else
                                        'decline_depth' if name == '下跌幅度' else
                                        'stabilization' if name == '企稳信号' else
                                        'volume_recovery' if name == '量能恢复' else
                                        'valuation_attr' if name == '估值吸引' else
                                        'chip_settle' if name == '筹码沉淀' else
                                        'fund_flow'), threshold)
            ok = raw_val >= thr
            steps.append((f"七维·{name} ≥{thr}(满分{full})",
                          "✅" if ok else f"❌ 实际{raw_val}/{full}", ok))
        
        s_total = score_result.get('综合评分', 0)
        min_total = params.get('min_total_score', 20)
        steps.append((f"综合总分 ≥{min_total}",
                      f"📊 **{s_total}**分" if s_total >= min_total else f"❌ **{s_total}**分 (需≥{min_total})",
                      s_total >= min_total))
        
    except Exception as e:
        steps.append(("七维评分计算", f"❌ 异常: {e}", False))
    
    # 显示结果表格
    st.markdown("---")
    c_status, c_detail = st.columns([1, 3])
    with c_status:
        all_pass = all(s[2] for s in steps)
        if all_pass:
            st.success("🎉 全部通过！应出现在结果列表中")
        else:
            fail_count = sum(1 for s in steps if not s[2])
            st.error(f"❌ 未通过 ({fail_count}/{len(steps)} 项)")
    
    with c_detail:
        for i, (desc, status, ok) in enumerate(steps):
            color = "#C8E6C9" if ok else "#FFCDD2"
            icon = "✅" if ok else ("⚠️" if "⏭" in status else "❌")
            st.markdown(f"<div style='padding:4px 10px;margin:2px 0;border-radius:4px;background:{color};font-size:13px;'>"
                       f"<b>{icon} [{i+1}]</b> {desc}: <b>{status}</b></div>", unsafe_allow_html=True)

def _export_df_to_xlsx(dframe, code_col="代码"):
    """将 DataFrame 导出为 xlsx 字节，代码列设为文本格式防止前导零丢失"""
    _illegal_xml_re = re.compile(
        '[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x84\x86-\x9f\ud800-\udfff\ufffe\uffff]'
    )
    def _clean_cell(val):
        if isinstance(val, str):
            return _illegal_xml_re.sub('', val)
        return val

    df = dframe.copy()
    if code_col in df.columns:
        df[code_col] = df[code_col].astype(str).str.zfill(6)
    # 清理所有单元格中的非法XML字符（不限dtype，防止控制字符藏在混合列中）
    for col in df.columns:
        df[col] = df[col].apply(lambda x: _illegal_xml_re.sub('', x) if isinstance(x, str) else x)
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Sheet1')
        ws = writer.sheets['Sheet1']
        if code_col in df.columns:
            code_col_idx = list(df.columns).index(code_col) + 1  # openpyxl 1-based
            for row in range(2, ws.max_row + 1):
                ws.cell(row=row, column=code_col_idx).number_format = '@'
    return buf.getvalue()

def render_stock_buttons(stocks, prefix="bt"):
    """统一的股票操作按钮区：5列×N行，每格 序号+名称+[评分详情]+[加自选]"""
    if not stocks:
        return
    for i in range(0, len(stocks), 5):
        cols = st.columns(5)
        for j in range(5):
            if i + j >= len(stocks):
                break
            s = stocks[i + j]
            code = str(s.get('代码', ''))
            name = str(s.get('名称', ''))
            seq = i + j + 1
            wl = code in st.session_state.watchlist
            with cols[j]:
                st.caption(f"{seq}. {name}  `{code}`")
                bc1, bc2 = st.columns(2)
                with bc1:
                    if st.button("评分详情", key=f"{prefix}_d_{code}", width='stretch'):
                        st.session_state.selected_stock = code
                        st.rerun()
                with bc2:
                    lb = "★ 已自选" if wl else "+ 加自选"
                    if st.button(lb, key=f"{prefix}_w_{code}", width='stretch',
                                 type="secondary" if not wl else "primary"):
                        if wl:
                            st.session_state.watchlist.remove(code)
                        else:
                            st.session_state.watchlist.append(code)
                        save_watchlist(st.session_state.watchlist)
                        st.rerun()

def render_table_chase(fdf, dde_scores=None, resonance_scores=None, resonance_styles=None):
    """追高模型Top30 — st.dataframe 表格 + 5列按钮网格"""
    if fdf is None or len(fdf) == 0:
        st.info("暂无符合追高条件的标的。")
        return
    st.markdown(
        f"<div style='font-size:13px;color:#888;margin-bottom:8px;'>共 <b>{len(fdf)}</b> 只标的</div>",
        unsafe_allow_html=True
    )
    fdf = fdf.copy()
    fdf['代码'] = fdf['代码'].astype(str).str.zfill(6)
    fdf = fdf.rename(columns={'综合评分': '追高评分', '板块': '概念板块'})

    # 共振交叉评分
    if resonance_scores:
        fdf['共振评分'] = fdf['代码'].apply(lambda x: resonance_scores.get(x, None))
    if resonance_styles:
        fdf['共振评价'] = fdf['代码'].apply(lambda x: resonance_styles.get(x, '-'))

    # 确定可用列
    base_cols = ['名称', '概念板块', '趋势结构', '动量强度', '板块共振',
                 '北向资金', '机构净买', '板块资金热度', '量价配合', '估值安全', '筹码稳定', '情绪热度',
                 '5日涨幅', '换手率', 'PE', '信号', '建议', '追高评分']
    if dde_scores:
        fdf['DDE资金确认(50)'] = fdf['代码'].apply(lambda x: dde_scores.get(x, None))
        if 'DDE资金确认(50)' not in base_cols:
            base_cols.insert(-2, 'DDE资金确认(50)')
    if resonance_scores or resonance_styles:
        if resonance_scores:
            if '共振评分' not in base_cols:
                base_cols.insert(-2, '共振评分')
        if resonance_styles:
            if '共振评价' not in base_cols:
                base_cols.insert(-2, '共振评价')
    display_cols = [c for c in base_cols if c in fdf.columns]
    df_display = fdf[display_cols]

    # Arrow 序列化兼容：含 "N/A" 字符串的列是 object 类型，PyArrow 无法序列化 → 统一转 str
    for c in df_display.columns:
        if df_display[c].dtype == 'object':
            df_display[c] = df_display[c].astype(str).replace('nan', 'N/A')

    def color_score(val):
        if isinstance(val, (int, float)):
            if val >= 80: return 'background-color:#C8E6C9;font-weight:bold'
            if val >= 70: return 'background-color:#E8F5E9'
            if val >= 60: return 'background-color:#FFF9C4'
            return ''
        return ''

    styled = df_display.style.map(color_score, subset=['追高评分'])
    st.dataframe(styled, width='stretch', hide_index=True,
                 column_config={'追高评分': st.column_config.NumberColumn(format='%.0f')})

    st.markdown("---")
    st.caption("操作区 — 评分详情 | 加/取消自选")
    render_stock_buttons(fdf.to_dict('records'), prefix="ch")

def render_table_lowbuy(fdf, dde_scores=None, resonance_scores=None, resonance_styles=None):
    """低吸模型Top30 — st.dataframe 表格 + 5列按钮网格"""
    if fdf is None or len(fdf) == 0:
        st.info("暂无符合低吸条件的标的。")
        return
    st.markdown(
        f"<div style='font-size:13px;color:#888;margin-bottom:8px;'>共 <b>{len(fdf)}</b> 只标的</div>",
        unsafe_allow_html=True
    )
    fdf = fdf.copy()
    fdf['代码'] = fdf['代码'].astype(str).str.zfill(6)
    fdf = fdf.rename(columns={'综合评分': '低吸评分', '板块': '概念板块'})

    # 共振交叉评分
    if resonance_scores:
        fdf['共振评分'] = fdf['代码'].apply(lambda x: resonance_scores.get(x, None))
    if resonance_styles:
        fdf['共振评价'] = fdf['代码'].apply(lambda x: resonance_styles.get(x, '-'))

    base_cols = ['名称', '概念板块', '下跌幅度', '企稳信号', '量能恢复',
                 '均线支撑', '估值吸引', '筹码沉淀', '20日涨幅', '信号', '低吸评分']
    if dde_scores:
        fdf['DDE资金确认(50)'] = fdf['代码'].apply(lambda x: dde_scores.get(x, None))
        if 'DDE资金确认(50)' not in base_cols:
            base_cols.insert(-1, 'DDE资金确认(50)')
    if resonance_scores or resonance_styles:
        if resonance_scores:
            if '共振评分' not in base_cols:
                base_cols.insert(-1, '共振评分')
        if resonance_styles:
            if '共振评价' not in base_cols:
                base_cols.insert(-1, '共振评价')
    display_cols = [c for c in base_cols if c in fdf.columns]
    df_display = fdf[display_cols]

    def color_score(val):
        if isinstance(val, (int, float)):
            if val >= 80: return 'background-color:#C8E6C9;font-weight:bold'
            if val >= 70: return 'background-color:#E8F5E9'
            if val >= 60: return 'background-color:#FFF9C4'
            return ''
        return ''

    styled = df_display.style.map(color_score, subset=['低吸评分'])
    st.dataframe(styled, width='stretch', hide_index=True,
                 column_config={'低吸评分': st.column_config.NumberColumn(format='%.0f')})

    st.markdown("---")
    st.caption("操作区 — 评分详情 | 加/取消自选")
    render_stock_buttons(fdf.to_dict('records'), prefix="lb")

def _render_filter_dashboard(_dbg, params):
    """可视化展示各过滤阶段的拦截数量条带"""
    total = _dbg.get('total', 0)
    if total == 0:
        with st.expander("📊 过滤漏斗图 (点击展开)", expanded=True):
            st.info("尚未执行全市场扫描，请点击「刷新数据」获取过滤漏斗分析")
        return

    # 前置过滤阶段
    front_stages = [
        ("无K线",       _dbg.get('no_kline', 0),          "#999"),
        ("10d跌幅不符", _dbg.get('decline_20d_fail', 0),  "#E67E22"),
        ("创新低",      _dbg.get('no_new_low', 0),        "#E74C3C"),
        ("反转1(距今<1d)", _dbg.get('reversal1', 0),       "#E91E63"),
        ("反转2(脱离不足)", _dbg.get('reversal2', 0),      "#9C27B0"),
        ("反转3(MA3弱)",  _dbg.get('reversal3', 0),        "#673AB7"),
    ]
    # 七维门槛阶段
    seven_dim_stages = [
        ("跌幅不足",  _dbg.get('decline', 0),     "#F39C12"),
        ("企稳不足",  _dbg.get('stabil', 0),      "#E74C3C"),
        ("量能不足",  _dbg.get('vol_rec', 0),     "#3498DB"),
        ("均线不足",  _dbg.get('ma_sup', 0),      "#2ECC71"),
        ("估值不足",  _dbg.get('val', 0),         "#9B59B6"),
        ("筹码不足",  _dbg.get('chip', 0),        "#1ABC9C"),
        ("资金不足",  _dbg.get('fund', 0),        "#E67E22"),
        ("总分不足",  _dbg.get('total_score', 0), "#34495E"),
    ]
    
    passed = _dbg.get('passed', 0)
    
    max_cnt = max((c for _, c, _ in front_stages + seven_dim_stages), default=1)
    max_cnt = max(max_cnt, 1)
    
    def _bar_html(label, cnt, color, max_val):
        pct = cnt / total * 100 if total > 0 else 0
        bar_pct = cnt / max_val * 100 if max_val > 0 else 0
        bar_style = f"width:{bar_pct}%;background:{color};" if cnt > 0 else "width:0;"
        return f"""
        <div style="display:flex;align-items:center;margin:2px 0;font-size:12px;">
            <span style="width:100px;color:#666;">{label}</span>
            <span style="width:40px;text-align:right;font-weight:600;margin-right:8px;
                color:{'#E74C3C' if cnt > 0 else '#999'};">{cnt}</span>
            <div style="flex:1;background:#F0EBE4;border-radius:4px;height:14px;">
                <div style="{bar_style}height:14px;border-radius:4px;transition:width 0.3s;"></div>
            </div>
            <span style="width:45px;text-align:right;font-size:11px;color:#999;margin-left:6px;">{pct:.1f}%</span>
        </div>"""
    
    bars_html = '<div style="margin:8px 0;">'
    bars_html += '<div style="font-size:11px;color:#888;margin-bottom:4px;">▸ 前置过滤</div>'
    for label, cnt, color in front_stages:
        bars_html += _bar_html(label, cnt, color, max_cnt)
    bars_html += '<div style="font-size:11px;color:#888;margin:8px 0 4px;">▸ 七维门槛</div>'
    for label, cnt, color in seven_dim_stages:
        bars_html += _bar_html(label, cnt, color, max_cnt)
    bars_html += '<div style="font-size:11px;color:#888;margin:8px 0 4px;">▸ 结果</div>'
    bars_html += _bar_html("✅ 通过", passed, "#27AE60", max_cnt)
    bars_html += '</div>'
    
    with st.expander("📊 过滤漏斗图 (点击展开)", expanded=True):
        st.markdown(bars_html, unsafe_allow_html=True)
        st.caption(f"全市场扫描 {total} 只 → 最终通过 {passed} 只")
        # [DEBUG] 显示运行时实际参数
        pdbg = _dbg.get('_params_debug', {})
        if pdbg:
            st.caption(f"🔧 运行时参数: stabil≥{pdbg.get('min_stabilization','?')} vol≥{pdbg.get('min_volume_recovery','?')} rev_pct={pdbg.get('reversal_bottom_pct','?')}% uptrend={pdbg.get('reversal_require_uptrend','?')} total≥{pdbg.get('min_total_score','?')} ver={pdbg.get('_params_version','?')}")

def _render_lowbuy_score_table(result_df):
    """低吸模型综合评分列表（表格样式）"""
    df = result_df.head(20) if isinstance(result_df, pd.DataFrame) else pd.DataFrame(result_df).head(20)
    if len(df) == 0:
        return
    
    for idx, row in df.iterrows():
        rank = idx + 1
        score = row.get('综合评分', row.get('信号强度', 0))
        signal = row.get('信号', '标准低吸')
        sig_bg = "#E8F5E9" if "强烈" in str(signal) else "#F1F8E9"
        sig_color = "#2E7D32" if "强烈" in str(signal) else "#43A047"
        
        # 八维评分
        dims = ['下跌', '企稳', '量能', '均线', '估值', '筹码']
        dim_vals = [
            row.get('下跌幅度', 0), row.get('企稳信号', 0),
            row.get('量能恢复', 0), row.get('均线支撑', 0),
            row.get('估值吸引', 0), row.get('筹码沉淀', 0)
        ]
        
        dim_html = ""
        for d_name, d_val in zip(dims, dim_vals):
            d_color = "#E74C3C" if d_val >= 80 else "#E67E22" if d_val >= 65 else "#27AE60"
            dim_html += f'<span style="font-size:11px;color:#888;">{d_name}</span> <span style="font-size:12px;font-weight:700;color:{d_color};">{d_val}</span>  '
        
        chg_20d = row.get('20日涨幅', 'N/A')
        chg_color = "#E74C3C" if "+" in str(chg_20d) else "#27AE60"
        sector = str(row.get('概念板块', ''))[:6]
        
        bg = "#F9FFF9" if rank <= 3 else "#FFFFFF"
        rank_badge = f'<span style="display:inline-block;width:22px;height:22px;border-radius:50%;background:{"#FFD700" if rank==1 else "#C0C0C0" if rank==2 else "#CD7F32" if rank==3 else "#E0E0E0"};color:white;text-align:center;line-height:22px;font-size:11px;font-weight:700;">{rank}</span>'
        
        st.markdown(f"""<div style="display:flex;align-items:center;padding:8px 14px;border-bottom:1px solid #F0EDE8;background:{bg};border-radius:4px;margin-bottom:2px;">
<div style="width:30px;flex-shrink:0;text-align:center;">{rank_badge}</div>
<div style="width:120px;flex-shrink:0;padding:0 8px;">
<div style="font-weight:700;color:#333;font-size:13px;">{row.get('名称', '')}</div>
<div style="font-size:10px;color:#999;">{row.get('代码', '')} · {sector}</div>
</div>
<div style="width:60px;text-align:center;">
<span style="font-size:18px;font-weight:800;color:#2E7D32;">{score}</span>
</div>
<div style="width:70px;text-align:center;">
<span style="font-size:12px;font-weight:600;color:{chg_color};">{chg_20d}</span>
</div>
<div style="flex:1;padding:0 8px;">{dim_html}</div>
<div style="width:80px;text-align:center;">
<span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600;background:{sig_bg};color:{sig_color};">{signal}</span>
</div>
<div style="width:50px;text-align:center;">
<button style="background:none;border:1px solid #ddd;border-radius:4px;padding:2px 8px;font-size:11px;color:#666;cursor:pointer;" title="查看详情">详情</button>
</div>
</div>""", unsafe_allow_html=True)

def _render_lowbuy_cards(result_df):
    """低吸模型卡片式展示（与追高模型Top10卡片风格一致）"""
    stocks = result_df.to_dict('records') if isinstance(result_df, pd.DataFrame) else result_df
    if not stocks:
        return
    
    # 卡片式布局 - 5只/行
    for i in range(0, len(stocks), 5):
        row_stocks = stocks[i:i+5]
        cols = st.columns(5)
        for j, stock in enumerate(row_stocks):
            with cols[j]:
                rank = i + j + 1
                rank_class = "gold" if rank == 1 else "silver" if rank == 2 else "bronze" if rank == 3 else ""
                rank_color = "#FFD700" if rank == 1 else "#C0C0C0" if rank == 2 else "#CD7F32" if rank == 3 else "#CCC"
                
                chg_20d = stock.get('20日涨幅', 'N/A')
                chg_color = "#E74C3C" if "+" in str(chg_20d) else "#27AE60"
                
                score = stock.get('低吸评分', stock.get('综合评分', stock.get('信号强度', 0)))
                
                signal = stock.get('信号', '标准低吸')
                sig_class = "badge-strong" if "强烈" in signal else "badge-hold"
                
                sector = stock.get('概念板块', '其他')
                if len(sector) > 8:
                    sector = sector[:8]
                
                st.markdown(f"""
                <div class="top10-card">
                    <div class="top10-rank {rank_class}" style="color:{rank_color};">{rank}</div>
                    <div style="padding-right:30px;">
                        <div style="font-weight:700;color:#333;font-size:15px;margin-bottom:2px;">{stock.get('名称', '')}</div>
                        <div style="font-size:11px;color:#888;margin-bottom:8px;">{stock.get('代码', '')} · {sector}</div>
                        <div style="display:flex;justify-content:space-between;align-items:center;">
                            <span style="font-size:20px;font-weight:800;color:#C4842D;">{score}</span>
                            <span style="font-size:13px;font-weight:600;color:{chg_color};">{chg_20d}</span>
                        </div>
                        <div style="margin-top:6px;"><span class="metric-badge {sig_class}">{signal}</span></div>
                    </div>
                </div>""", unsafe_allow_html=True)
                
                code = stock.get("代码", "")
                in_wl = code in st.session_state.watchlist
                if st.button("⭐" if in_wl else "+自选", key=f"lbt5_{code}",
                    width='stretch', type="primary" if in_wl else "secondary"):
                    if in_wl:
                        st.session_state.watchlist.remove(code)
                    else:
                        st.session_state.watchlist.append(code)
                    save_watchlist(st.session_state.watchlist)
                    st.rerun()
