"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import CACHE_DATA_JSON, DEFAULT_GC_PARAMS, DEFAULT_GC_SAMPLE_OPTIONS, DEFAULT_GC_WEIGHTS, DEFAULT_LOWBUY_WEIGHTS, LOWBUY_WEIGHT_CONFIG, WEIGHT_CONFIG
from core.config import AKSHARE_AVAILABLE
from core.screener import get_stock_pool, get_top10_stocks, get_lowbuy_top5, score_single_stock, _find_stock_row, get_stock_detail, screen_low_buy_stocks, get_stock_pool_chase_high, batch_calculate_rsi
from core.scoring.chase_high import calculate_v3_total_score, calculate_five_dimensions_score, _build_stock_data, _classify_signal
from core.scoring.lowbuy import calculate_lowbuy_score, _check_low_buy_conditions, _get_lowbuy_params
from core.scoring.golden_cross import calculate_golden_cross_score, _run_golden_cross_scan, get_hot_concept_stocks, get_volprice_sectors, _get_gc_params
from core.scoring.canslim import calculate_canslim_score, compute_rps
from core.scoring.dilemma import calculate_dilemma_reversal_score
from core.scoring.oversold import calculate_oversold_rebound_score
from core.filters import hard_filter_oversold_rebound
from core.scoring.resonance import get_dde_confirmation_scores, calculate_resonance_score, _classify_resonance_style, get_resonance_data
from core.filters import hard_filter_v3, _gc_hard_filter
from data.market import fetch_all_a_stocks, preprocess_stock_data, get_stock_kline, get_kline_with_today, get_all_spot_data, _supplement_tencent_quotes, read_tdx_day_file, calculate_dynamic_recommend_count
from data.cache import load_watchlist, save_watchlist, save_cache_data, load_cache_data, is_cache_today
from data.dde import _load_dde_data, _get_dde_or_fallback, _get_resonance_cross_ref
from data.sector import _get_cached_dragon_tiger, _get_cached_sector_data, _get_sector_fund_flow, fetch_dragon_tiger_v3, fetch_sector_board_v3, _classify_stock_sector
from data.financial import get_financial_data
from data.tdx_provider import tdx_available, fetch_all_quotes_tdx, fetch_kline_tdx, get_today_quote_single, fetch_sector_data_tdx, resolve_market
from backtest.runner import run_real_backtest_cached, generate_backtest_data
from backtest.metrics import calc_backtest_metrics
from app.charts import create_candlestick_chart, create_radar_chart, create_backtest_equity_chart, create_monthly_heatmap, create_score_bar
from app.components import (
    render_filter_bar, render_top_params_panel, render_stats_chase,
    render_stats_lowbuy, render_stock_buttons, render_table_chase,
    render_table_lowbuy, _render_lowbuy_cards, _render_filter_dashboard,
    _diag_stock, _export_df_to_xlsx,
)
import backtest_engine

def render_screener():
    """选股筛选页面 - 含模型切换"""
    if not tdx_available() and not AKSHARE_AVAILABLE:
        st.markdown("""<div class="data-status warning">
        <span>⚠️ pytdx 和 akshare 均不可用，请检查通达信连接</span>
        <span>安装 pytdx: pip install pytdx</span>
        </div>""", unsafe_allow_html=True)
    
    # ===== 模型切换 =====
    st.markdown("""
    <style>
    button[data-baseweb="tab"] {
        font-size: 26px !important;
        padding: 12px 32px !important;
    }
    button[data-baseweb="tab"] span {
        font-size: 26px !important;
    }
    div[data-baseweb="tab-list"] button:first-child {
        color: #6C5CE7 !important;
        border-bottom: 3px solid #6C5CE7 !important;
    }
    </style>
    """, unsafe_allow_html=True)
    model_names = {
        "resonance": "🎯 共振模型（多维共振参考）",
        "chase_high": "🚀 追高模型（抓强势龙头股）",
        "buy_low": "📉 低吸模型（抓超跌价值股）",
        "rebound_model": "📌 金叉模型（抓强势回调股）",
        "canslim": "📊 CAN SLIM模型（抓主升浪股）",
        "dilemma_reversal": "🔄 困境反转模型（抓周期股）",
        "oversold_rebound": "💎 超跌反弹模型（抓超跌股）",
    }
    current = st.session_state.current_model
    tab_labels = list(model_names.values())
    key_order = list(model_names.keys())
    current_idx = key_order.index(current) if current in key_order else 0
    
    if "gc_params" not in st.session_state:
        st.session_state.gc_params = dict(DEFAULT_GC_PARAMS)
    if "gc_weights" not in st.session_state:
        st.session_state.gc_weights = dict(DEFAULT_GC_WEIGHTS)
    
    with st.expander("📊 个股评分（输入代码查六大模型得分）", expanded=False):
        render_stock_scorer()
    
    model_tabs = st.tabs(tab_labels)
    
    from app.renderers.resonance import render_tab_resonance
    from app.renderers.chase_high import render_tab_chase_high
    from app.renderers.buy_low import render_tab_buy_low
    from app.renderers.golden_cross import render_tab_golden_cross
    from app.renderers.canslim import render_tab_canslim
    from app.renderers.dilemma import render_tab_dilemma
    from app.renderers.oversold import render_tab_oversold
    
    render_tab_resonance(st, model_tabs, 0)
    render_tab_chase_high(st, model_tabs, 1)
    render_tab_buy_low(st, model_tabs, 2)
    render_tab_golden_cross(st, model_tabs, 3)
    render_tab_canslim(st, model_tabs, 4)
    render_tab_dilemma(st, model_tabs, 5)
    render_tab_oversold(st, model_tabs, 6)

def render_top_chase_high():
    """追高模型综合动态推荐"""
    top_n = get_top10_stocks()
    if not top_n: return
    dyn_n = st.session_state.get('_chase_dynamic_n', len(top_n))
    
    st.markdown(f"""
    <div class="top10-container">
        <div class="top10-header">
            <div class="top10-title">🌟 追高综合 Top {dyn_n} <span class="top10-badge">每日更新</span></div>
        </div>
    </div>""", unsafe_allow_html=True)
    
    btn1, btn2, _ = st.columns([1, 1, 4])
    with btn1:
        if st.button("⭐ 一键加入自选", width='stretch', type="primary", key="ch_add_all"):
            for stock in top_n:
                if stock["代码"] not in st.session_state.watchlist:
                    st.session_state.watchlist.append(stock["代码"])
            save_watchlist(st.session_state.watchlist)
            st.success(f"已将Top {dyn_n}全部加入自选！"); st.rerun()
    with btn2:
        top_n_df = pd.DataFrame(top_n)
        xlsx_data = _export_df_to_xlsx(top_n_df)
        st.download_button(f"📥 导出Top{dyn_n}", xlsx_data, f"top{dyn_n}_chase_{datetime.now().strftime('%Y%m%d')}.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", width='stretch', key="dl_t10")
    
    st.markdown("")
    for i in range(0, len(top_n), 5):
        row_stocks = top_n[i:i+5]
        cols = st.columns(5)
        for j, stock in enumerate(row_stocks):
            with cols[j]:
                rank = i + j + 1
                rank_class = "gold" if rank == 1 else "silver" if rank == 2 else "bronze" if rank == 3 else ""
                rank_color = "#FFD700" if rank == 1 else "#C0C0C0" if rank == 2 else "#CD7F32" if rank == 3 else "#CCC"
                chg = stock.get('5日涨幅', '0%')
                chg_color = "#E74C3C" if "+" in str(chg) else "#27AE60"
                st.markdown(f"""
                <div class="top10-card">
                    <div class="top10-rank {rank_class}" style="color:{rank_color};">{rank}</div>
                    <div style="padding-right:30px;">
                        <div style="font-weight:700;color:#333;font-size:15px;margin-bottom:2px;">{stock['名称']}</div>
                        <div style="font-size:11px;color:#888;margin-bottom:8px;">{stock['代码']} · {stock.get('概念板块', '其他')[:8]}</div>
                        <div style="display:flex;justify-content:space-between;align-items:center;">
                            <span style="font-size:20px;font-weight:800;color:#C4842D;">{stock.get('追高评分', stock.get('综合评分', ''))}</span>
                            <span style="font-size:13px;font-weight:600;color:{chg_color};">{chg}</span>
                        </div>
                        <div style="margin-top:6px;"><span class="metric-badge badge-strong">{stock['信号']}</span></div>
                    </div>
                </div>""", unsafe_allow_html=True)
                code = stock["代码"]; in_wl = code in st.session_state.watchlist
                if st.button("⭐" if in_wl else "+自选", key=f"t10_{code}",
                    width='stretch', type="primary" if in_wl else "secondary"):
                    if in_wl: st.session_state.watchlist.remove(code)
                    else: st.session_state.watchlist.append(code)
                    save_watchlist(st.session_state.watchlist); st.rerun()

def render_top_low_buy(sample_source="全市场A股"):
    """低吸模型精选Top — 动态推荐数量"""
    _lb_dyn_n = calculate_dynamic_recommend_count()
    st.markdown(f"""
    <div class="lowbuy-container">
        <div class="top10-header">
            <div class="lowbuy-title">📉 低吸精选 Top {_lb_dyn_n} <span class="lowbuy-badge">底部反转信号</span></div>
        </div>
    </div>""", unsafe_allow_html=True)
    
    # ===== 单只股票诊断（始终显示，不受缓存影响）=====
    with st.expander("🔍 查询单只股票打分", expanded=False):
        diag_code = st.text_input("输入股票代码（如 601318）", value="601318", key="lb_diag_code", max_chars=6)
        if st.button("🔬 诊断", key="lb_diag_btn", width='stretch'):
            _diag_stock(diag_code)
    
    # 检查是否有今天的缓存
    if st.session_state.get('lowbuy_cache') and st.session_state.get('last_update_time'):
        cache_time = st.session_state.last_update_time
        if cache_time.date() == datetime.now().date():
            st.info(f"📌 显示今日 {cache_time.strftime('%H:%M')} 的缓存结果，点击「刷新数据」获取最新")
            result_df = pd.DataFrame(st.session_state.lowbuy_cache)
            if len(result_df) > 0:
                # 过滤漏斗图（卡片之前，与新扫描路径一致）
                _dbg = st.session_state.get('_lb_dbg', {})
                _lp = _get_lowbuy_params()
                try:
                    _render_filter_dashboard(_dbg, _lp)
                except Exception as _e:
                    st.warning(f"过滤漏斗渲染异常: {_e}")
                btn1, btn2, _ = st.columns([1, 1, 4])
                with btn1:
                    if st.button("⭐ 一键加入自选", width='stretch', type="primary", key="lb_add_all_cached"):
                        for _, row in result_df.iterrows():
                            if row["代码"] not in st.session_state.watchlist:
                                st.session_state.watchlist.append(row["代码"])
                        save_watchlist(st.session_state.watchlist)
                        st.success(f"已将{len(result_df)}只低吸标的加入自选！"); st.rerun()
                with btn2:
                    xlsx_data = _export_df_to_xlsx(result_df.head(_lb_dyn_n))
                    st.download_button(f"📥 导出Top{_lb_dyn_n}", xlsx_data, f"top{_lb_dyn_n}_lowbuy_{datetime.now().strftime('%Y%m%d')}.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", width='stretch', key="dl_lb")
                st.markdown("")
                _render_lowbuy_cards(result_df.head(_lb_dyn_n))
                return
    
    # 无缓存，运行新的筛选
    df_raw = fetch_all_a_stocks()
    if df_raw is None:
        st.warning("无法获取行情数据"); return
    
    # 🌟 样本来源过滤
    if sample_source == "热门板块":
        hot_codes = get_hot_concept_stocks(6)
        if hot_codes:
            df_raw['代码'] = df_raw['代码'].astype(str).str.zfill(6)
            df_raw = df_raw[df_raw['代码'].isin(hot_codes)]
            st.info(f"已锁定 {len(df_raw)} 只热门概念板块成分股")
        else:
            st.warning("未能获取热门板块数据，回退为全市场扫描")
    elif sample_source == "量价":
        vp_codes = get_volprice_sectors(6)
        if vp_codes:
            df_raw['代码'] = df_raw['代码'].astype(str).str.zfill(6)
            df_raw = df_raw[df_raw['代码'].isin(vp_codes)]
            st.info(f"已锁定 {len(df_raw)} 只量价反转板块成分股")
        else:
            st.warning("未能获取量价反转板块数据，回退为全市场扫描")
    
    df_market = preprocess_stock_data(df_raw)
    if df_market is None:
        st.warning("数据预处理失败"); return
    
    if sample_source == "热门板块":
        spinner_text = "正在扫描资金加速板块，筛选低吸标的…"
    elif sample_source == "量价":
        spinner_text = "正在扫描量价反转板块，筛选低吸标的…"
    else:
        spinner_text = "正在全市场扫描底部反转信号，请稍候..."
    with st.spinner(spinner_text):
        result_df = screen_low_buy_stocks(df_market)
    
    # 显示过滤漏斗图
    _dbg = st.session_state.get('_lb_dbg', {})
    _lp = _get_lowbuy_params()
    try:
        _render_filter_dashboard(_dbg, _lp)
    except Exception as _e:
        st.warning(f"过滤漏斗渲染异常: {_e}")
    
    if result_df is None or len(result_df) == 0:
        st.info("📭 今日未找到符合低吸条件的股票。可能当前市场整体处于上升趋势，或下跌个股尚未出现明确的反转信号。")
        st.markdown("""
        <div style="background:#FFF8E1;border-radius:8px;padding:12px 16px;font-size:13px;color:#888;">
        💡 <b>提示：</b>可尝试在顶部参数面板中放宽条件（如减少下跌观察天数、扩大跌幅区间）
        </div>""", unsafe_allow_html=True)
        return
    
    # 保存低吸结果到缓存
    if result_df is not None and len(result_df) > 0:
        st.session_state.lowbuy_cache = result_df.to_dict('records')
        save_cache_data({
            'chase_high_top10': st.session_state.get('top10_cache'),
            'lowbuy_top5': st.session_state.lowbuy_cache,
            'lowbuy_dbg': st.session_state.get('_lb_dbg', {}),
        })
    
    # 一键操作
    btn1, btn2, _ = st.columns([1, 1, 4])
    with btn1:
        if st.button("⭐ 一键加入自选", width='stretch', type="primary", key="lb_add_all"):
            for _, row in result_df.iterrows():
                if row["代码"] not in st.session_state.watchlist:
                    st.session_state.watchlist.append(row["代码"])
            save_watchlist(st.session_state.watchlist)
            st.success(f"已将{len(result_df)}只低吸标的加入自选！"); st.rerun()
    with btn2:
        xlsx_data = _export_df_to_xlsx(result_df.head(_lb_dyn_n))
        st.download_button(f"📥 导出Top{_lb_dyn_n}", xlsx_data, f"top{_lb_dyn_n}_lowbuy_{datetime.now().strftime('%Y%m%d')}.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", width='stretch', key="dl_lb")
    
    st.markdown("")
    _render_lowbuy_cards(result_df.head(_lb_dyn_n))

def render_stock_scorer():
    """个股评分面板：输入代码或名称，展示六大模型评分。"""
    st.markdown("### 个股评分")
    
    # 输入方式：代码或名称
    c1, c2 = st.columns([2, 3])
    with c1:
        code_input = st.text_input("股票代码", value="", placeholder="如 000001", key="ss_code")
    with c2:
        name_input = st.text_input("或输入名称关键词", value="", placeholder="如 平安银行", key="ss_name")
    
    if not code_input and not name_input:
        return
    
    # 名称→代码 模糊搜索
    target_code = None
    if code_input:
        target_code = code_input.strip().zfill(6)
    elif name_input and AKSHARE_AVAILABLE:
        try:
            name_df = ak.stock_info_a_code_name()
            matches = name_df[name_df['名称'].str.contains(name_input, na=False)]
            if len(matches) == 0:
                st.warning(f"未找到名称包含「{name_input}」的股票")
                return
            elif len(matches) == 1:
                target_code = str(matches.iloc[0]['代码']).zfill(6)
            else:
                # 多候选，让用户选
                candidates = []
                for _, r in matches.head(10).iterrows():
                    c = str(r['代码']).zfill(6)
                    n = str(r['名称'])
                    candidates.append(f"{c} - {n}")
                choice = st.selectbox("请选择股票", candidates, key="ss_choice")
                target_code = choice.split(" - ")[0]
        except Exception as e:
            st.warning(f"名称查询失败: {e}")
            return
    
    if not target_code:
        return
    
    # 开始评分
    model_order = ["chase_high", "buy_low", "golden_cross", "resonance", "canslim", "dilemma_reversal", "oversold_rebound"]
    
    # 先获取一次基本行情确认股票存在
    with st.spinner("正在获取行情数据..."):
        row_dict, _ = _find_stock_row(target_code)
        if row_dict is None:
            st.error(f"未找到股票 {target_code}，请检查代码是否正确或稍后重试")
            return
        stock_name = str(row_dict.get('名称', ''))
        stock_close = float(row_dict.get('最新价', 0) or 0)
        stock_chg = float(row_dict.get('涨跌幅', 0) or 0)
    
    # 股票基本信息
    chg_sign = "+" if stock_chg >= 0 else ""
    chg_color = "#E53935" if stock_chg > 0 else ("#2E7D32" if stock_chg < 0 else "#666")
    st.markdown(f"""
    <div style="background:white;border-radius:12px;padding:14px 20px;margin:8px 0;
    border:1px solid #E0E0E0;display:flex;align-items:center;gap:16px;">
    <div><span style="font-size:20px;font-weight:700;color:#333;">{stock_name}</span>
    <span style="font-size:13px;color:#999;margin-left:8px;">{target_code}</span></div>
    <div><span style="font-size:22px;font-weight:700;color:#333;">{stock_close:.2f}</span>
    <span style="font-size:15px;color:{chg_color};margin-left:6px;">{chg_sign}{stock_chg:.2f}%</span></div>
    </div>
    """, unsafe_allow_html=True)
    
    # 逐个模型评分
    with st.spinner("正在计算各模型评分..."):
        all_results = {}
        for model in model_order:
            try:
                result = score_single_stock(target_code, model)
                all_results[model] = result
            except Exception as e:
                all_results[model] = {"success": False, "error": str(e)}
    
    # 4行网格展示（7个模型：3行×2 + 1行×1）
    total_models = len(model_order)
    grid_rows = (total_models + 1) // 2
    for row_idx in range(grid_rows):
        cols = st.columns(2)
        for col_idx in range(2):
            model_idx = row_idx * 2 + col_idx
            if model_idx >= len(model_order):
                break
            model = model_order[model_idx]
            result = all_results.get(model, {"success": False, "error": "未计算"})
            label = MODEL_LABELS.get(model, model)
            color = COLOR_SCHEME[model_idx]
            
            with cols[col_idx]:
                if not result.get("success"):
                    st.metric(label=label, value="N/A", delta=result.get("error", "获取失败"))
                    continue
                
                total = result.get("total", 0)
                max_s = result.get("max_score", 100)
                pct = min(total / max_s, 1.0) if max_s > 0 else 0
                
                # 进度条
                bar_color = "#E74C3C" if pct < 0.3 else ("#F39C12" if pct < 0.6 else "#27AE60")
                st.markdown(f"""
                <div style="margin-bottom:4px;">
                <span style="font-weight:600;color:{color};font-size:15px;">{label}</span>
                <span style="float:right;font-size:24px;font-weight:700;color:#333;">{total}</span>
                <span style="float:right;font-size:12px;color:#999;margin-right:4px;margin-top:10px;">/ {max_s}</span>
                </div>
                <div style="background:#EEE;border-radius:6px;height:8px;margin-bottom:8px;">
                <div style="width:{pct*100:.0f}%;background:{bar_color};height:100%;border-radius:6px;"></div>
                </div>
                """, unsafe_allow_html=True)
                
                # 各维度明细
                dims = result.get("dims", {})
                if dims:
                    dim_lines = []
                    for dk, dv in dims.items():
                        dim_label = dk.replace("C_","").replace("A_","").replace("N_","").replace("S_","").replace("L_","").replace("I_","").replace("M_","").replace("L1_","L1 ").replace("L2_","L2 ").replace("L3_","L3 ").replace("L4_","L4 ")
                        dim_lines.append(f"{dim_label}: **{dv}**")
                    st.markdown("<span style='font-size:11px;color:#666;'>" + " &nbsp;|&nbsp; ".join(dim_lines) + "</span>", unsafe_allow_html=True)
                
                # 额外信息
                extra_parts = []
                if result.get("signal"):
                    extra_parts.append(f"信号: {result['signal']}")
                if result.get("position_msg"):
                    extra_parts.append(result["position_msg"])
                if result.get("filter_msg") and not result.get("pass", True):
                    extra_parts.append(f"过滤: {result['filter_msg']}")
                if extra_parts:
                    st.markdown("<span style='font-size:11px;color:#888;'>" + " &nbsp;|&nbsp; ".join(extra_parts) + "</span>", unsafe_allow_html=True)

def render_detail(code):
    d = get_stock_detail(code)
    if not d:
        st.error("未找到数据"); return
    
    cb, ct = st.columns([1, 5])
    with cb:
        if st.button("← 返回列表", width='stretch', key="detail_back"):
            st.session_state.selected_stock = None; st.rerun()
    with ct:
        sig_color = {"强势买入":"#E74C3C","逢低吸纳":"#E67E22","观望等待":"#27AE60","建议回避":"#888"}.get(d.get('信号',''), "#666")
        st.markdown(f"""<div class="header-container" style="margin-top:0;">
        <div class="main-title">{d['名称']}
        <span style="font-size:14px;font-weight:400;color:#888;">{d['代码']} · 综合<b style='color:#C4842D;'>{d.get('综合评分','N/A')}</b>分 · {d.get('板块','')}</span>
        <span class="metric-badge" style="background:{sig_color};color:white;margin-left:10px;">{d.get('信号','')}</span>
        </div></div>""", unsafe_allow_html=True)

    mc = st.columns(3)
    met = [
        ("5日涨幅", d.get("5日涨幅","N/A"), "up" if "+" in str(d.get("5日涨幅","")) else "down"),
        ("20日涨幅", d.get("20日涨幅","N/A"), "up" if "+" in str(d.get("20日涨幅","")) else "down"),
        ("量比", d.get("量比_显示","N/A"), "neutral"),
        ("换手率", d.get("换手率_显示","N/A"), "neutral"),
        ("RSI-14", d.get("RSI_显示","N/A"), "neutral"),
        ("PE(TTM)", d.get("PE_显示","N/A"), "neutral"),
    ]
    for i, (nm, vl, mood) in enumerate(met):
        with mc[i%3]:
            cls = "up" if mood == "up" else "down" if mood == "down" else ""
            st.markdown(f"""<div class="detail-metric-card"><div class="metric-name">{nm}</div><div class="metric-value {cls}">{vl}</div></div>""", unsafe_allow_html=True)

    dims = ["趋势结构","动量强度","板块共振","北向资金","机构净买","板块资金热度","量价配合","估值安全","筹码稳定","情绪热度"]
    clrs = [WEIGHT_CONFIG.get(d, {}).get("color", "#666") for d in dims]
    
    st.markdown("<hr style='margin:20px 0;border:none;border-top:1px solid #EEE;'>", unsafe_allow_html=True)
    st.markdown("**📊 十维评分详情(v4)**")
    _dc1 = st.columns(5)
    for co, dm, cr in zip(_dc1, dims[:5], clrs[:5]):
        with co:
            sc = d.get(dm, 50); wt = st.session_state.weights.get(dm, 20)
            st.markdown(f"""<div class="detail-metric-card" style="text-align:center;">
            <div class="metric-name">{dm}</div>
            <div style="font-size:26px;font-weight:800;color:{cr};margin:4px 0;">{sc}<span style="font-size:14px;">分</span></div>
            <div style="font-size:11px;color:#999;">权重 {wt}%</div>
            <div style="margin-top:8px;"><div class="score-bar"><div class="score-fill" style="width:{sc}%;background:{cr};"></div></div></div>
            </div>""", unsafe_allow_html=True)
    _dc2 = st.columns(5)
    for co, dm, cr in zip(_dc2, dims[5:], clrs[5:]):
        with co:
            sc = d.get(dm, 50); wt = st.session_state.weights.get(dm, 20)
            st.markdown(f"""<div class="detail-metric-card" style="text-align:center;">
            <div class="metric-name">{dm}</div>
            <div style="font-size:26px;font-weight:800;color:{cr};margin:4px 0;">{sc}<span style="font-size:14px;">分</span></div>
            <div style="font-size:11px;color:#999;">权重 {wt}%</div>
            <div style="margin-top:8px;"><div class="score-bar"><div class="score-fill" style="width:{sc}%;background:{cr};"></div></div></div>
            </div>""", unsafe_allow_html=True)

    st.markdown("<hr style='margin:20px 0;border:none;border-top:1px solid #EEE;'>", unsafe_allow_html=True)
    sv = d.get("综合评分", 50)
    if sv >= 85: lv, ds = ("💰 核心龙头·重仓追高", f"综合评分 {sv} 分（v4十维），属于核心主线龙头。信号「{d.get('信号','')}」，建议重仓60%~80%。趋势 {d.get('趋势结构','N/A')}，北向 {d.get('北向资金','N/A')}，机构 {d.get('机构净买','N/A')}，板块 {d.get('板块共振','N/A')}。")
    elif sv >= 70: lv, ds = ("📈 支线趋势·轻仓试错", f"综合评分 {sv} 分（v4十维），属于支线趋势标的。信号「{d.get('信号','')}」，建议轻仓20%~40%。趋势 {d.get('趋势结构','N/A')}。")
    elif sv >= 55: lv, ds = ("⚠️ 建议观望", f"综合评分 {sv} 分（v4十维），低于70分追高门槛，建议观望。")
    else: lv, ds = ("🚫 不建议参与", f"综合评分 {sv} 分（v3八维），分数不足70，放弃不参与。")
    
    st.markdown(f"""<div class="advice-box"><div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;"><span>⚡</span><strong>{lv}</strong></div>
    <div style="font-size:14px;color:#555;line-height:1.7;">{ds}</div></div>""", unsafe_allow_html=True)

    # === K-line chart ===
    st.markdown("**K-Line**")
    _kline_df, _kline_rt = get_kline_with_today(d.get('代码', ''), days=60)
    if _kline_df is not None and len(_kline_df) > 5:
        _kline_title = f"{d.get('名称','')} ({d.get('代码','')})"
        if _kline_rt:
            _kline_title += " [盘中]"
        _kline_fig = create_candlestick_chart(_kline_df, title=_kline_title, is_realtime=_kline_rt)
        if _kline_fig:
            st.plotly_chart(_kline_fig, width='stretch', config={'displayModeBar': False})
        if _kline_rt:
            st.caption("▶ 最右侧蜡烛为今日盘中实时数据")
    else:
        st.info("K-line loading...")

    st.markdown("**📡 八维雷达图**")
    cc, cf = st.columns([3, 2])
    with cc:
        dimd = {dd: d.get(dd, 50) for dd in dims}
        radar_fig = create_radar_chart(dimd, st.session_state.weights)
        st.plotly_chart(radar_fig, width='stretch', config={'displayModeBar': False})
    with cf:
        st.markdown("**⚖️ 快速调权**")
        for dm, cr in zip(dims, clrs):
            cw = st.session_state.weights.get(dm, 20)
            mx = WEIGHT_CONFIG[dm]["max"]
            # 处理 +/- 按钮
            if st.session_state.get(f"_dinc_{dm}", False):
                st.session_state.weights[dm] = min(mx, cw + 1)
                st.session_state[f"_dinc_{dm}"] = False
                st.rerun()
            if st.session_state.get(f"_ddec_{dm}", False):
                st.session_state.weights[dm] = max(0, cw - 1)
                st.session_state[f"_ddec_{dm}"] = False
                st.rerun()
            sc1, sc2, sc3, sc4 = st.columns([0.5, 2, 0.8, 0.8])
            with sc1:
                st.markdown(f"<span style='color:{cr};font-size:13px;'>●</span>", unsafe_allow_html=True)
            with sc2:
                st.markdown(f"<span style='font-size:12px;color:#444;'>{dm}</span> <b style='color:{cr};font-size:14px;'>{cw}%</b>", unsafe_allow_html=True)
            with sc3:
                if st.button("−", key=f"ddec_{dm}"):
                    st.session_state[f"_ddec_{dm}"] = True
                    st.rerun()
            with sc4:
                if st.button("+", key=f"dinc_{dm}"):
                    st.session_state[f"_dinc_{dm}"] = True
                    st.rerun()
        if st.button("🔄 重新计算评分", width='stretch', type="primary", key="detail_recalc"):
            st.cache_data.clear(); st.rerun()

def render_watchlist():
    st.markdown("""<div class="header-container">
    <div class="main-title">⭐ 我的自选</div>
    <div class="sub-title">已自动保存至本地 · 点击股票查看详情与八维分析</div>
    </div>""", unsafe_allow_html=True)
    
    wl = st.session_state.watchlist
    if not wl:
        st.info("📭 自选股为空")
        return
    
    df = get_stock_pool()
    wl_df = df[df["代码"].isin(wl)].copy()
    if len(wl_df) == 0:
        st.warning("自选股数据加载中，请稍后刷新..."); return
    
    render_stats_chase(wl_df)
    c1, c2 = st.columns([1, 4])
    with c1:
        if st.button("🗑️ 清空自选", width='stretch', key="wl_clear_all"):
            st.session_state.watchlist = []; save_watchlist([]); st.rerun()
    with c2:
        if st.button("📤 导出自选股", width='stretch', key="wl_export_btn"):
            csv = wl_df.to_csv(index=False).encode('utf-8-sig')
            st.download_button("下载CSV", csv, "my_watchlist.csv", "text/csv", key="dl_wl")
    
    st.markdown("")
    sec, sig_filter, sw = render_filter_bar(wl_df)
    if sec != "全部": wl_df = wl_df[wl_df["板块"] == sec]
    if sig_filter is not None and sig_filter[0] == "信号": wl_df = wl_df[wl_df["信号"].isin(sig_filter[1])]
    if sw:
        m = wl_df["代码"].str.contains(sw, False) | wl_df["名称"].str.contains(sw, False)
        wl_df = wl_df[m]
    render_table_chase(wl_df.reset_index(drop=True))

def render_backtest():
    # 模型选择 — 放大字体和图标（页面中仅此一个 radio，用 role 选择器精准命中）
    st.markdown("""
    <style>
    [role="radiogroup"] label[data-baseweb="radio"] {
        font-size: 22px !important;
        padding: 8px 20px !important;
    }
    [role="radiogroup"] label[data-baseweb="radio"] > div:first-child {
        transform: scale(1.6);
        margin-right: 10px !important;
    }
    </style>
    """, unsafe_allow_html=True)
    model_options = {"resonance": "🎯 共振模型", "chase_high": "🚀 追高模型", "buy_low": "📉 低吸模型", "golden_cross": "📌 金叉模型", "canslim": "📊 CAN SLIM模型（抓主升浪股）", "dilemma_reversal": "🔄 困境反转模型（抓周期股）"}
    st.markdown('<p style="font-size:20px;font-weight:600;margin:0 0 4px 0;">回测模型</p>', unsafe_allow_html=True)
    selected_model = st.radio(" ", list(model_options.values()), horizontal=True, key="bt_model", label_visibility="collapsed")
    # Key映射表（emoji+中文 -> 内部key）
    _model_map = {
        "🎯 共振模型": "resonance",
        "🚀 追高模型": "chase_high",
        "📉 低吸模型": "buy_low",
        "📌 金叉模型": "golden_cross",
        "📊 CAN SLIM模型（抓主升浪股）": "canslim",
        "🔄 困境反转模型（抓周期股）": "dilemma_reversal",
    }
    model_key = _model_map.get(selected_model, "chase_high")

    if model_key == "chase_high":
        model_subtitle = "基于当前八维权重配置(v3)进行历史回测 · 含沪深300基准对比"
    elif model_key == "buy_low":
        model_subtitle = "基于七维低吸评分进行历史回测 · 含沪深300基准对比"
    elif model_key == "resonance":
        model_subtitle = "基于四维共振评分（K线结构+板块热度）进行历史回测 · 含沪深300基准对比"
    elif model_key == "canslim":
        model_subtitle = "基于CAN SLIM模型（抓主升浪股）七因子简化版（技术因子完整，财务因子占位）进行历史回测 · 含沪深300基准对比"
    elif model_key == "dilemma_reversal":
        model_subtitle = "基于困境反转模型（抓周期股）四层评分（L4技术资金完整，L1-L3占位）进行历史回测 · 含沪深300基准对比"
    else:
        model_subtitle = "基于五维金叉评分（下跌形态·K线止跌·均线拐头·量能确认·MACD反转）进行历史回测 · 含沪深300基准对比"

    st.markdown(f"""<div class="header-container"><div class="main-title">📈 策略回测中心</div>
    <div class="sub-title">{model_subtitle}</div></div>""", unsafe_allow_html=True)
    
    with st.expander("⚙️ 回测参数配置", expanded=True):
        pc1, pc2, pc3, pc4 = st.columns(4)
        with pc1: sd = st.date_input("起始日期", value=pd.Timestamp("2026-06-01").date(), key="bt_start")
        with pc2: ed = st.date_input("结束日期", value=datetime.now().date(), key="bt_end")
        with pc3: top_n = st.selectbox("持仓数量", [3,5,10,15,20], index=2, key="bt_topn")
        with pc4: min_sc = st.selectbox("最低评分", [50,55,60,65,70], index=2, key="bt_minsc")
    with st.expander("📉 五层卖出参数", expanded=False):
        sp1, sp2 = st.columns(2)
        with sp1:
            bt_stop_loss = st.slider("止损比例 (%)", min_value=1, max_value=15, value=5, step=1, key="bt_stop_loss",
                help="持仓跌幅超过此比例立即止损卖出")
            bt_hard_tp = st.slider("硬止盈低档 (%)", min_value=5, max_value=25, value=12, step=1, key="bt_hard_tp",
                help="盈利达标且共振<50时止盈卖出")
            bt_hard_tp_ceiling = st.slider("硬止盈天花板 (%)", min_value=15, max_value=70, value=35, step=5, key="bt_hard_tp_ceiling",
                help="盈利超过此比例无条件卖出")
            bt_moving_gain = st.slider("移动止盈激活线 (%)", min_value=3, max_value=25, value=15, step=1, key="bt_moving_gain",
                help="峰值盈利超过此比例后启动移动止盈监控")
        with sp2:
            bt_moving_dd = st.slider("移动止盈回撤线 (%)", min_value=1, max_value=12, value=7, step=1, key="bt_moving_dd",
                help="从峰值回撤超过此比例触发移动止盈")
            bt_cooling = st.slider("冷却期 (天)", min_value=1, max_value=10, value=5, step=1, key="bt_cooling",
                help="持仓前N天共振不参与卖出判断")
            bt_resonance = st.slider("共振卖出阈值", min_value=20, max_value=60, value=40, step=5, key="bt_resonance",
                help="冷却期后共振评分低于此值触发卖出")
            bt_min_score_pct = st.slider("得分门槛 (Z-Score)", min_value=0.0, max_value=3.0, value=1.0, step=0.1, key="bt_min_score_pct",
                help="只买入得分超过当日均值N个标准差的股票，0=不过滤。行情差时自动空仓")
    pcc1, _ = st.columns([3, 1])
    with pcc1: rebal = st.selectbox("调仓周期", ["每周(5交易日)","每两周(10交易日)","每月(20交易日)"], index=0, key="bt_rebal")

    st.markdown(f"""<div style="background:#FFFBF5;border:1px solid #E8DCC8;border-radius:10px;padding:14px 20px;margin:12px 0;">
    <span style="font-weight:700;color:#C4842D;">📋 当前权重配置：</span>""", unsafe_allow_html=True)
    ws = []; tw = 0
    if model_key == "chase_high" or model_key in ("canslim", "dilemma_reversal"):
        for dk, dv in WEIGHT_CONFIG.items():
            wv = st.session_state.weights.get(dk, dv["default"]); tw += wv
            ws.append(f"<span style='color:{dv['color']}'><b>{dk}</b> {wv}%</span>")
    elif model_key == "buy_low":
        for dk, dv in LOWBUY_WEIGHT_CONFIG.items():
            wv = st.session_state.get("lowbuy_weights", DEFAULT_LOWBUY_WEIGHTS).get(dk, dv["default"]); tw += wv
            ws.append(f"<span style='color:{dv['color']}'><b>{dk}</b> {wv}%</span>")
    elif model_key == "resonance":
        ws.append(f"<span style='color:#00897B'><b>资金流向</b> 30%</span>")
        ws.append(f"<span style='color:#1565C0'><b>DDE决策</b> 20%</span>")
        ws.append(f"<span style='color:#E65100'><b>K线结构</b> 25%</span>")
        ws.append(f"<span style='color:#6A1B9A'><b>板块热度</b> 25%</span>")
        tw = 100
    else:  # golden_cross
        for dk, dv in DEFAULT_GC_WEIGHTS.items():
            wv = st.session_state.get("gc_weights", dict(DEFAULT_GC_WEIGHTS)).get(dk, dv)
            tw += wv
            ws.append(f"<span style='color:#C4842D'><b>{dk}</b> {wv}%</span>")
    st.markdown("  ".join(ws) + f"&nbsp;&nbsp;|&nbsp;&nbsp;<b>合计:{tw}%</b></div>", unsafe_allow_html=True)
    
    btn1, _, btn3 = st.columns([1, 2, 1])
    with btn1: run_bt = st.button("▶️ 开始回测", width='stretch', type="primary", key="bt_run")
    with btn3: exp_bt = st.button("💾 导出报告", width='stretch', key="bt_export")

    if run_bt:
        with st.spinner("正在运行回测... ⏳"):
            try:
                bt_start = time.time()
                bt_df = run_real_backtest_cached(str(sd), str(ed), top_n=top_n, model=model_key,
                    stop_loss=st.session_state.get('bt_stop_loss', 5) / 100.0,
                    hard_take_profit=st.session_state.get('bt_hard_tp', 12) / 100.0,
                    hard_take_profit_ceiling=st.session_state.get('bt_hard_tp_ceiling', 35) / 100.0,
                    moving_stop_gain=st.session_state.get('bt_moving_gain', 15) / 100.0,
                    moving_stop_drawdown=st.session_state.get('bt_moving_dd', 7) / 100.0,
                    cooling_period=st.session_state.get('bt_cooling', 5),
                    resonance_threshold=st.session_state.get('bt_resonance', 40),
                    min_z_score=st.session_state.get('bt_min_score_pct', 1.0))
                bt_elapsed = time.time() - bt_start
                if bt_df is not None:
                    summary = bt_df.attrs.get('summary', '')
                    metrics = calc_backtest_metrics(bt_df)
                    # 格式化耗时
                    h = int(bt_elapsed // 3600)
                    m = int((bt_elapsed % 3600) // 60)
                    s = bt_elapsed % 60
                    if h > 0:
                        elapsed_str = f"{h}小时{m}分{int(s)}秒"
                    elif m > 0:
                        elapsed_str = f"{m}分{int(s)}秒"
                    else:
                        elapsed_str = f"{s:.1f}秒"
                    st.session_state.backtest_result = (bt_df, metrics, elapsed_str)
                    extra = bt_df.attrs.get('summary', '')
                    st.success(f"✅ 回测完成！共 {len(bt_df)} 个交易日 · 耗时 {elapsed_str} | {extra}")
            except Exception as e:
                st.error(f"❌ 回测失败: {e}")

    if st.session_state.get('backtest_result') and st.session_state.backtest_result[0] is not None:
        bt_result = st.session_state.backtest_result
        bt_df, metrics = bt_result[0], bt_result[1]
        elapsed_str = bt_result[2] if len(bt_result) > 2 else ""
        if metrics and len(bt_df) > 0:
            st.subheader("📊 核心绩效指标")
            # 时间标签
            if '日期' in bt_df.columns:
                bt_start = bt_df['日期'].min()
                bt_end = bt_df['日期'].max()
                extra_tag = f" · ⏱️ 耗时 {elapsed_str}" if elapsed_str else ""
                st.markdown(f"""<div style="text-align:center;margin-bottom:18px;">
                <span style="background:#F5F0EA;color:#8B7355;padding:6px 22px;border-radius:20px;font-size:13px;font-weight:600;">
                📅 {bt_start.strftime('%Y-%m-%d')} ~ {bt_end.strftime('%Y-%m-%d')} · {len(bt_df)}个交易日{extra_tag}
                </span></div>""", unsafe_allow_html=True)
            
            last_row = bt_df.iloc[-1]
            _sp_df = bt_df.attrs.get("stock_profit_list")
            
            # 第一行：投资回报率 — 放大醒目（ROI = 总盈利 / 峰值资金投入）
            total_profit = _sp_df[_sp_df['代码'].notna() & (_sp_df['代码'] != '合计')]['单笔收益'].sum() if _sp_df is not None and len(_sp_df) > 0 else 0.0
            max_deployed_val = bt_df.attrs.get("max_deployed", bt_df.attrs.get("avg_deployed", 1))
            roi_val_pct = (total_profit / max_deployed_val * 100) if max_deployed_val > 0 else 0
            roi_val = f"{roi_val_pct:+.2f}%"
            roi_color = "positive" if roi_val_pct >= 0 else "negative"
            st.markdown(f"""<div style="text-align:center;margin-bottom:16px;">
            <div class="bt-stat-card" style="display:inline-block;padding:20px 40px;">
            <div class="bt-label" style="font-size:16px;">投资回报率 (ROI)</div>
            <div class="bt-val {roi_color}" style="font-size:48px;line-height:1.2;">{roi_val}</div>
            <div style="font-size:12px;color:gray;margin-top:4px;">ROI = 总盈利 ÷ 峰值资金投入</div>
            </div></div>""", unsafe_allow_html=True)
            
            # 第二行：胜率 | 超额收益 | 月均收益 | 年化收益
            stat_row2 = st.columns(4)
            items2 = [
                ("胜率", metrics['胜率'], f"超额{metrics['超额胜率']}", "positive" if metrics['win_rate_raw']>=0.55 else "neutral"),
                ("超额收益", metrics['超额收益'], "vs沪深300", "positive" if metrics.get('alpha_raw',0)>=0 else "negative"),
                ("月均收益", metrics['月均收益'], "", "neutral"),
                ("年化收益", metrics['年化收益率'], "", "positive" if metrics.get('ann_ret_raw',0)>=0 else "negative"),
            ]
            for col, (lbl, val, sub, cc) in zip(stat_row2, items2):
                with col:
                    st.markdown(f"""<div class="bt-stat-card"><div class="bt-label">{lbl}</div><div class="bt-val {cc}">{val}</div><div class="bt-sub">{sub}</div></div>""", unsafe_allow_html=True)
            
            # 第三行：交易天数 | 峰值资金投入 | 平均资金投入 | 累计买入总额 | 选股数量 | 期末组合净值
            max_deployed_val = bt_df.attrs.get("max_deployed", bt_df['持仓数'].max() * 10000 * (1 + backtest_engine.TRADING_COST))
            avg_deployed_val2 = bt_df.attrs.get("avg_deployed", max_deployed_val)
            total_invested_val = bt_df.attrs.get("total_invested", 0)
            stat_row3 = st.columns(6)
            items3 = [
                ("交易天数", f"{len(bt_df)} 天", "", "neutral"),
                ("峰值资金投入", f"¥{max_deployed_val:,.2f}", "", "neutral"),
                ("平均资金投入", f"¥{avg_deployed_val2:,.2f}", "", "neutral"),
                ("累计买入总额", f"¥{total_invested_val:,.2f}", "", "neutral"),
                ("选股数量", f"{int(last_row['持仓数'])} 只", "", "neutral"),
                ("期末组合净值", f"¥{last_row['组合净值']:,.2f}", "", "neutral"),
            ]
            for col, (lbl, val, sub, cc) in zip(stat_row3, items3):
                with col:
                    st.markdown(f"""<div class="bt-stat-card"><div class="bt-label">{lbl}</div><div class="bt-val {cc}">{val}</div><div class="bt-sub">{sub}</div></div>""", unsafe_allow_html=True)
            
            # 第四行：基准收益 | 年化波动 | 夏普比率 | 卡玛比率
            stat_row4 = st.columns(4)
            items4 = [
                ("基准收益", metrics['基准累计收益'], "", "neutral"),
                ("年化波动", metrics['年化波动率'], "", "neutral"),
                ("夏普比率", str(metrics['夏普比率']), ">1优秀", "positive" if metrics['sharpe_raw']>=1 else "neutral"),
                ("卡玛比率", str(metrics['卡玛比率']), "", "neutral"),
            ]
            for col, (lbl, val, sub, cc) in zip(stat_row4, items4):
                with col:
                    st.markdown(f"""<div class="bt-stat-card"><div class="bt-label">{lbl}</div><div class="bt-val {cc}">{val}</div><div class="bt-sub">{sub}</div></div>""", unsafe_allow_html=True)

            st.markdown("")
            # 股票收益清单
            stock_profit_df = bt_df.attrs.get("stock_profit_list")
            if stock_profit_df is not None and len(stock_profit_df) > 0:
                st.subheader("📋 股票收益清单")
                # 格式化显示列
                show_df = stock_profit_df.copy()
                show_df["投入金额"] = show_df["投入金额"].apply(lambda x: f"¥{x:,.0f}" if isinstance(x, (int, float)) and x != 0 else x)
                show_df["单笔收益"] = show_df["单笔收益"].apply(lambda x: f"¥{x:+,.2f}" if isinstance(x, (int, float)) else x)
                show_df["单笔收益率"] = show_df["单笔收益率"].apply(lambda x: f"{x*100:+.2f}%" if isinstance(x, (int, float)) else x)
                st.dataframe(show_df, width='stretch', 
                    height=min(35 * len(show_df) + 38, 600), hide_index=True)
                st.markdown("")

                # 下载 Excel（三 Sheet）
                from io import BytesIO
                max_dep = bt_df.attrs.get("max_deployed", bt_df['持仓数'].max() * 10000 * (1 + backtest_engine.TRADING_COST))
                avg_dep = bt_df.attrs.get("avg_deployed", max_dep)
                total_inv = bt_df.attrs.get("total_invested", 0)
                total_profit_excel = stock_profit_df[stock_profit_df['代码'].notna() & (stock_profit_df['代码'] != '合计')]['单笔收益'].sum() if stock_profit_df is not None and len(stock_profit_df) > 0 else 0.0
                roi_excel = total_profit_excel / max_dep if max_dep > 0 else 0
                summary_for_excel = pd.DataFrame({
                    "--- 汇总统计 ---": ["回测起始日期", "回测结束日期", "盈利金额", "峰值资金投入", "平均资金投入", "累计买入总额", "ROI (总盈利÷峰值资金)", "胜率", "持仓股票数量", "交易天数"],
                    "": [
                        str(bt_start.date()),
                        str(bt_end.date()),
                        total_profit_excel,
                        max_dep,
                        avg_dep,
                        total_inv,
                        roi_excel,
                        metrics.get('胜率', 'N/A'),
                        int(last_row['持仓数']),
                        len(bt_df),
                    ],
                })
                detail_cols = ["日期","累计投入","组合净值","基准净值","日收益率",
                             "基准日收益率","累计收益率","基准累计收益","超额收益",
                             "最大回撤","持仓数"]
                daily_df = bt_df[detail_cols].copy()
                daily_df["日收益率"] = daily_df["日收益率"].apply(lambda x: f"{x*100:+.2f}%")
                daily_df["基准日收益率"] = daily_df["基准日收益率"].apply(lambda x: f"{x*100:+.2f}%")
                daily_df["累计收益率"] = daily_df["累计收益率"].apply(lambda x: f"{x*100:+.2f}%")
                daily_df["基准累计收益"] = daily_df["基准累计收益"].apply(lambda x: f"{x*100:+.2f}%")
                daily_df["超额收益"] = daily_df["超额收益"].apply(lambda x: f"{x*100:+.2f}%")
                daily_df["最大回撤"] = daily_df["最大回撤"].apply(lambda x: f"{x*100:.2f}%")

                output = BytesIO()
                with pd.ExcelWriter(output, engine='openpyxl') as writer:
                    summary_for_excel.to_excel(writer, sheet_name='股票收益分析汇总', index=False)
                    stock_profit_df.to_excel(writer, sheet_name='股票收益清单', index=False)
                    daily_df.to_excel(writer, sheet_name='回测日明细', index=False)

                    # --- 盈利/亏损背景色 ---
                    from openpyxl.styles import PatternFill
                    GREEN_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")  # 浅绿
                    RED_FILL   = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")  # 浅红
                    WHITE_FILL = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")

                    def _auto_width(ws, min_width=8, max_width=28):
                        for col_cells in ws.columns:
                            col_letter = col_cells[0].column_letter
                            max_len = max((len(str(c.value or "")) for c in col_cells), default=0)
                            ws.column_dimensions[col_letter].width = max(min_width, min(max_len * 1.7 + 2, max_width))

                    # 1. 股票收益清单：格式 + 着色
                    ws_stock = writer.sheets['股票收益清单']
                    _auto_width(ws_stock)
                    cols_stock = [c.value for c in ws_stock[1]]  # header row
                    # 数字格式化
                    fmt_map = {
                        "投入金额": '#,##0.00',
                        "买入价": '0.00',
                        "卖出价/收盘价": '0.00',
                        "单笔收益": '#,##0.00',
                        "单笔收益率": '0.00%',
                    }
                    for i, h in enumerate(cols_stock):
                        if h in fmt_map:
                            for row in ws_stock.iter_rows(min_row=2, max_row=ws_stock.max_row):
                                cell = row[i]
                                if isinstance(cell.value, (int, float)):
                                    cell.number_format = fmt_map[h]
                    # 着色
                    profit_col_idx = None
                    for i, h in enumerate(cols_stock):
                        if h in ("单笔收益",):
                            profit_col_idx = i + 1  # 1-based
                            break
                    if profit_col_idx:
                        for row in ws_stock.iter_rows(min_row=2, max_row=ws_stock.max_row):
                            val = row[profit_col_idx - 1].value
                            if isinstance(val, (int, float)):
                                fill = GREEN_FILL if val > 0 else RED_FILL if val < 0 else WHITE_FILL
                                for cell in row:
                                    cell.fill = fill

                    # 2. 股票收益分析汇总：数字格式化 + 着色
                    ws_sum = writer.sheets['股票收益分析汇总']
                    _auto_width(ws_sum)
                    # 金额列格式化
                    money_labels = {"初始资金", "盈利金额", "峰值资金投入", "平均资金投入", "累计买入总额", "期末组合净值"}
                    for row in ws_sum.iter_rows(min_row=2, max_row=ws_sum.max_row):
                        label = str(row[0].value or "")
                        data_cell = row[1]
                        if label in money_labels and isinstance(data_cell.value, (int, float)):
                            data_cell.number_format = '#,##0.00'
                        elif ("ROI" in label or "回报率" in label) and isinstance(data_cell.value, (int, float)):
                            data_cell.number_format = '0.00%'
                    # 着色
                    for row in ws_sum.iter_rows(min_row=2, max_row=ws_sum.max_row):
                        data_cell = row[1]
                        if isinstance(data_cell.value, (int, float)):
                            label = str(row[0].value or "")
                            if "ROI" in label or "回报率" in label:
                                data_cell.fill = GREEN_FILL if data_cell.value > 0 else RED_FILL if data_cell.value < 0 else WHITE_FILL

                    # 3. 回测日明细：超额收益列着色
                    ws_daily = writer.sheets['回测日明细']
                    _auto_width(ws_daily)
                    cols_daily = [c.value for c in ws_daily[1]]
                    excess_idx = None
                    for i, h in enumerate(cols_daily):
                        if h == "超额收益":
                            excess_idx = i + 1
                            break
                    if excess_idx:
                        for row in ws_daily.iter_rows(min_row=2, max_row=ws_daily.max_row):
                            cell = row[excess_idx - 1]
                            raw = cell.value
                            if isinstance(raw, str):
                                try:
                                    raw = float(raw.replace("%", "").replace("+", ""))
                                except:
                                    raw = None
                            if isinstance(raw, (int, float)):
                                cell.fill = GREEN_FILL if raw > 0 else RED_FILL if raw < 0 else WHITE_FILL

                output.seek(0)
                _name_map = {"resonance": "共振模型", "chase_high": "追高模型", "buy_low": "低吸模型", "golden_cross": "金叉模型", "canslim": "CAN_SLIM模型", "dilemma_reversal": "困境反转模型"}
                fname = f"回测分析表_{_name_map.get(model_key, '未知模型')}.xlsx"
                st.download_button(
                    "📥 下载Excel (三Sheet)",
                    output,
                    fname,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    key="bt_dl_excel",
                )
            tab1, tab2, tab3 = st.tabs(["📈 净值曲线", "🗓️ 月度收益", "📋 详细记录"])
            with tab1:
                eq_fig = create_backtest_equity_chart(bt_df, metrics)
                st.plotly_chart(eq_fig, width='stretch', config={'displayModeBar': True})
            with tab2:
                hm_fig = create_monthly_heatmap(bt_df)
                st.plotly_chart(hm_fig, width='stretch', config={'displayModeBar': False})
            with tab3:
                display_cols = ["日期","累计投入","组合净值","基准净值","日收益率",
                                "基准日收益率","累计收益率","基准累计收益","超额收益",
                                "最大回撤","持仓数"]
                # 兼容新旧列名：优先用拆分列，回退到旧列
                new_trade_cols = ["今日买入","今日卖出","当前持仓"]
                for c in new_trade_cols:
                    if c in bt_df.columns:
                        display_cols.append(c)
                if not any(c in bt_df.columns for c in new_trade_cols) and "持仓明细" in bt_df.columns:
                    display_cols.append("持仓明细")
                if "持仓收盘价" in bt_df.columns:
                    display_cols.append("持仓收盘价")
                detail_df = bt_df[display_cols].copy()
                detail_df["日收益率"] = detail_df["日收益率"].apply(lambda x: f"{x*100:+.2f}%")
                detail_df["基准日收益率"] = detail_df["基准日收益率"].apply(lambda x: f"{x*100:+.2f}%")
                detail_df["累计收益率"] = detail_df["累计收益率"].apply(lambda x: f"{x*100:+.2f}%")
                detail_df["基准累计收益"] = detail_df["基准累计收益"].apply(lambda x: f"{x*100:+.2f}%")
                detail_df["超额收益"] = detail_df["超额收益"].apply(lambda x: f"{x*100:+.2f}%")
                detail_df["最大回撤"] = detail_df["最大回撤"].apply(lambda x: f"{x*100:.2f}%")
                detail_df["组合净值"] = detail_df["组合净值"].apply(lambda x: f"¥{x:,.2f}")
                detail_df["基准净值"] = detail_df["基准净值"].apply(lambda x: f"¥{x:,.2f}")
                detail_df["累计投入"] = detail_df["累计投入"].apply(lambda x: f"¥{x:,.2f}")
                st.dataframe(detail_df, width='stretch', height=450,
                    column_config={"日期": st.column_config.DateColumn("日期", format="YYYY-MM-DD", width="medium")})
                csv_out = detail_df.to_csv(index=False).encode('utf-8-sig')
                st.download_button("📥 下载CSV", csv_out, "backtest_detail.csv", "text/csv", key="bt_dl_csv")

    st.markdown("""
    ---
    **智能选股系统 - Smart Stock Screener**
    功能：四模型选股（追高+低吸+共振+金叉）+ 个股分析 + 自选股管理 + 策略回测 + 参数可调
    数据源：pytdx通达信行情(优先) + 通达信本地数据(K线) + akshare(龙虎榜兜底) | A股全市场约6600+只股票
    """)
