"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
def calc_backtest_metrics(bt_df):
    """计算回测统计指标（含短期回测保护）"""
    if bt_df is None or len(bt_df) == 0:
        return None
    equity = bt_df["组合净值"].values.astype(float)
    benchmark = bt_df["基准净值"].values.astype(float)
    returns = bt_df["日收益率"].values.astype(float)
    benchmark_returns = bt_df["基准日收益率"].values.astype(float)
    total_days = len(bt_df)
    annual_factor = 245 / max(total_days, 1)
    cumret = float(bt_df["累计收益率"].iloc[-1])
    bench_cumret = float(bt_df["基准累计收益"].iloc[-1])
    
    # 保护：equity[0] 不能为 0 或 NaN
    e0 = float(equity[0]) if len(equity) > 0 and float(equity[0]) > 0 else 100000.0
    b0 = float(benchmark[0]) if len(benchmark) > 0 and float(benchmark[0]) > 0 else 100000.0
    
    # 年化收益率：短期回测（<60天）用简单线性年化，避免复利爆炸
    if total_days >= 60:
        ann_return = (float(equity[-1]) / e0) ** annual_factor - 1
        bench_ann = (float(benchmark[-1]) / b0) ** annual_factor - 1
    else:
        ann_return = cumret * annual_factor
        bench_ann = bench_cumret * annual_factor
    
    # 额外保护：截断极端年化值（绝对值超过1000视为异常，返回0）
    if abs(ann_return) > 1000:
        ann_return = 0.0
    if abs(bench_ann) > 1000:
        bench_ann = 0.0
    
    volatility = float(np.std(returns)) * np.sqrt(245)
    # 夏普保护：volatility 极小值
    if volatility < 1e-6:
        sharpe = 0.0
    else:
        sharpe = (ann_return - 0.03) / volatility
    
    alpha = ann_return - bench_ann
    # 短期回测（<60天）：超额收益和月均收益失真，显示为 N/A
    if total_days < 60:
        alpha_str = "N/A（数据不足）"
    else:
        alpha_str = f"{alpha*100:+.1f}%"
    
    max_dd = float(bt_df["最大回撤"].max())
    win_days = sum(1 for r in returns if r > 0)
    win_rate = win_days / max(len(returns), 1)
    losing_streak = 0; max_loss_streak = 0
    for r in returns:
        if r <= 0: losing_streak += 1; max_loss_streak = max(max_loss_streak, losing_streak)
        else: losing_streak = 0
    excess_wins = sum(1 for s, b in zip(returns, benchmark_returns) if s > b)
    excess_win_rate = excess_wins / max(len(returns), 1)
    bt_df_copy = bt_df.copy()
    bt_df_copy["日期"] = pd.to_datetime(bt_df_copy["日期"])
    monthly = bt_df_copy.resample('ME', on='日期').apply(lambda x: (x["组合净值"].iloc[-1] / x["组合净值"].iloc[0] - 1) if len(x) > 1 else 0)
    monthly_str = "N/A（数据不足）" if total_days < 60 else f"{monthly.mean()*100:.2f}%"
    # 卡玛保护：max_dd 极小值
    if max_dd < 1e-6:
        calmar = 0.0
    else:
        calmar = ann_return / max_dd
    
    return {
        "初始资金": 100000, "期末资金": round(float(equity[-1]), 0), "基准期末": round(float(benchmark[-1]), 0),
        "累计收益率": f"{cumret*100:+.1f}%", "基准累计收益": f"{bench_cumret*100:+.1f}%",
        "超额收益": alpha_str, "年化收益率": f"{ann_return*100:+.1f}%",
        "基准年化": f"{bench_ann*100:+.1f}%", "最大回撤": f"{max_dd*100:.1f}%",
        "夏普比率": round(sharpe, 2), "卡玛比率": round(calmar, 2),
        "年化波动率": f"{volatility*100:.1f}%", "胜率": f"{win_rate*100:.1f}%",
        "超额胜率": f"{excess_win_rate*100:.1f}%", "交易天数": total_days,
        "最大连亏天数": max_loss_streak, "月均收益": monthly_str,
        "月胜率": f"{(monthly>0).sum()/max(len(monthly),1)*100:.0f}%",
        "cumret_raw": cumret, "ann_ret_raw": ann_return, "sharpe_raw": sharpe,
        "dd_raw": max_dd, "win_rate_raw": win_rate, "alpha_raw": alpha,
        "excess_win_rate_raw": excess_win_rate,
    }
