"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import BASE_DIR, _app_cache
import backtest_engine
from core.screener import get_stock_pool, get_stock_pool_chase_high, score_single_stock
from core.scoring.chase_high import calculate_v3_total_score
from core.scoring.lowbuy import calculate_lowbuy_score
from data.cache import save_cache_data
from data.market import get_stock_kline, get_kline_with_today
from data.tdx_provider import tdx_available, get_full_name_map as tdx_get_full_name_map, fetch_kline_tdx

def run_real_backtest_cached(start_date, end_date, top_n, model='chase_high',
                stop_loss=0.05, hard_take_profit=0.12, hard_take_profit_ceiling=0.35,
                moving_stop_gain=0.15, moving_stop_drawdown=0.07, cooling_period=5,
                resonance_threshold=40, min_z_score=1.0):
    """调用真实回测引擎并转换为UI格式"""
    _trades, _daily, _sels = backtest_engine.run_backtest(
        start_date, end_date, top_n=top_n, model=model,
        stop_loss=stop_loss, hard_take_profit=hard_take_profit,
        hard_take_profit_ceiling=hard_take_profit_ceiling,
        moving_stop_gain=moving_stop_gain, moving_stop_drawdown=moving_stop_drawdown,
        cooling_period=cooling_period, resonance_threshold=resonance_threshold,
        min_z_score=min_z_score
    )
    if _daily is None or len(_daily) == 0:
        return None

    # 加载股票代码→名称映射（多源合并，确保覆盖600xxx等遗漏代码）
    import json
    code_to_name = {}
    # 源1: 本地缓存文件
    try:
        cache_path = os.path.join(BASE_DIR, 'market_data_cache.json')
        with open(cache_path, 'r', encoding='utf-8') as f:
            cache = json.load(f)
        for item in cache.get('data', []):
            code_to_name[str(item['代码']).zfill(6)] = item['名称']
    except Exception:
        pass
    # 源2: pytdx get_security_list（覆盖全量，含600xxx）
    try:
        if tdx_available():
            tdx_names = tdx_get_full_name_map()
            for c, n in tdx_names.items():
                if c not in code_to_name:
                    code_to_name[c] = n
    except Exception:
        pass
    # 源3: 模块级缓存的实时行情数据
    try:
        raw_df = _app_cache.get('raw_market_data')
        if raw_df is not None and '代码' in raw_df.columns and '名称' in raw_df.columns:
            for _, r in raw_df.iterrows():
                c = str(r['代码']).zfill(6)
                if c not in code_to_name:
                    code_to_name[c] = r['名称']
    except Exception:
        pass
    # 源4: backtest_engine 内置名称加载器（TDX文件 + pytdx多服务器兜底）
    try:
        be_names = backtest_engine.load_stock_names()
        for c, n in be_names.items():
            if c not in code_to_name:
                code_to_name[c] = n
    except Exception:
        pass

    # 使用部署资金（总投入，含卖出后循环再投）
    pv_list = _daily["portfolio_value"].values.astype(float)
    cum_total_inv_list = _daily["total_invested"].values.astype(float)
    base_equity = 10_000_000

    max_deployed = max(cum_total_inv_list) if len(cum_total_inv_list) > 0 else 10000.0 * top_n
    if max_deployed <= 0:
        max_deployed = 1.0

    # 平均资金投入：仅统计有投入的交易日
    nonzero_mask = cum_total_inv_list > 0
    avg_deployed = float(np.mean(cum_total_inv_list[nonzero_mask])) if nonzero_mask.any() else 0.0

    # 累计收益率 = (组合净值 - 初始资金) / 峰值资金（策略实际需要的资金上限）
    cum_rets = np.zeros(len(pv_list))
    for i in range(len(pv_list)):
        cum_rets[i] = (float(pv_list[i]) - backtest_engine.INITIAL_CAPITAL) / max_deployed

    daily_rets = np.zeros(len(pv_list))
    daily_rets[1:] = cum_rets[1:] - cum_rets[:-1]
    if nonzero_mask.any():
        first_idx = nonzero_mask.argmax()
        if first_idx < len(pv_list):
            daily_rets[first_idx] = cum_rets[first_idx]

    bench_rets = _daily["benchmark_return"].values.astype(float)
    bench_cum = np.cumprod(1 + bench_rets)

    peak = np.maximum.accumulate(np.maximum(pv_list, 0))
    dds = np.where(peak > 0, (peak - pv_list) / peak, 0)

    total_pnl = 0.0
    win_trades = 0
    if _trades is not None and len(_trades) > 0:
        total_pnl = float(_trades["pnl"].sum())
        win_trades = int((_trades["pnl"] > 0).sum())

    records = []
    for j in range(len(_daily)):
        d = _daily.iloc[j]
        # 持仓明细注入名称
        raw_detail = str(d.get("positions_detail", ""))
        if raw_detail and code_to_name:
            parts = []
            for seg in raw_detail.split(", "):
                if "@" in seg:
                    code, price = seg.split("@", 1)
                    name = code_to_name.get(code, "")
                    parts.append(f"{code}{name}@{price}" if name else seg)
                else:
                    parts.append(seg)
            raw_detail = ", ".join(parts)

        # 持仓收盘价明细（注入名称）
        raw_close = str(d.get("positions_close", ""))
        if raw_close and code_to_name:
            parts = []
            for seg in raw_close.split(", "):
                if "@" in seg:
                    code, price = seg.split("@", 1)
                    name = code_to_name.get(code, "")
                    parts.append(f"{code}{name}@{price}" if name else seg)
                else:
                    parts.append(seg)
            raw_close = ", ".join(parts)

        # 今日买入 / 今日卖出 / 当前持仓 注入名称
        def _fmt_bought(bought_list):
            if not bought_list:
                return ""
            parts = []
            for item in bought_list:
                c = str(item.get("code", "")).zfill(6)
                n = code_to_name.get(c, "")
                parts.append(f"{c}{n}@{item.get('buy_price',0):.2f}" if n else f"{c}@{item.get('buy_price',0):.2f}")
            return ", ".join(parts)

        def _fmt_sold(sold_list):
            if not sold_list:
                return ""
            parts = []
            for item in sold_list:
                c = str(item.get("code", "")).zfill(6)
                n = code_to_name.get(c, "")
                core = f"{item.get('buy_price',0):.2f}→{item.get('sell_price',0):.2f}"
                parts.append(f"{c}{n} {core}" if n else f"{c} {core}")
            return ", ".join(parts)

        def _fmt_current(pos_detail_str):
            if not pos_detail_str or pos_detail_str == "空仓":
                return ""
            parts = []
            for seg in pos_detail_str.split(", "):
                if "@" in seg:
                    code, price = seg.split("@", 1)
                    c = code.strip()
                    n = code_to_name.get(c, "")
                    parts.append(f"{c}{n}@{price}" if n else seg)
                else:
                    parts.append(seg)
            return ", ".join(parts)

        bought_str = _fmt_bought(d.get("bought_today", []))
        sold_str = _fmt_sold(d.get("sold_today", []))
        current_str = _fmt_current(raw_detail)

        records.append({
            "日期": pd.to_datetime(d["date"]),
            "累计投入": round(cum_total_inv_list[j], 2),
            "组合净值": round(pv_list[j] if pv_list[j] > 0 else base_equity, 2),
            "基准净值": round(base_equity * bench_cum[j], 2),
            "日收益率": round(daily_rets[j], 6),
            "基准日收益率": round(bench_rets[j], 6),
            "累计收益率": round(cum_rets[j], 6),
            "基准累计收益": round(bench_cum[j] - 1, 6),
            "超额收益": round(cum_rets[j] - (bench_cum[j] - 1), 6),
            "最大回撤": round(float(dds[j]), 6),
            "基准最大回撤": 0,
            "持仓数": int(d["num_positions"]),
            "今日买入": bought_str,
            "今日卖出": sold_str,
            "当前持仓": current_str,
            "持仓明细": raw_detail,
            "持仓收盘价": raw_close,
        })

    _bt_df = pd.DataFrame(records)
    _bt_df.attrs["max_deployed"] = max_deployed
    _bt_df.attrs["avg_deployed"] = avg_deployed
    _bt_df.attrs["total_invested"] = float(_daily["total_invested"].iloc[-1]) if "total_invested" in _daily.columns else 0.0
    _bt_df.attrs["summary"] = (
        f"策略: 止损{backtest_engine.STOP_LOSS*100:.0f}%/硬止盈{backtest_engine.HARD_TAKE_PROFIT*100:.0f}%/移动止盈{backtest_engine.MOVING_STOP_GAIN*100:.0f}%→回撤{backtest_engine.MOVING_STOP_DRAWDOWN*100:.0f}% | "
        f"交易: {len(_trades) if _trades is not None else 0}笔 | "
        f"盈亏: {total_pnl:+,.0f}元 | "
        f"胜率: {win_trades}/{max(len(_trades),1)}笔"
    )
    # 生成股票收益清单
    PER_STOCK = 10000
    stock_list = []
    # FIX: 使用 (code, buy_date) 精确匹配卖出记录，避免同一股票二次买入后被误判为已卖出
    sold_pairs = set()

    if _trades is not None and len(_trades) > 0:
        for _, t in _trades.iterrows():
            code = t['code']
            buy_date = str(t.get('buy_date', ''))[:10]
            sold_pairs.add((code, buy_date))
            name = code_to_name.get(code, code)
            buy_p = float(t['buy_price'])
            sell_p = float(t['sell_price'])
            cost = backtest_engine.TRADING_COST
            pnl_rate = (sell_p * (1 - cost)) / (buy_p * (1 + cost)) - 1
            pnl_amount = PER_STOCK * pnl_rate
            sell_date = str(t.get('sell_date', ''))[:10]
            sell_reason = t.get('sell_reason', '')
            stock_list.append({
                '买入日期': str(t.get('buy_date', ''))[:10],
                '代码': code,
                '名称': name,
                '投入金额': PER_STOCK,
                '买入价': round(buy_p, 2),
                '卖出价/收盘价': round(sell_p, 2),
                '单笔收益': round(pnl_amount, 6),
                '单笔收益率': round(pnl_rate, 6),
                '卖出原因': sell_reason,
                '卖出时间': f"{sell_date}",
            })

    # FIX: 用列表存储所有买入实例（允许同一 code 多次出现），不再用 dict 去重丢失二次买入信息
    buy_instances = []
    if _daily is not None and len(_daily) > 0:
        for _, row in _daily.iterrows():
            bt = row.get('bought_today', [])
            date = str(row['date'])[:10]
            if isinstance(bt, list):
                for b in bt:
                    buy_instances.append({
                        'code': b['code'],
                        'buy_date': date,
                        'buy_price': float(b['buy_price']),
                    })

        last_row = _daily.iloc[-1]
        pc_str = str(last_row.get('positions_close', ''))
        holdings_close = {}
        if pc_str and pc_str != '空仓':
            for item in pc_str.split(', '):
                if '@' in item:
                    parts = item.split('@')
                    try:
                        holdings_close[parts[0].strip()] = float(parts[1].strip())
                    except:
                        pass

        for bi in buy_instances:
            if (bi['code'], bi['buy_date']) in sold_pairs:
                continue
            buy_p = bi['buy_price']
            close_p = holdings_close.get(bi['code'], buy_p)
            cost = backtest_engine.TRADING_COST
            pnl_rate = close_p / (buy_p * (1 + cost)) - 1
            pnl_amount = PER_STOCK * pnl_rate
            stock_list.append({
                '买入日期': bi['buy_date'],
                '代码': bi['code'],
                '名称': code_to_name.get(bi['code'], bi['code']),
                '投入金额': PER_STOCK,
                '买入价': round(buy_p, 2),
                '卖出价/收盘价': round(close_p, 2),
                '单笔收益': round(pnl_amount, 6),
                '单笔收益率': round(pnl_rate, 6),
                '卖出原因': 'N/A',
                '卖出时间': '持仓',
            })

    stock_list.sort(key=lambda x: (x['买入日期'], x['代码']))

    # 添加期末收盘价和期末涨跌幅
    end_date_ts = pd.Timestamp(end_date)
    for s in stock_list:
        code = s['代码']
        buy_p = s['买入价']
        if s['卖出时间'] == '持仓':
            end_close = s['卖出价/收盘价']
        else:
            end_close = None
            kline_df = backtest_engine.read_tdx_day_file(code)
            if kline_df is not None and len(kline_df) > 0:
                kline_df['date'] = pd.to_datetime(kline_df['date'])
                end_rows = kline_df[kline_df['date'] == end_date_ts]
                if len(end_rows) == 0:
                    near_rows = kline_df[kline_df['date'] <= end_date_ts]
                    if len(near_rows) > 0:
                        end_close = float(near_rows['close'].iloc[-1])
                else:
                    end_close = float(end_rows['close'].iloc[0])
            if end_close is None:
                end_close = buy_p
        s['期末收盘价'] = round(end_close, 2)
        s['期末涨跌幅'] = round((end_close - buy_p) / buy_p * 100, 2)

    if stock_list:
        total_pnl_stock = sum(s['单笔收益'] for s in stock_list)
        stock_list.append({
            '买入日期': '合计',
            '代码': None,
            '名称': None,
            '投入金额': None,
            '买入价': None,
            '卖出价/收盘价': None,
            '单笔收益': round(total_pnl_stock, 6),
            '单笔收益率': None,
            '卖出原因': None,
            '卖出时间': None,
            '期末收盘价': None,
            '期末涨跌幅': None,
        })
    _bt_df.attrs['stock_profit_list'] = pd.DataFrame(stock_list)
    return _bt_df

def generate_backtest_data(start_date_str, end_date_str, top_n=5, min_score=60):
    """回测数据生成"""
    start = pd.Timestamp(start_date_str)
    end = pd.Timestamp(end_date_str)
    dates = pd.bdate_range(start=start, end=end)
    
    seed = hash((start_date_str + end_date_str + str(top_n) + str(min_score))) % (2**31)
    rng = np.random.RandomState(seed)
    
    pool_df = get_stock_pool()
    scored_pool = pool_df.sort_values("综合评分", ascending=False).reset_index(drop=True)
    candidates = scored_pool.head(top_n * 3).copy()
    n_candidates = len(candidates)
    
    results = []
    portfolio_value = 100000.0
    benchmark_value = 100000.0
    peak_val = portfolio_value
    benchmark_peak = benchmark_value
    current_holdings = []
    
    for i, dt in enumerate(dates):
        if i % 5 == 0 or i == 0:
            perturbation = rng.randn(n_candidates) * 5
            temp_scores = candidates["综合评分"].values + perturbation
            selected_indices = np.argsort(temp_scores)[-top_n:][::-1]
            current_holdings = list(selected_indices)
        
        daily_returns = []
        for idx in current_holdings:
            if idx < len(candidates):
                stock = candidates.iloc[idx]
                score_factor = (stock["综合评分"] - 50) / 500.0
                daily_ret = rng.normal(score_factor, 0.018)
                daily_returns.append({"代码": stock["代码"], "名称": stock["名称"],
                                     "评分": stock["综合评分"], "日收益率": daily_ret})
        
        port_ret = np.mean([r["日收益率"] for r in daily_returns]) if daily_returns else 0
        portfolio_value *= (1 + port_ret)
        peak_val = max(peak_val, portfolio_value)
        drawdown = (peak_val - portfolio_value) / peak_val if peak_val > 0 else 0
        
        benchmark_ret = rng.normal(0.0003, 0.015)
        benchmark_value *= (1 + benchmark_ret)
        benchmark_peak = max(benchmark_peak, benchmark_value)
        benchmark_dd = (benchmark_peak - benchmark_value) / benchmark_peak if benchmark_peak > 0 else 0
        
        results.append({
            "日期": dt.date(), "组合净值": round(portfolio_value, 2),
            "基准净值": round(benchmark_value, 2), "日收益率": round(port_ret, 5),
            "基准日收益率": round(benchmark_ret, 5),
            "累计收益率": round((portfolio_value / 100000 - 1), 5),
            "基准累计收益": round((benchmark_value / 100000 - 1), 5),
            "超额收益": round((portfolio_value / benchmark_value - 1), 5),
            "最大回撤": round(drawdown, 5), "基准最大回撤": round(benchmark_dd, 5),
            "持仓数": len(daily_returns),
            "持仓明细": [r["名称"] for r in daily_returns],
            "持仓评分": [r["评分"] for r in daily_returns],
        })
    
    return pd.DataFrame(results)
