"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
def _patch_requests_no_proxy():
    """Force all requests.Session to disable system proxy."""
    try:
        import requests
        # Patch 1: Force trust_env=False on every Session creation
        _orig_init = requests.Session.__init__
        def _no_proxy_init(self, *args, **kwargs):
            _orig_init(self, *args, **kwargs)
            self.trust_env = False
            self.proxies = {'http': '', 'https': ''}
        requests.Session.__init__ = _no_proxy_init
        # Patch 2: merge_environment_settings returns empty proxies
        _orig_merge = requests.Session.merge_environment_settings
        def _no_proxy_merge(self, url, proxies, stream, verify, cert):
            settings = _orig_merge(self, url, {}, stream, verify, cert)
            settings['proxies'] = {}
            return settings
        requests.Session.merge_environment_settings = _no_proxy_merge
    except Exception as _e:
        pass

def _patch_push2_http_fallback():
    """push2 HTTPS 直连不稳定（远端主动断开），强制将 push2 请求降级为 HTTP。
    同时禁用代理，避免系统代理干扰。
    """
    try:
        import requests

        # Patch Session.send: 强制无代理 + HTTPS→HTTP 降级
        _orig_send = requests.Session.send

        def _patched_send(self, request, **kwargs):
            # 强制禁用代理
            self.trust_env = False
            self.proxies = {'http': '', 'https': ''}
            kwargs.pop('proxies', None)

            # push2 HTTPS 降级为 HTTP
            url_lower = request.url.lower()
            if 'push2.eastmoney.com' in url_lower and url_lower.startswith('https://'):
                request.url = request.url.replace('https://', 'http://', 1)

            return _orig_send(self, request, **kwargs)

        requests.Session.send = _patched_send

        # Patch requests.get/post/head 等顶层函数（它们通过 with Session() 调用）
        _orig_request = requests.Session.request

        def _patched_request(self, method, url, **kwargs):
            self.trust_env = False
            self.proxies = {'http': '', 'https': ''}
            kwargs.pop('proxies', None)
            if 'push2.eastmoney.com' in url.lower() and isinstance(url, str) and url.lower().startswith('https://'):
                url = url.replace('https://', 'http://', 1)
            return _orig_request(self, method, url, **kwargs)

        requests.Session.request = _patched_request
    except Exception:
        pass
