"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from core.config import BASE_DIR, CACHE_DATA_JSON, DEFAULT_LOWBUY_PARAMS, DEFAULT_LOWBUY_WEIGHTS, DEFAULT_ORB_PARAMS, DEFAULT_ORB_WEIGHTS, DEFAULT_WEIGHTS, WATCHLIST_JSON

def load_watchlist():
    try:
        if os.path.exists(WATCHLIST_JSON):
            with open(WATCHLIST_JSON, 'r', encoding='utf-8') as f:
                data = json.load(f)
                return data if isinstance(data, list) else []
    except Exception as e:
        print(f"加载自选股失败: {e}")
    return []

def save_watchlist(watchlist):
    try:
        with open(WATCHLIST_JSON, 'w', encoding='utf-8') as f:
            json.dump(watchlist, f, ensure_ascii=False, indent=2)
        return True
    except Exception as e:
        print(f"保存自选股失败: {e}")
        return False

def save_cache_data(data_dict):
    """保存选股结果缓存到文件"""
    try:
        cache = {
            'timestamp': datetime.now().isoformat(),
            'chase_high_top10': data_dict.get('chase_high_top10'),
            'lowbuy_top5': data_dict.get('lowbuy_top5'),
            'lowbuy_dbg': data_dict.get('lowbuy_dbg'),
            'lowbuy_params_version': DEFAULT_LOWBUY_PARAMS.get('_params_version', 0),
            'stock_pool_columns': data_dict.get('stock_pool_columns', []),
        }
        with open(CACHE_DATA_JSON, 'w', encoding='utf-8') as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
        return True
    except Exception as e:
        print(f"保存缓存失败: {e}")
        return False

def load_cache_data():
    """加载选股结果缓存"""
    try:
        if os.path.exists(CACHE_DATA_JSON):
            with open(CACHE_DATA_JSON, 'r', encoding='utf-8') as f:
                return json.load(f)
        return None
    except Exception as e:
        print(f"加载缓存失败: {e}")
        return None

def is_cache_today(cache_data):
    """检查缓存是否是今天的"""
    if not cache_data or 'timestamp' not in cache_data:
        return False
    try:
        cache_date = datetime.fromisoformat(cache_data['timestamp']).date()
        return cache_date == datetime.now().date()
    except Exception:
        return False
