"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import CACHE_DIR, DDE_DATA_FILE, _SINA_MONEYFLOW_URL, _SINA_PREFIX_MAP, _VERBOSE
def _load_dde_from_sina_cached():
    """
    新浪财经资金流向缓存层：通过 urllib.request 直接调用新浪接口，
    返回包含 symbol/name/trade/changeratio/r0_ratio/r3_ratio/ratioamount 等
    字段的 dict-list，缓存 30 分钟。
    
    使用 urllib.request 而非 requests 库，完全绕过 push2 fail-fast patch。
    """
    try:
        import urllib.request, json

        req = urllib.request.Request(_SINA_MONEYFLOW_URL, headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
            'Accept': '*/*',
        })
        r = urllib.request.urlopen(req, timeout=20)
        raw = r.read().decode('gbk')
        data = json.loads(raw)

        # ── 格式校验：新浪接口必须返回 list[dict] ──
        if not isinstance(data, list):
            if _VERBOSE:
                print(f"[共振模型] 新浪资金流向接口返回格式异常 (期望list, 实际{type(data).__name__}), 内容: {str(data)[:200]}")
            return None

        if len(data) == 0:
            if _VERBOSE:
                print("[共振模型] 新浪资金流向接口返回空数据")
            return None

        if not isinstance(data[0], dict):
            if _VERBOSE:
                print(f"[共振模型] 新浪资金流向首项格式异常 (期望dict, 实际{type(data[0]).__name__})")
            return None

        if _VERBOSE:
            r3_ok = sum(1 for d in data if abs(float(d.get('r3_net', 0))) > 0)
            print(f"[共振模型] 新浪资金流向: {len(data)} 只, r3_net非零 {r3_ok}")

        return data

    except Exception as e:
        if _VERBOSE:
            print(f"[共振模型] 新浪资金流向接口失败: {e}")
        return None

def _load_dde_from_sina(quotes_df=None):
    """
    新浪财经资金流向备选：当 DDE Excel 不可用时，
    通过新浪 MoneyFlow API 获取资金流向数据，
    并映射为与 DDE Excel 兼容的 DataFrame 格式。

    字段映射策略（新浪 → DDE）：
      - symbol (sz000001) → 代码 (000001)
      - name → 名称
      - trade → 最新
      - changeratio (小数) → 涨幅 (%)
      - ratioamount (总净流入占比) → DDX ≈ ratioamount / 10
      - r3_ratio (大单净占比) → 特大单净比 / 大单净比（新浪不区分大单和特大单，两者填同一值）
      - DDY / DDZ / 连续 / 买卖方向 → 填 0（新浪不提供 Level-2 数据）
    """
    raw = _load_dde_from_sina_cached()
    if raw is None or len(raw) == 0:
        return None

    # 防御性检查：raw 必须是 list[dict]
    if not isinstance(raw, list) or not raw or not isinstance(raw[0], dict):
        if _VERBOSE:
            print(f"[共振模型] 新浪资金流向数据格式校验失败, type={type(raw).__name__}")
        return None

    import pandas as pd

    # ---- 解析新浪 JSON 到 DataFrame ----
    records = []
    for item in raw:
        sym = str(item.get('symbol', '')).strip()
        # 去除 sh/sz/bj 前缀，恢复纯数字代码
        if len(sym) >= 2 and sym[:2] in _SINA_PREFIX_MAP:
            code = sym[2:]
        else:
            code = sym

        # 只保留 6 位数字代码
        if not code.isdigit() or len(code) != 6:
            continue

        try:
            trade = float(item.get('trade', 0) or 0)
            changeratio = float(item.get('changeratio', 0) or 0) * 100  # 小数→百分比
            ratioamount = float(item.get('ratioamount', 0) or 0)       # 总净流入占比(%)
            r3_ratio = float(item.get('r3_ratio', 0) or 0)            # 大单净占比(%)
        except (ValueError, TypeError):
            continue

        if trade == 0:
            continue

        records.append({
            '代码': code,
            '名称': str(item.get('name', '')).strip(),
            '最新': trade,
            '涨幅': changeratio,
            'DDX': max(-3, min(3, ratioamount * 10)),
            'DDY': 0.0,
            'DDZ': 0.0,
            '5日DDX': max(-3, min(3, ratioamount * 10)),
            '5日DDY': 0.0,
            '10日DDX': max(-3, min(3, ratioamount * 10)),
            '10日DDY': 0.0,
            '连续': 0,
            '5日内': 0,
            '10日内': 0,
            '特大买入': 0.0,
            '特大卖出': 0.0,
            '特大单净比': r3_ratio * 100 if r3_ratio > 0 else ratioamount * 100,
            '大单买入': 0.0,
            '大单卖出': 0.0,
            '大单净比': r3_ratio * 100 if r3_ratio > 0 else ratioamount * 100,
        })

    base = pd.DataFrame(records)

    # ---- 过滤无效行 ----
    skip = base['代码'].isin(['000000']) | (base['最新'] == 0)
    base = base[~skip].copy()

    # ---- 与行情数据做交集 ----
    if quotes_df is not None and len(quotes_df) > 0:
        valid_codes = set(base['代码']) & set(quotes_df['代码'])
        base = base[base['代码'].isin(valid_codes)]

    # ---- 确保列顺序与 DDE Excel 一致 ----
    needed = ['代码', '名称', '最新', '涨幅', 'DDX', 'DDY', 'DDZ',
              '5日DDX', '5日DDY', '10日DDX', '10日DDY',
              '连续', '5日内', '10日内',
              '特大买入', '特大卖出', '特大单净比',
              '大单买入', '大单卖出', '大单净比']
    base = base[needed].copy()

    if _VERBOSE:
        print(f"[共振模型] 新浪备选链路返回: {len(base)} 只股票")

    return base if len(base) > 0 else None

def _get_dde_or_fallback(quotes_df=None):
    """
    DDE 数据双层降级入口：
    1. 优先读取本地 DDE Excel 文件（东方财富 DDE 数据）
    2. Excel 不可用时自动走新浪财经资金流向备选链路
    3. 全部失败返回 None
    """
    # 第一层：DDE Excel
    dde_df = _load_dde_data()
    if dde_df is not None:
        if _VERBOSE:
            print(f"[共振模型] DDE Excel 加载成功: {len(dde_df)} 只")
        return dde_df

    # 第一层失败时诊断
    if not os.path.exists(DDE_DATA_FILE):
        if _VERBOSE:
            print(f"[共振模型] DDE Excel 文件不存在: {DDE_DATA_FILE}")
    else:
        if _VERBOSE:
            print(f"[共振模型] DDE Excel 文件存在但解析失败")

    # 第二层：新浪财经资金流向
    if _VERBOSE:
        print("[共振模型] DDE Excel 不可用，尝试新浪财经资金流向备选...")

    dde_df = _load_dde_from_sina(quotes_df)
    if dde_df is not None:
        if _VERBOSE:
            print(f"[共振模型] 新浪备选链路成功: {len(dde_df)} 只 (数据源: sina)")
        return dde_df

    # 第二层失败时诊断
    if _VERBOSE:
        print("[共振模型] 新浪资金流向接口也失败 — 可能是网络问题，可稍后重试")

    # 第三层：全部失败
    return None

def _load_dde_data():
    """加载东方财富 DDE 数据文件（Excel格式），返回 DataFrame"""
    if not os.path.exists(DDE_DATA_FILE):
        if _VERBOSE: print(f"[共振模型] DDE数据文件不存在: {DDE_DATA_FILE}")
        return None
    
    try:
        import pandas as pd
        
        df = pd.read_excel(DDE_DATA_FILE)
        
        # 列名映射：东方财富Excel列名 → 标准列名
        # 实际列: 序/代码/名称/最新/涨幅%/当日资金流(DDX)/(DDY)/(DDZ)/5日资金流(5日DDX)/(5日DDY)/10日资金流(10日DDX)/(10日DDY)/DDX飘红天数(连续)/(5日内)/(10日内)/特大买入%/特大卖出%/特大单净比%/大单买入%/大单卖出%/大单净比%
        col_rename = {}
        for c in df.columns:
            c_str = str(c).strip()
            if c_str == '序':
                col_rename[c] = '序号'
            elif c_str == '代码':
                col_rename[c] = '代码'
            elif c_str == '名称':
                col_rename[c] = '名称'
            elif c_str == '最新':
                col_rename[c] = '最新'
            elif c_str == '涨幅%':
                col_rename[c] = '涨幅'
            elif c_str == '当日资金流':
                col_rename[c] = 'DDX'
            elif c_str == '5日资金流':
                col_rename[c] = '5日DDX'
            elif c_str == '10日资金流':
                col_rename[c] = '10日DDX'
            elif c_str == 'DDX飘红天数':
                col_rename[c] = '连续'
            elif c_str == '特大买入%':
                col_rename[c] = '特大买入'
            elif c_str == '特大卖出%':
                col_rename[c] = '特大卖出'
            elif c_str == '特大单净比%':
                col_rename[c] = '特大单净比'
            elif c_str == '大单买入%':
                col_rename[c] = '大单买入'
            elif c_str == '大单卖出%':
                col_rename[c] = '大单卖出'
            elif c_str == '大单净比%':
                col_rename[c] = '大单净比'
            elif 'Unnamed' in c_str:
                # Unnamed 列为 Excel 二级表头（DDY/DDZ等），列序号对应实际含义
                col_idx = df.columns.get_loc(c)
                unamed_map = {6: 'DDY', 7: 'DDZ', 9: '5日DDY', 11: '10日DDY', 13: '5日内', 14: '10日内'}
                if col_idx in unamed_map:
                    col_rename[c] = unamed_map[col_idx]
        
        df = df.rename(columns=col_rename)
        
        # 过滤掉嵌入的子标题行（第一行含"DDX"字符串的非数值行）
        if len(df) > 0:
            first_code = str(df.iloc[0].get('代码', '')).strip()
            if first_code == 'nan' or first_code == '' or first_code == 'DDX':
                df = df.iloc[1:].copy()
        
        # 需要的标准列
        needed = ['代码', '名称', '最新', '涨幅', 'DDX', 'DDY', 'DDZ',
                  '5日DDX', '5日DDY', '10日DDX', '10日DDY',
                  '连续', '5日内', '10日内',
                  '特大买入', '特大卖出', '特大单净比',
                  '大单买入', '大单卖出', '大单净比']
        
        for col in needed:
            if col not in df.columns:
                if _VERBOSE: print(f"[共振模型] 缺失列: {col}，实际列: {df.columns.tolist()}")
                return None
        
        df = df[needed].copy()
        
        # 转换数值列
        numeric_cols = ['最新', '涨幅', 'DDX', 'DDY', 'DDZ',
                        '5日DDX', '5日DDY', '10日DDX', '10日DDY',
                        '连续', '5日内', '10日内',
                        '特大买入', '特大卖出', '特大单净比',
                        '大单买入', '大单卖出', '大单净比']
        for col in numeric_cols:
            df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
        
        # 代码格式化：去除小数点，左补零到6位
        df['代码'] = df['代码'].apply(lambda x: str(int(float(x))).zfill(6) if str(x).replace('.','').replace('-','').isdigit() else str(x).zfill(6))
        
        skip = df['代码'].isin(['000000']) | (df['最新'] == 0)
        df = df[~skip]
        
        if _VERBOSE: print(f"[共振模型] 加载DDE数据: {len(df)} 只股票 (Excel解析成功)")
        return df
    except Exception as e:
        if _VERBOSE: print(f"[共振模型] DDE数据加载失败: {e}")
        import traceback
        traceback.print_exc()
        return None

def get_resonance_cache(date_str=None):
    """获取共振模型缓存数据"""
    if date_str is None:
        date_str = datetime.now().strftime('%Y%m%d')
    cache_file = os.path.join(CACHE_DIR, f'resonance_{date_str}.pkl')
    if os.path.exists(cache_file):
        try:
            with open(cache_file, 'rb') as f:
                return pickle.load(f)
        except:
            pass
    return None

def save_resonance_cache(data, date_str=None):
    """保存共振模型缓存数据"""
    if date_str is None:
        date_str = datetime.now().strftime('%Y%m%d')
    cache_file = os.path.join(CACHE_DIR, f'resonance_{date_str}.pkl')
    try:
        with open(cache_file, 'wb') as f:
            pickle.dump(data, f)
    except:
        pass

def _get_resonance_cross_ref():
    """获取共振模型交叉评分字典 {code: 综合评分} 和 {code: 当前走势}"""
    scores = {}; styles = {}
    # 优先从 session_state
    rr = []
    if not rr:
        # 回退到今日缓存文件
        cache_file = os.path.join(CACHE_DIR, f"resonance_{datetime.now().strftime('%Y%m%d')}.pkl")
        if os.path.exists(cache_file):
            try:
                with open(cache_file, 'rb') as f:
                    cache = pickle.load(f)
                rr = cache.get('results', [])
            except:
                pass
    for r in rr:
        code = str(r.get('代码', '')).zfill(6)
        scores[code] = float(r.get('综合评分', 0))
        styles[code] = r.get('当前走势', '-')
    return scores, styles
