"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import AKSHARE_AVAILABLE
from data.tdx_provider import tdx_available

def get_financial_data(code):
    """
    合并拉取一只股票的季度财务数据，返回字典。
    
    返回字段：
    - success: 是否成功获取到至少一项有效数据
    - eps_growth_yoy: 单季扣非净利润同比增速
    - roe, roe_ttm, eps_cagr_3y
    - np_recovery_q: 净利润恢复率 (T/ABS(T-4))
    - rev_recovery_q: 营收恢复率
    - roe_recovery_q: ROE环比恢复率 (T/ABS(T-1))
    - gm, gm_recovery_q: 毛利率及恢复率
    - ocf_recovery_q: 经营现金流恢复率
    - pb, debt_ratio, goodwill_ratio
    - market_cap: 总市值（亿）
    - turnover_rate: 换手率
    """
    EMPTY = {
        "success": False,
        "eps_growth_yoy": 0.0, "roe": 0.0, "eps_cagr_3y": None,
        "np_recovery_q": 0.0, "np_recovery_q_1": 0.0, "np_recovery_q_2": 0.0,
        "rev_recovery_q": 0.0,
        "roe_ttm": 0.0,
        "roe_recovery_q": 0.0, "roe_recovery_q_1": 0.0, "roe_recovery_q_2": 0.0,
        "gm": 0.0, "gm_recovery_q": 0.0, "ocf_recovery_q": 0.0,
        "pb": 999.0, "debt_ratio": 999.0, "goodwill_ratio": 999.0,
        "market_cap": 0.0, "turnover_rate": 0.0,
    }

    if not AKSHARE_AVAILABLE:
        return EMPTY

    data = dict(EMPTY)
    any_success = False

    # ---- 合并市值/换手率 ----
    spot_all = get_all_spot_data()
    spot = spot_all.get(code, {})
    cap = spot.get("总市值", 0)
    to = spot.get("换手率", 0)

    if cap > 0:
        data["market_cap"] = cap
        data["turnover_rate"] = to
        any_success = True
    else:
        # fallback: 单独请求腾讯行情 API
        try:
            import requests as _req
            prefix = 'sh' if code.startswith(('6', '5', '9')) else 'sz'
            resp = _req.get(f'http://qt.gtimg.cn/q={prefix}{code}', timeout=10,
                headers={'User-Agent': 'Mozilla/5.0'})
            for line in resp.text.strip().split('\n'):
                if '=\"' in line and '~' in line:
                    parts = line.split('\"')[1].split('~')
                    if len(parts) >= 46 and parts[2] == code:
                        try:
                            data["market_cap"] = float(parts[45])
                        except:
                            pass
                        try:
                            data["turnover_rate"] = float(parts[38])
                        except:
                            pass
                        any_success = True
                        break
        except:
            pass

    # ---- 季度利润表 ----
    profit_q = None
    try:
        profit_q = ak.stock_profit_sheet_by_quarterly_em(symbol=code)
    except:
        pass

    if profit_q is not None and len(profit_q) >= 5:
        try:
            df = profit_q.head(8).copy()
            df = df.sort_index()  # 按报告期升序（旧→新）
            cols = df.columns.tolist()
            
            def _col(name):
                for c in cols:
                    if name in c:
                        return c
                return None
            
            rev_col = _col('营业收入')
            np_col = _col('净利润')
            dnp_col = _col('扣非净利润')
            ocf_col = _col('经营活动') or _col('现金流')
            
            if np_col and dnp_col:
                def _safe(idx):
                    v = df.iloc[idx].get(dnp_col, 0)
                    return float(v) if v and v == v else 0.0
                
                # T期 = 最新季, T-4期 = 同比基期
                dnp_t = _safe(-1)
                dnp_t4 = _safe(-5)
                dnp_t1 = _safe(-2)
                dnp_t5 = _safe(-6)
                dnp_t2 = _safe(-3)
                dnp_t6 = _safe(-7)
                
                # 扣非净利润同比增速
                if dnp_t4 != 0:
                    data["eps_growth_yoy"] = (dnp_t - dnp_t4) / abs(dnp_t4)
                    any_success = True
                
                # 净利润恢复率（用净利润列）
                def _safe_np(idx):
                    v = df.iloc[idx].get(np_col, 0)
                    return float(v) if v and v == v else 0.0
                
                np_t = _safe_np(-1)
                np_t4 = _safe_np(-5)
                np_t1 = _safe_np(-2)
                np_t5 = _safe_np(-6)
                np_t2 = _safe_np(-3)
                np_t6 = _safe_np(-7)
                
                if abs(np_t4) > 0:
                    data["np_recovery_q"] = np_t / abs(np_t4)
                if abs(np_t5) > 0:
                    data["np_recovery_q_1"] = np_t1 / abs(np_t5)
                if abs(np_t6) > 0:
                    data["np_recovery_q_2"] = np_t2 / abs(np_t6)
            
            # 营收恢复率
            if rev_col:
                rev_t = float(df.iloc[-1].get(rev_col, 0) or 0)
                rev_t4 = float(df.iloc[-5].get(rev_col, 0) or 0)
                if abs(rev_t4) > 0:
                    data["rev_recovery_q"] = rev_t / abs(rev_t4)
                    any_success = True
            
            # 经营现金流恢复率
            if ocf_col:
                ocf_t = float(df.iloc[-1].get(ocf_col, 0) or 0)
                ocf_t4 = float(df.iloc[-5].get(ocf_col, 0) or 0)
                if abs(ocf_t4) > 0:
                    data["ocf_recovery_q"] = ocf_t / abs(ocf_t4)
                    any_success = True
            
            # 近3年净利润复合增速（用于CAGR）
            if len(df) >= 13:
                np_y1 = (float(df.iloc[-1].get(np_col, 0) or 0) +
                         float(df.iloc[-2].get(np_col, 0) or 0) +
                         float(df.iloc[-3].get(np_col, 0) or 0) +
                         float(df.iloc[-4].get(np_col, 0) or 0))
                np_y0 = (float(df.iloc[-13].get(np_col, 0) or 0) +
                         float(df.iloc[-12].get(np_col, 0) or 0) +
                         float(df.iloc[-11].get(np_col, 0) or 0) +
                         float(df.iloc[-10].get(np_col, 0) or 0))
                if np_y0 > 0 and np_y1 > 0:
                    data["eps_cagr_3y"] = (np_y1 / np_y0) ** (1/3) - 1
                    any_success = True
        except:
            pass

    # ---- 财务分析指标（ROE, 毛利率, 资产负债率）----
    def _find_col(cols, name):
        for c in cols:
            if name in c:
                return c
        return name

    try:
        fa_df = ak.stock_financial_analysis_indicator(symbol=code)
        if fa_df is not None and len(fa_df) > 0:
            latest = fa_df.iloc[-1]
            cols = fa_df.columns.tolist()
            
            def _fa(name):
                for c in cols:
                    if name in c:
                        v = latest.get(c, 0)
                        return float(v) if v and v == v else 0.0
                return 0.0
            
            data["roe"] = _fa('净资产收益率') / 100.0 if _fa('净资产收益率') > 1 else _fa('净资产收益率')
            data["roe_ttm"] = _fa('净资产收益率') / 100.0 if _fa('净资产收益率') > 1 else _fa('净资产收益率')
            data["gm"] = _fa('销售毛利率') / 100.0 if _fa('销售毛利率') > 1 else _fa('销售毛利率')
            data["debt_ratio"] = _fa('资产负债率') / 100.0 if _fa('资产负债率') > 1 else _fa('资产负债率')
            
            # 毛利率恢复率：T期 vs T-4期
            if len(fa_df) >= 5:
                gm_t4 = float(fa_df.iloc[-5].get(_find_col(cols, '销售毛利率'), 0) or 0)
                gm_t4 = gm_t4 / 100.0 if gm_t4 > 1 else gm_t4
                if abs(gm_t4) > 0 and data["gm"] > 0:
                    data["gm_recovery_q"] = data["gm"] / abs(gm_t4)
            
            # ROE 环比恢复率
            if len(fa_df) >= 2:
                roe_t1 = float(fa_df.iloc[-2].get(_find_col(cols, '净资产收益率'), 0) or 0)
                roe_t1 = roe_t1 / 100.0 if roe_t1 > 1 else roe_t1
                if abs(roe_t1) > 0 and data["roe"] != 0:
                    data["roe_recovery_q"] = data["roe"] / abs(roe_t1)
            if len(fa_df) >= 3:
                roe_t2 = float(fa_df.iloc[-3].get(_find_col(cols, '净资产收益率'), 0) or 0)
                roe_t2 = roe_t2 / 100.0 if roe_t2 > 1 else roe_t2
                roe_t1 = float(fa_df.iloc[-2].get(_find_col(cols, '净资产收益率'), 0) or 0)
                roe_t1 = roe_t1 / 100.0 if roe_t1 > 1 else roe_t1
                if abs(roe_t2) > 0 and roe_t1 != 0:
                    data["roe_recovery_q_1"] = roe_t1 / abs(roe_t2)
            if len(fa_df) >= 4:
                roe_t3 = float(fa_df.iloc[-4].get(_find_col(cols, '净资产收益率'), 0) or 0)
                roe_t3 = roe_t3 / 100.0 if roe_t3 > 1 else roe_t3
                roe_t2 = float(fa_df.iloc[-3].get(_find_col(cols, '净资产收益率'), 0) or 0)
                roe_t2 = roe_t2 / 100.0 if roe_t2 > 1 else roe_t2
                if abs(roe_t3) > 0 and roe_t2 != 0:
                    data["roe_recovery_q_2"] = roe_t2 / abs(roe_t3)
            
            any_success = True
    except:
        pass

    # ---- 资产负债表（商誉/净资产）----
    try:
        bs_df = ak.stock_balance_sheet_by_quarterly_em(symbol=code)
        if bs_df is not None and len(bs_df) > 0:
            latest = bs_df.iloc[-1]
            cols = bs_df.columns.tolist()
            
            def _bs(name):
                for c in cols:
                    if name in c:
                        v = latest.get(c, 0)
                        return float(v) if v and v == v else 0.0
                return 0.0
            
            goodwill = _bs('商誉')
            net_equity = _bs('净资产') or _bs('股东权益')
            if net_equity > 0 and goodwill > 0:
                data["goodwill_ratio"] = goodwill / net_equity
                any_success = True
            elif net_equity > 0:
                data["goodwill_ratio"] = 0.0
                any_success = True
    except:
        pass

    # ---- PB（从行情数据近似）----
    try:
        # 用总市值和净资产粗略估算PB
        if data["market_cap"] > 0:
            bs_df_check = ak.stock_balance_sheet_by_quarterly_em(symbol=code)
            if bs_df_check is not None and len(bs_df_check) > 0:
                latest_bs = bs_df_check.iloc[-1]
                for c in latest_bs.index:
                    if '净资产' in str(c) or '股东权益' in str(c):
                        net_eq = float(latest_bs.get(c, 0) or 0)
                        if net_eq > 0:
                            data["pb"] = (data["market_cap"] * 1e8) / net_eq
                            any_success = True
                            break
    except:
        pass

    data["success"] = any_success
    return data
