"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re
from datetime import datetime, timedelta
from collections import defaultdict

import pandas as pd
import numpy as np
from core.protocols import NullSink
from core.config import BASE_DIR, TDX_AVAILABLE, TDX_VIPDOC_DIR, _VERBOSE, _app_cache
from data.tdx_provider import (
    tdx_available, fetch_all_quotes_tdx, fetch_kline_tdx,
    get_today_quote_single, fetch_sector_data_tdx,
    get_kline_with_today as tdx_get_kline_with_today,
    resolve_market, find_tdx_vipdoc_dir as tdx_find_vipdoc,
    get_full_name_map as tdx_get_full_name_map
)

def read_tdx_day_file(stock_code):
    """
    读取通达信本地日线数据文件
    stock_code: 6位代码 如 '000001'
    返回 DataFrame[日期,开盘,最高,最低,收盘,成交量,成交额] 或 None
    """
    if not TDX_VIPDOC_DIR:
        return None
    try:
        code = str(stock_code).zfill(6)
        # 判断沪/深/北
        if code.startswith(('6', '9')):
            filepath = os.path.join(TDX_VIPDOC_DIR, "sh", "lday", f"sh{code}.day")
        elif code.startswith(('0', '3', '2')):
            filepath = os.path.join(TDX_VIPDOC_DIR, "sz", "lday", f"sz{code}.day")
        elif code.startswith(('4', '8')):
            filepath = os.path.join(TDX_VIPDOC_DIR, "bj", "lday", f"bj{code}.day")
        else:
            return None

        if not os.path.exists(filepath):
            return None

        record_size = 32  # 每条记录32字节
        data = []
        with open(filepath, 'rb') as f:
            while True:
                raw = f.read(record_size)
                if len(raw) < record_size:
                    break
                # 通达信day文件标准格式 (32字节/条):
                # date(uint32) open(uint32) high(uint32) low(uint32) close(uint32) amount(float32) volume(uint32) reserved(uint32)
                # 价格字段存储为 实际价格×100 的整数
                date_int, open_i, high_i, low_i, close_i, amount, volume, _ = struct.unpack('<IIIIIfII', raw[:32])
                # 价格除以100还原（通达信标准存储方式）
                open_p = open_i / 100.0
                high_p = high_i / 100.0
                low_p = low_i / 100.0
                close_p = close_i / 100.0
                # 校验日期范围
                if date_int < 19900101 or date_int > 20991231:
                    continue
                # 校验价格合理性
                if close_p <= 0 or close_p > 100000:
                    continue
                data.append({
                    '日期': pd.Timestamp(str(date_int)),
                    '开盘': open_p,
                    '最高': high_p,
                    '最低': low_p,
                    '收盘': close_p,
                    '成交量': volume,
                    '成交额': amount,
                })
        if not data:
            return None
        df = pd.DataFrame(data)
        df = df.sort_values('日期').reset_index(drop=True)
        return df
    except Exception:
        return None

def _supplement_tencent_quotes(df):
    """用腾讯微证券 API 补齐 pytdx 缺失的量比、换手率和名称。
    腾讯 API: qt.gtimg.cn, parts[1]=名称, parts[38]=换手率, parts[39]=PE(动态), parts[46]=量比
    分批请求（每批150只），顺序执行避免限流。
    """
    if df is None or len(df) == 0:
        return df
    try:
        import requests as _req
        codes = df['代码'].astype(str).values
        # 构建带市场前缀的代码列表
        def _to_tx(code):
            return ('sh' if code.startswith(('6','5','9')) else 'sz') + code
        tx_codes = [_to_tx(c) for c in codes]

        BATCH = 150
        results = {}  # code -> (量比, 换手率, PE, 名称)

        for batch_idx in range((len(tx_codes) + BATCH - 1) // BATCH):
            batch = tx_codes[batch_idx * BATCH : (batch_idx + 1) * BATCH]
            query = ','.join(batch)
            try:
                resp = _req.get(f'http://qt.gtimg.cn/q={query}', timeout=15,
                    headers={'User-Agent': 'Mozilla/5.0'})
                for line in resp.text.strip().split('\n'):
                    if '=\"' in line and '~' in line:
                        parts = line.split('\"')[1].split('~')
                        if len(parts) >= 47:
                            raw_code = parts[2]  # e.g. '600000'
                            # 名称
                            name = parts[1].strip() if parts[1] else ''
                            try:
                                vol_ratio = float(parts[46])
                            except (ValueError, IndexError):
                                vol_ratio = 1.0
                            try:
                                turnover = float(parts[38])
                            except (ValueError, IndexError):
                                turnover = 0.0
                            try:
                                pe = float(parts[39])
                            except (ValueError, IndexError):
                                pe = 0.0
                            results[raw_code] = (vol_ratio, turnover, pe, name)
            except Exception:
                continue  # 单批失败不阻塞整体

        # 合并到 DataFrame
        if results:
            vr_map, to_map, pe_map, name_map = {}, {}, {}, {}
            for code, (vr, to, pe, name) in results.items():
                vr_map[code] = vr
                to_map[code] = to
                if pe > 0:
                    pe_map[code] = pe
                if name:
                    name_map[code] = name
            df_codes = df['代码'].astype(str)
            df['量比'] = pd.to_numeric(df_codes.map(vr_map), errors='coerce')
            df['量比'] = df['量比'].fillna(1.0)
            df['换手率'] = pd.to_numeric(df_codes.map(to_map), errors='coerce')
            df['换手率'] = df['换手率'].fillna(0.0)
            # 补充PE：仅填充空值
            if pe_map:
                pe_mask = df['市盈率-动态'].isna() | (df['市盈率-动态'] == 0)
                pe_vals = pd.to_numeric(df_codes[pe_mask].map(pe_map), errors='coerce')
                df.loc[pe_mask, '市盈率-动态'] = pe_vals.astype(float)
            # 修复名称：用腾讯数据覆盖所有匹配到的名称（腾讯名称更可靠）
            if name_map:
                df['名称'] = df_codes.map(name_map).fillna(df['名称'])
            if _VERBOSE: print(f"[Tencent] 补充量比/换手率/PE+名称: {len(results)}/{len(df)} 只匹配")
        return df
    except Exception as _e:
        if _VERBOSE: print(f"[Tencent] 补充数据异常: {_e}")
        return df

def _fetch_all_a_stocks_tdx():
    """通过 pytdx 从通达信服务器获取全市场A股实时行情"""
    if not tdx_available():
        print("[TDX] pytdx 不可用")
        return None
    try:
        df = fetch_all_quotes_tdx()
        if df is not None and len(df) > 0:
            if _VERBOSE: print(f"[TDX] 成功获取 {len(df)} 条股票行情数据")
            df = _supplement_tencent_quotes(df)
            return df
    except Exception as e:
        if _VERBOSE: print(f"[TDX] 行情获取异常: {e}")
    return None

def fetch_all_a_stocks(sink=None):
    if sink is None:
        sink = NullSink()
    """获取A股全市场实时行情数据（模块级缓存30分钟）
    优先：pytdx 从通达信服务器获取快速行情快照
    兜底：akshare stock_zh_a_spot_em
    回退：本地文件缓存
    """
    # 模块级缓存优先
    if _app_cache['raw_market_data'] is not None and _app_cache['raw_market_time']:
        if (time.time() - _app_cache['raw_market_time']) < 1800:
            return _app_cache['raw_market_data']

    if not tdx_available() and not AKSHARE_AVAILABLE:
        return None

    try:
        sink.on_status("正在获取A股全市场行情数据...")
        df = None

        # 第一优先级：pytdx 通达信
        if tdx_available():
            try:
                df = _fetch_all_a_stocks_tdx()
                if df is not None and len(df) > 0:
                    if _VERBOSE: print(f"[pytdx] 获取到 {len(df)} 只股票")
            except Exception as _tdx_e:
                print(f"[pytdx失败] {_tdx_e}，尝试akshare...")

        # 第二优先级：akshare 兜底（带超时保护，避免push2 API阻塞）
        if df is None or len(df) == 0:
            if AKSHARE_AVAILABLE:
                import threading
                _ak_result = [None]
                _ak_error = [None]
                def _ak_fetch():
                    try:
                        _ak_result[0] = ak.stock_zh_a_spot_em()
                    except Exception as e:
                        _ak_error[0] = e
                _ak_thread = threading.Thread(target=_ak_fetch, daemon=True)
                _ak_thread.start()
                _ak_thread.join(timeout=8)
                if _ak_thread.is_alive():
                    if _VERBOSE: print("[akshare] 超时跳过")
                elif _ak_error[0] is not None:
                    print(f"[akshare失败] {_ak_error[0]}")
                elif _ak_result[0] is not None and len(_ak_result[0]) > 0:
                    df = _ak_result[0]
                    if _VERBOSE: print(f"[akshare] 获取到 {len(df)} 只股票")

        # 第三优先级：本地文件缓存回退
        if df is None or len(df) == 0:
            try:
                cache_path = os.path.join(BASE_DIR, 'market_data_cache.json')
                if os.path.exists(cache_path):
                    with open(cache_path, 'r', encoding='utf-8') as _f:
                        cached = json.load(_f)
                    if cached and 'data' in cached and len(cached['data']) > 0:
                        df = pd.DataFrame(cached['data'])
                        cache_age = time.time() - cached.get('timestamp', 0)
                        _app_cache['raw_market_data'] = df
                        _app_cache['raw_market_time'] = time.time()
                        if _VERBOSE: print(f"[缓存回退] 已使用 {len(df)} 条本地缓存数据")
                        return df
            except Exception as _cache_e:
                print(f"[缓存回退失败] {_cache_e}")
            print("获取数据为空，请检查通达信连接和网络")
            return None

        # 存入模块级缓存
        _app_cache['raw_market_data'] = df
        _app_cache['raw_market_time'] = time.time()

        # 保存到本地文件作为回退
        try:
            cache_path = os.path.join(BASE_DIR, 'market_data_cache.json')
            with open(cache_path, 'w', encoding='utf-8') as _f:
                json.dump({
                    'timestamp': time.time(),
                    'data': df.to_dict(orient='records')
                }, _f, ensure_ascii=False)
            if _VERBOSE: print(f"[缓存] 已保存 {len(df)} 条行情数据到本地文件")
        except Exception as _e:
            if _VERBOSE: print(f"[缓存] 保存本地缓存失败: {_e}")
        return df
    except Exception as e:
        print(f"获取行情数据失败: {e}")
        return None

def preprocess_stock_data(df_raw):
    """数据预处理和过滤"""
    if df_raw is None or len(df_raw) == 0:
        return None
    df = df_raw.copy()
    
    required_cols = ['代码', '名称', '最新价', '涨跌幅']
    for col in required_cols:
        if col not in df.columns:
            print(f"缺少必要列: {col}")
            return None
    
    # 排除ST/*ST股票
    df = df[~df['名称'].str.contains('ST|退市', case=False, na=False)]
    
    # 排除停牌股票
    if '成交量' in df.columns:
        df = df[df['成交量'] > 0]
    if '最新价' in df.columns:
        df = df[df['最新价'] > 0]
    
    # 数据类型转换
    numeric_cols = ['最新价', '涨跌幅', '涨跌额', '成交量', '成交额', '振幅', 
                    '最高', '最低', '今开', '昨收', '量比', '换手率']
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # 兼容本地缓存文件的列名差异：缓存的 '市盈率' → '市盈率-动态'
    if '市盈率' in df.columns and '市盈率-动态' not in df.columns:
        df.rename(columns={'市盈率': '市盈率-动态'}, inplace=True)
    
    if '市盈率-动态' in df.columns:
        df['市盈率-动态'] = pd.to_numeric(df['市盈率-动态'], errors='coerce')
    if '市净率' in df.columns:
        df['市净率'] = pd.to_numeric(df['市净率'], errors='coerce')
    
    # 确保代码是6位字符串
    df['代码'] = df['代码'].astype(str).str.zfill(6)
    
    return df.reset_index(drop=True)

def get_stock_kline(code, days=30):
    """
    获取个股日K线数据
    优先从通达信本地数据读取（毫秒级），失败则回退 pytdx get_security_bars
    """
    # === 优先尝试通达信本地数据 ===
    if TDX_AVAILABLE:
        df = read_tdx_day_file(code)
        if df is not None and len(df) > 0:
            return df.tail(days)

    # === 回退到 pytdx ===
    if tdx_available():
        df = fetch_kline_tdx(code, days=days)
        if df is not None and len(df) > 0:
            return df

    return None

def get_kline_with_today(code, days=60):
    """Get K-line data with today's forming candle appended via pytdx real-time quote"""
    df = get_stock_kline(code, days=days)
    if df is None or len(df) == 0:
        return df, False
    now = datetime.now()
    if now.weekday() >= 5:
        return df, False
    hour_min = now.hour * 100 + now.minute
    if hour_min < 915 or hour_min > 1505:
        return df, False
    last_date_str = str(df.iloc[-1].get('\u65e5\u671f', ''))
    today_str = now.strftime('%Y-%m-%d')
    today_str2 = now.strftime('%Y%m%d')
    if today_str in last_date_str or today_str2 in last_date_str:
        return df, False
    if not tdx_available():
        return df, False
    try:
        today_quote = get_today_quote_single(code)
        if today_quote is None:
            return df, False
        today_close = today_quote.get('最新价', 0)
        today_open = today_quote.get('今开', 0)
        if today_close <= 0:
            return df, False
        today_row = {
            '\u65e5\u671f': today_str,
            '\u5f00\u76d8': today_open,
            '\u6700\u9ad8': today_quote.get('最高', today_close),
            '\u6700\u4f4e': today_quote.get('最低', today_close),
            '\u6536\u76d8': today_close,
            '\u6210\u4ea4\u91cf': today_quote.get('成交量', 0),
            '\u6210\u4ea4\u989d': today_quote.get('成交额', 0),
        }
        new_row = pd.DataFrame([today_row])
        df = pd.concat([df, new_row], ignore_index=True)
        return df, True
    except Exception as e:
        print(f"Append today K-line failed: {e}")
        return df, False

def get_all_spot_data():
    """
    通过腾讯行情 API (qt.gtimg.cn) 拉取全市场行情快照，提取总市值和换手率，
    返回 {code: {"总市值": float(yi), "换手率": float}}。失败返回空字典。
    使用腾讯 API 绕过 push2.eastmoney.com 阻断。
    """
    result = {}
    try:
        import requests as _req

        # 获取股票代码列表（优先从本地缓存，其次从市场数据）
        codes = _load_stock_code_list()
        if not codes:
            if _VERBOSE:
                print("[腾讯行情] 无法获取股票代码列表")
            return result

        def _to_tx(code):
            return ('sh' if code.startswith(('6', '5', '9')) else 'sz') + code

        tx_codes = [_to_tx(c) for c in codes]
        BATCH = 80  # qt.gtimg.cn 批量上限，避免超长URL

        for i in range((len(tx_codes) + BATCH - 1) // BATCH):
            batch = tx_codes[i * BATCH : (i + 1) * BATCH]
            query = ','.join(batch)
            try:
                resp = _req.get(f'http://qt.gtimg.cn/q={query}', timeout=15,
                    headers={'User-Agent': 'Mozilla/5.0'})
                for line in resp.text.strip().split('\n'):
                    if '=\"' in line and '~' in line:
                        parts = line.split('\"')[1].split('~')
                        if len(parts) >= 46:
                            raw_code = parts[2]
                            try:
                                cap_yi = float(parts[45])  # field 45: 总市值（亿元）
                            except (ValueError, IndexError):
                                cap_yi = 0.0
                            try:
                                turnover = float(parts[38])  # field 38: 换手率
                            except (ValueError, IndexError):
                                turnover = 0.0
                            if cap_yi > 0:
                                result[raw_code] = {"总市值": cap_yi, "换手率": turnover}
            except Exception:
                continue  # 单批失败不阻塞整体

            # 分批间隔，避免限流
            if i < (len(tx_codes) + BATCH - 1) // BATCH - 1:
                time.sleep(0.25)

        if _VERBOSE:
            print(f"[腾讯行情] 全市场行情: {len(result)}/{len(codes)} 只有效数据")
    except Exception as e:
        if _VERBOSE:
            print(f"[腾讯行情] 全市场行情获取失败: {e}")
    return result

def _load_stock_code_list():
    """加载A股全市场股票代码列表。
    优先级：本地代码缓存 > 本地行情缓存 > akshare stock_info_a_code_name（上交所/深交所官网API）
    """
    codes = []
    cache_dir = os.path.join(BASE_DIR, '.cache')
    os.makedirs(cache_dir, exist_ok=True)
    code_list_path = os.path.join(cache_dir, 'a_stock_code_list.json')

    # 第一优先级：本地代码缓存（7天有效）
    try:
        if os.path.exists(code_list_path):
            with open(code_list_path, 'r', encoding='utf-8') as f:
                cached = json.load(f)
            if time.time() - cached.get('ts', 0) < 7 * 86400:
                codes = cached.get('codes', [])
                if codes:
                    return codes
    except Exception:
        pass

    # 第二优先级：本地行情缓存
    try:
        cache_path = os.path.join(BASE_DIR, 'market_data_cache.json')
        if os.path.exists(cache_path):
            with open(cache_path, 'r', encoding='utf-8') as f:
                cached = json.load(f)
            records = cached.get('data', [])
            codes = [str(r.get('代码', '')).zfill(6) for r in records if r.get('代码')]
            codes = list(dict.fromkeys(codes))
            if codes:
                return codes
    except Exception:
        pass

    # 第三优先级：从 fetch_all_a_stocks 获取
    try:
        df = fetch_all_a_stocks()
        if df is not None and len(df) > 0:
            codes = df['代码'].astype(str).apply(lambda x: x.zfill(6)).unique().tolist()
            if codes:
                return codes
    except Exception:
        pass

    # 第四优先级（兜底）：从 akshare 获取完整A股代码列表（上交所/深交所官网）
    try:
        if AKSHARE_AVAILABLE:
            df_info = ak.stock_info_a_code_name()
            if df_info is not None and len(df_info) > 0:
                codes = df_info['code'].astype(str).apply(lambda x: x.zfill(6)).unique().tolist()
                # 保存到本地缓存
                try:
                    with open(code_list_path, 'w', encoding='utf-8') as f:
                        json.dump({'ts': time.time(), 'codes': codes}, f)
                except Exception:
                    pass
    except Exception:
        pass

    return codes

def calculate_dynamic_recommend_count(default=10):
    """
    根据上证指数(000001)的市场状态，动态计算当日推荐股票数量。

    判断指标：
    - 20日涨跌幅：指数最近20个交易日的涨跌
    - 量能趋势：最近5日均量 vs 20日均量
    - 均线排列：5日均线是否在20日均线上方
    - 连续下跌天数：最近5日中有多少日收跌

    市场状态 → 推荐数量：
    - 强势牛市（涨>5%，多头排列，放量） → 12-15只
    - 偏强（涨>3%，多头排列） → 10-12只
    - 震荡偏强（涨>0% 或 微跌+放量） → 9只
    - 震荡（-3% ~ 0%） → 8只
    - 偏弱（-5% ~ -3%） → 5-7只
    - 熊市（跌超5%） → 3-5只
    - 极端行情（连跌5日+跌超10%） → 0只

    兜底：市场数据获取失败时返回 default (10只)
    """
    try:
        kline = get_stock_kline('000001', days=60)
        if kline is None or len(kline) < 25:
            return default

        close_col = '收盘' if '收盘' in kline.columns else 'close'
        volume_col = '成交量' if '成交量' in kline.columns else 'volume'

        closes = kline[close_col].values.astype(float)
        volumes = kline[volume_col].values.astype(float)
        n = len(closes)

        # 1. 20日涨跌幅
        chg_20d = (closes[-1] / closes[max(0, n - 21)] - 1) * 100

        # 2. 量能趋势 (5日均量 vs 20日均量)
        vol_5 = np.mean(volumes[-5:]) if n >= 5 else np.mean(volumes)
        vol_20 = np.mean(volumes[-20:]) if n >= 20 else np.mean(volumes)
        vol_ratio = vol_5 / vol_20 if vol_20 > 0 else 1.0

        # 3. 均线多头 (5日 > 20日)
        ma5 = np.mean(closes[-5:]) if n >= 5 else closes[-1]
        ma20 = np.mean(closes[-20:]) if n >= 20 else closes[-1]
        ma_bull = ma5 > ma20

        # 4. 连续下跌检测
        down_days = 0
        for i in range(max(0, n - 5), n - 1):
            if closes[i + 1] < closes[i]:
                down_days += 1

        # 极端行情: 连续5日下跌且20日跌幅>10%
        if down_days >= 5 and chg_20d < -10:
            return 0

        # 市场状态判定 → 基础推荐数量
        if chg_20d > 5 and ma_bull and vol_ratio > 1.1:
            base = 12
        elif chg_20d > 3 and ma_bull:
            base = 11
        elif chg_20d > 0 or (chg_20d > -1 and vol_ratio > 1.0):
            base = 9
        elif chg_20d >= -3:
            base = 8
        elif chg_20d >= -5:
            base = 6
        else:
            base = 4

        # 量能微调：放量+1，缩量-1
        if vol_ratio > 1.2:
            base += 1
        elif vol_ratio < 0.8:
            base -= 1

        # 反弹初期加成：均线多头但指数还在跌 → 多给推荐
        if ma_bull and chg_20d < 0:
            base += 1

        return max(0, min(15, base))

    except Exception:
        return default
