"""Auto-generated by refactor_split.py — DO NOT edit manually."""
import os, json, time, re, struct, glob, pickle, io, logging, traceback
from datetime import datetime, timedelta
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from core.config import _VERBOSE, _app_cache
from data.tdx_provider import tdx_available, fetch_sector_data_tdx

def _get_cached_dragon_tiger():
    """获取龙虎榜数据（模块级缓存，1小时有效）"""
    now = time.time()
    if _app_cache['dragon_tiger'] is not None and _app_cache['dragon_tiger_time'] and (now - _app_cache['dragon_tiger_time']) < 3600:
        return _app_cache['dragon_tiger']
    data = fetch_dragon_tiger_v3()
    _app_cache['dragon_tiger'] = data
    _app_cache['dragon_tiger_time'] = now
    return data

def _get_cached_sector_data():
    """获取板块数据（模块级缓存，30分钟有效）"""
    now = time.time()
    if _app_cache['sector_data'] is not None and _app_cache['sector_time'] and (now - _app_cache['sector_time']) < 1800:
        return _app_cache['sector_data'], _app_cache['sector_map']
    data, smap = fetch_sector_board_v3()
    _app_cache['sector_data'] = data
    _app_cache['sector_map'] = smap
    _app_cache['sector_time'] = now
    return data, smap

def _get_sector_fund_flow():
    """计算板块资金流向（追高模型前置门槛用）。
    聚合 DDE 数据按板块平均净资金流比例（特大单净比+大单净比）。
    返回: {sector_name: avg_flow_ratio}，正值=净流入，负值=净流出。
    缓存30分钟。
    """
    now = time.time()
    if _app_cache['sector_fund_flow'] is not None and _app_cache['sector_fund_flow_time'] \
            and (now - _app_cache['sector_fund_flow_time']) < 1800:
        return _app_cache['sector_fund_flow']

    dde_df = _load_dde_data()
    if dde_df is None or len(dde_df) == 0:
        return {}

    _, stock_sector_map = _get_cached_sector_data()
    if not stock_sector_map:
        return {}

    # 计算每只股票的净资金流比例
    dde_df['特大单净比'] = pd.to_numeric(dde_df['特大单净比'], errors='coerce').fillna(0)
    dde_df['大单净比'] = pd.to_numeric(dde_df['大单净比'], errors='coerce').fillna(0)
    dde_df['5日DDX'] = pd.to_numeric(dde_df['5日DDX'], errors='coerce').fillna(0)
    dde_df['fund_flow_ratio'] = dde_df['特大单净比'] + dde_df['大单净比']
    # 主力净比为0时，用5日DDX作为替代
    mask_zero = dde_df['fund_flow_ratio'] == 0
    dde_df.loc[mask_zero, 'fund_flow_ratio'] = dde_df.loc[mask_zero, '5日DDX']

    # 按板块聚合
    sector_flows = defaultdict(list)
    for _, row in dde_df.iterrows():
        code = str(row['代码'])
        sector = stock_sector_map.get(code)
        if sector:
            sector_flows[sector].append(row['fund_flow_ratio'])

    # 板块平均资金流向
    result = {}
    for sector, flows in sector_flows.items():
        if flows:
            result[sector] = sum(flows) / len(flows)

    _app_cache['sector_fund_flow'] = result
    _app_cache['sector_fund_flow_time'] = now
    if _VERBOSE:
        inflow_count = sum(1 for v in result.values() if v > 0)
        outflow_count = sum(1 for v in result.values() if v <= 0)
        print(f"[板块资金] 净流入板块: {inflow_count}, 净流出板块: {outflow_count}, 总计: {len(result)}")
    return result

def fetch_dragon_tiger_v3():
    """获取龙虎榜数据，返回 {code: {inst_net_buy_3d, north_net_buy, pure_hot_money_only}}"""
    try:
        import akshare as ak
        today_str = datetime.now().strftime('%Y%m%d')
        cache_key = f"lhb_v3_{today_str}"
        pass
        result = {}
        for days_ago in range(5):
            try:
                dt = (datetime.now() - timedelta(days=days_ago)).strftime('%Y%m%d')
                df = ak.stock_lhb_detail_em(start_date=dt, end_date=dt)
                if df is None or len(df) == 0:
                    continue
                for _, r in df.iterrows():
                    code = str(r.get('代码', ''))
                    if not code or len(code) != 6:
                        continue
                    if code not in result:
                        result[code] = {'inst_net_buy_3d': 0, 'north_net_buy': 0,
                                        'pure_hot_money_only': True, 'inst_sell_2d': False,
                                        'inst_net_sell_2d': False}
                    buyer_str = str(r.get('买方', '')) + str(r.get('解读', ''))
                    if '机构' in buyer_str or '机构专用' in buyer_str:
                        result[code]['pure_hot_money_only'] = False
                        result[code]['inst_net_buy_3d'] += float(r.get('买入额', 0) or 0) - float(r.get('卖出额', 0) or 0)
                    if '北向' in buyer_str or '沪股通' in buyer_str or '深股通' in buyer_str:
                        result[code]['north_net_buy'] += float(r.get('买入额', 0) or 0)
            except:
                continue
        # cached in app layer
        return result
    except Exception as e:
        print(f"龙虎榜数据获取失败: {e}")
    return {}

def fetch_sector_board_v3():
    """获取板块行情数据（通过 pytdx 通达信板块数据）
    返回: ({板块名: {daily_gain, limit_up_count, net_inflow}}, {stock_code: sector_name})
    """
    if not tdx_available():
        return {}, {}
    try:
        sector_board, stock_sector_map = fetch_sector_data_tdx()
        if _VERBOSE: print(f"[pytdx] 板块数据: {len(sector_board)} 个板块, {len(stock_sector_map)} 只成分股映射")
        return sector_board, stock_sector_map
    except Exception as e:
        print(f"板块数据获取失败: {e}")
    return {}, {}

def _classify_stock_sector(stock_code, stock_name, sector_board_data, stock_sector_map=None):
    """根据股票代码匹配所属板块（优先使用成分股映射）"""
    import re
    code = str(stock_code)
    # 优先：通过成分股反向映射精确匹配
    if stock_sector_map and code in stock_sector_map:
        sec = stock_sector_map[code]
        # 🔧 P0修复: 过滤 pytdx 内部非中文编码（如 W300881W3、20175920 等）
        if re.search(r'[\u4e00-\u9fff]', sec):
            return sec
    # 备选：关键词匹配
    name = str(stock_name)
    kw_map = {'半导体': '半导体', '芯片': '半导体', 'AI': 'AI算力',
              '算力': 'AI算力', '光模块': 'AI算力', '云': '云计算',
              '软件': '云计算', '新能源': '新能源', '锂电': '新能源',
              '光伏': '新能源', '医药': '医药', '医疗': '医药',
              '白酒': '白酒', '食品': '食品饮料', '消费': '食品饮料'}
    for kw, sec in kw_map.items():
        if kw in name and sec in sector_board_data:
            return sec
    return None  # 未匹配到有效板块
